Repository taosdata/TDengine, pull requests merged in 2019-08, with the labels that each got.

#274 alter_examples_bash
  tests/examples/bash/demo.csv
  tests/examples/bash/demo.sql
Labels: documentation

#124 Modify json's date to Json standard time format ISO-8601
  src/modules/http/src/httpJson.c
Labels: enhancement

#346 upload code for cassandra/tdengine test
  tests/comparisonTest/cassandra/application.conf
  tests/comparisonTest/cassandra/cassandratest/pom.xml
  tests/comparisonTest/cassandra/cassandratest/src/main/java/com/cassandra/test/CassandraTest.java
  tests/comparisonTest/cassandra/cassandratest/src/main/java/com/cassandra/test/WriteThread.java
  tests/comparisonTest/cassandra/q1.txt
  tests/comparisonTest/cassandra/q2.txt
  tests/comparisonTest/cassandra/q3.txt
  tests/comparisonTest/cassandra/q4.txt
Labels: good first issue
