Repository taosdata/TDengine, pull requests merged in 2025-09, with the labels that each got.

#32811 fix: ignore error while calc dir size
  source/dnode/vnode/src/vnd/vnodeQuery.c
Labels: team engine

#32834 refactor: simplify get started
  docs/zh/04-get-started/01-docker.mdx
  docs/zh/04-get-started/03-package.mdx
Labels: team platform

#32836 doc: add more additional notes for config.
  docs/en/14-reference/01-components/01-taosd.md
  docs/zh/14-reference/01-components/01-taosd.md
Labels: team engine

#32839 fix: update UDF example paths to correct directory
  docs/en/07-develop/09-udf.md
  docs/zh/07-develop/09-udf.md
  test/cases/23-UDFs/sh/compile_udf.sh
  tests/coverage/covtests.task
Labels: team platform

#32843 fix: state window desc true for issue
  source/libs/executor/src/executorInt.c
Labels: team engine

#32827 fix[TS-7192]: alter database cannot set ss_keeplocal to 1440m
  source/dnode/mnode/impl/src/mndDb.c
Labels: team engine

#32851 enh: destroy mutex of file object
  source/dnode/vnode/src/tsdb/tsdbFSet2.c
  source/dnode/vnode/src/tsdb/tsdbFile2.c
Labels: team engine

#32852 enh: destroy mutex of file object
  source/dnode/vnode/src/tsdb/tsdbFSet2.c
  source/dnode/vnode/src/tsdb/tsdbFile2.c
Labels: team engine

#32858 fix:update taosd startup command in workflow
  .github/workflows/tdengine-release-build.yml
Labels: team platform

#32862 docs: update ha docs for en
  docs/en/08-operation/18-dual.md
  docs/en/08-operation/18-ha/01-replica3.md
  docs/en/08-operation/18-ha/02-replica2.md
  docs/en/08-operation/18-ha/03-dual.md
  docs/en/08-operation/18-ha/index.md
  docs/en/assets/dual-01.png
  docs/en/assets/replica2-01.png
Labels: internal

#32848 fix: query on dnode
  source/libs/planner/src/planOptimizer.c
  test/cases/22-Show/test_show_basic.py
Labels: team engine

#32832 merge: from 3.3.6 to main branch
  include/libs/nodes/nodes.h
  source/common/src/tanalytics.c
  source/common/src/tdatablock.c
  source/dnode/vnode/src/tsdb/tsdbCacheRead.c
  source/libs/executor/src/cachescanoperator.c
  source/libs/function/src/builtins.c
  source/libs/function/src/builtinsimpl.c
  source/libs/function/src/functionMgt.c
  source/libs/nodes/src/nodesUtilFuncs.c
  source/libs/planner/src/planOptimizer.c
  test/cases/22-Functions/03-Selection/ans/last_with_cols.csv
  test/cases/22-Functions/03-Selection/in/last_with_cols.in
  test/cases/22-Functions/03-Selection/test_select_first_last.py
  test/cases/25-JoinQueries/test_join_tbname.py
  test/cases/uncatalog/system-test/2-query/test_cols_function.py
  test/ci/cases.task
Labels: team engine

#32869 Update 01-index.md
  docs/zh/01-index.md
Labels: from community

#32727 fix(tmq): set pointer = NULL to avoid double free
  source/client/src/clientMonitor.c
  source/dnode/mnode/impl/inc/mndDef.h
  source/dnode/mnode/impl/src/mndConsumer.c
  source/dnode/mnode/impl/src/mndDef.c
  source/dnode/mnode/impl/src/mndSubscribe.c
  source/dnode/mnode/impl/src/mndTopic.c
Labels: team engine

#32861 fix(stream): auto create normal table error in tmq
  source/client/src/clientRawBlockWrite.c
  source/dnode/vnode/inc/vnode.h
  source/dnode/vnode/src/meta/metaQuery.c
  source/dnode/vnode/src/tq/tqRead.c
  source/dnode/vnode/src/tq/tqScan.c
  test/cases/uncatalog/system-test/7-tmq/test_tmq_td37436.py
  test/ci/cases.task
  utils/test/c/CMakeLists.txt
  utils/test/c/tmq_td37436.c
Labels: team engine

#32880 Windows case opt 0903
  test/cases/40-DataSubscription/02-Native/test_tmq_cons1_v1_snapshot.py
  test/cases/40-DataSubscription/02-Native/test_tmq_cons1_v1_t1.py
  test/cases/40-DataSubscription/02-Native/test_tmq_cons1_v1_tn.py
  test/cases/40-DataSubscription/02-Native/test_tmq_cons1_v4_t1.py
  test/cases/40-DataSubscription/02-Native/test_tmq_cons1_v4_tn.py
  test/cases/40-DataSubscription/02-Native/test_tmq_cons2_v1_overlap.py
  test/cases/40-DataSubscription/02-Native/test_tmq_cons2_v1_snapshot.py
  test/cases/40-DataSubscription/02-Native/test_tmq_cons2_v1_t1.py
  test/cases/40-DataSubscription/02-Native/test_tmq_cons2_v1_tn.py
  test/cases/40-DataSubscription/02-Native/test_tmq_cons2_v4_t1.py
  test/cases/40-DataSubscription/02-Native/test_tmq_cons2_v4_tn.py
  test/cases/uncatalog/system-test/0-others/test_taosd_audit.py
  test/cases/uncatalog/system-test/1-insert/test_insertWithMoreVgroup.py
  test/cases/uncatalog/system-test/1-insert/test_mutil_stage.py
  test/cases/uncatalog/system-test/2-query/test_partition_by_col.py
  test/cases/uncatalog/system-test/2-query/test_partition_by_col_agg.py
  test/cases/uncatalog/system-test/2-query/test_queryQnode.py
  test/cases/uncatalog/system-test/3-enterprise/restore/restore_basic.py
  test/ci/win_ignore_cases
  test/new_test_framework/taostest/components/taosd.py
Labels: team platform

#32889 docs: update link to taosd documentation in stream processing parameters
  docs/en/14-reference/03-taos-sql/41-stream.md
Labels: team platform

#32890 docs: update config parameters
  .gitignore
  docs/en/14-reference/01-components/01-taosd.md
  docs/en/14-reference/01-components/08-config-scope.md
  docs/zh/14-reference/01-components/01-taosd.md
  docs/zh/14-reference/01-components/08-config-scope.md
Labels: team engine

#32894 docs: update config parameters and coverage lists.txt
  test/ci/coverage.txt
Labels: team engine

#32897 Revert "fix: cols(last)"
  include/libs/nodes/nodes.h
  source/dnode/vnode/src/tsdb/tsdbCacheRead.c
  source/libs/executor/src/cachescanoperator.c
  source/libs/function/src/builtins.c
  source/libs/function/src/builtinsimpl.c
  source/libs/function/src/functionMgt.c
  source/libs/nodes/src/nodesUtilFuncs.c
  source/libs/planner/src/planOptimizer.c
  test/cases/10-Functions/03-Selection/ans/last_with_cols.csv
  test/cases/10-Functions/03-Selection/in/last_with_cols.in
  test/cases/10-Functions/03-Selection/test_func_last_both.py
  tests/system-test/2-query/cols_function.py
Labels: team engine

#32906 merge: from 3.3.6 to main branch
  include/libs/nodes/nodes.h
  source/dnode/vnode/src/tsdb/tsdbCacheRead.c
  source/libs/executor/src/cachescanoperator.c
  source/libs/function/src/builtins.c
  source/libs/function/src/builtinsimpl.c
  source/libs/function/src/functionMgt.c
  source/libs/nodes/src/nodesUtilFuncs.c
  source/libs/planner/src/planOptimizer.c
Labels: team engine

#32879 docs(data-publisher): add section data-publisher in advanced functionalities
  docs/en/06-advanced/07-data-publisher/01-MQTT.md
  docs/en/06-advanced/07-data-publisher/index.md
  docs/en/14-reference/01-components/04-taosx.md
  docs/zh/06-advanced/07-data-publisher/01-MQTT.md
  docs/zh/06-advanced/07-data-publisher/index.md
  docs/zh/14-reference/01-components/04-taosx.md
Labels: team tools

#32911 merge: from 3.3.6 to main branch
  docs/en/14-reference/01-components/01-taosd.md
  docs/zh/14-reference/01-components/01-taosd.md
  include/common/tglobal.h
  include/common/tmsg.h
  include/dnode/mnode/mnode.h
  include/libs/sync/sync.h
  source/common/src/msg/tmsg.c
  source/common/src/tglobal.c
  source/dnode/mgmt/mgmt_dnode/inc/dmInt.h
  source/dnode/mgmt/mgmt_dnode/src/dmHandle.c
  source/dnode/mgmt/mgmt_dnode/src/dmInt.c
  source/dnode/mgmt/mgmt_dnode/src/dmWorker.c
  source/dnode/mgmt/mgmt_mnode/src/mmHandle.c
  source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
  source/dnode/mgmt/node_mgmt/inc/dmMgmt.h
  source/dnode/mgmt/node_mgmt/inc/dmNodes.h
  source/dnode/mgmt/node_mgmt/src/dmEnv.c
  source/dnode/mgmt/node_mgmt/src/dmMonitor.c
  source/dnode/mgmt/node_util/inc/dmUtil.h
  source/dnode/mnode/impl/inc/mndInt.h
  source/dnode/mnode/impl/src/mndArbGroup.c
  source/dnode/mnode/impl/src/mndDnode.c
  source/dnode/mnode/impl/src/mndMain.c
  source/dnode/mnode/impl/src/mndSync.c
  source/dnode/vnode/inc/vnode.h
  source/dnode/vnode/src/vnd/vnodeSync.c
  source/libs/sync/inc/syncInt.h
  source/libs/sync/src/syncMain.c
Labels: team engine

#32856 Doc/main/status-interval
  docs/en/14-reference/01-components/01-taosd.md
  docs/zh/14-reference/01-components/01-taosd.md
  source/common/src/tglobal.c
Labels: team engine

#32917 fix: %%tbname placeholder in select list
  source/libs/scalar/src/scalar.c
Labels: team engine

#32918 Enh/add new windows ci 3.0
  test/ci/cases_win.task
  test/ci/run_win_cases.py
Labels: team platform

#32905 docs: update stream in advanced features section
  docs/en/06-advanced/03-stream.md
Labels: internal

#32925 Update documents for taosinstall, taosinspect
  docs/zh/08-operation/20-inspect-tools/03-taosinstall.md
  docs/zh/08-operation/20-inspect-tools/04-taosinspect.md
  docs/zh/08-operation/20-inspect-tools/06-taossubcribe.md
  docs/zh/08-operation/20-inspect-tools/index.md
Labels: internal

#32929 Remove alarm section title from basic inspection
  docs/zh/08-operation/20-inspect-tools/04-taosinspect.md
Labels: internal

#32923 fix: [TD-37878] Support using alias name in notify condition.
  source/libs/parser/src/parTranslater.c
Labels: team engine

#32934 refactor: expose ports in Dockerfile
  packaging/docker/Dockerfile
Labels: team platform

#32928 docs: update taosAdapter metrics
  docs/en/14-reference/01-components/03-taosadapter.md
  docs/zh/14-reference/01-components/03-taosadapter.md
Labels: team tools

#32978 fix(stmt):add check vtable in stmt translation
  source/client/src/clientStmt.c
  source/client/src/clientStmt2.c
  source/client/test/stmt2Test.cpp
Labels: team engine

#32981 fix(stmt):add check vtable in stmt translation
  source/client/src/clientStmt.c
  source/client/src/clientStmt2.c
Labels: team engine

#32983 Enh/td 37251 3.0 dropoutput
  include/common/streamMsg.h
  include/common/tmsgdef.h
  include/libs/executor/executor.h
  include/libs/new-stream/streamRunner.h
  source/common/src/msg/streamMsg.c
  source/dnode/mgmt/mgmt_snode/src/smHandle.c
  source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
  source/dnode/mgmt/node_mgmt/src/dmTransport.c
  source/dnode/snode/src/snode.c
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/dnode/vnode/src/vnd/vnodeSvr.c
  source/libs/executor/inc/executil.h
  source/libs/executor/src/dataInserter.c
  source/libs/executor/src/executor.c
  source/libs/new-stream/inc/streamTriggerTask.h
  source/libs/new-stream/src/streamRunner.c
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#32995 docs: update driver-go version
  docs/en/14-reference/05-connector/20-go.md
  docs/zh/14-reference/05-connector/20-go.mdx
Labels: team tools

#32992 test: cancel compalitbility_rolling_upgrade case on branch 3.0.
  test/ci/cases.task
Labels: team engine

#32987 fix: handle unformated wkt error
  source/libs/geometry/src/geomFunc.c
  tests/system-test/2-query/geometry.py
Labels: team engine

#32998 merge: from 3.3.6 to main
  source/common/src/tglobal.c
  source/dnode/mnode/impl/src/mndConfig.c
  source/dnode/mnode/impl/src/mndDnode.c
  source/libs/geometry/src/geomFunc.c
  test/cases/uncatalog/system-test/2-query/test_geometry.py
Labels: team engine

#33004 docs: Modify docs of virtual table and PERCENTILE.
  docs/en/14-reference/03-taos-sql/22-function.md
  docs/zh/14-reference/03-taos-sql/22-function.md
Labels: team engine

#33001 fix:stmt_get_fields get update sql timestamp precision
  source/client/test/stmtTest.cpp
  source/libs/parser/src/parInsertStmt.c
Labels: team engine

#32996 enh(stmt):insert ctb in other stb return error
  include/libs/qcom/query.h
  source/client/src/clientStmt2.c
  source/client/test/stmt2Test.cpp
  source/libs/parser/src/parInsertUtil.c
Labels: team engine

#32982 feat: TS-6663-add-mem-buffer-cache
  include/libs/monitor/monitor.h
  include/os/osSysinfo.h
  source/dnode/mgmt/node_util/src/dmUtil.c
  source/libs/monitor/src/monFramework.c
  source/os/src/osSysinfo.c
  source/os/test/osSystemTests.cpp
  source/os/test/osTests.cpp
Labels: team engine

#33020 docs: update tdgpt diagram
  docs/en/assets/tdgpt-01.png
Labels: internal

#33023 docs(datain): update kafka sasl/ssl auth config pictures
  docs/zh/06-advanced/05-data-in/kafka-04-sasl-gssapi.png
  docs/zh/06-advanced/05-data-in/kafka-04-sasl-plain.png
  docs/zh/06-advanced/05-data-in/kafka-04.png
  docs/zh/06-advanced/05-data-in/kafka-05.png
Labels: team tools

#33025 feat: add custom rule to enforce space after punctuation in emphasis
  docs/.markdownlint-cli2.jsonc
  docs/custom-rules/space-after-punctuation-in-emphasis.js
Labels: team platform

#33008 fix(query): clear refId before send drop-task msg.
  source/libs/qcom/src/queryUtil.c
  source/libs/scheduler/src/schRemote.c
Labels: team engine

#33009 fix(query): clear the refId before sending dropping task msg.
  source/libs/scheduler/src/schRemote.c
Labels: team engine

#33028 merge: from 3.3.6 to main
  source/libs/qcom/src/queryUtil.c
Labels: team engine

#33029 fix: refine python taos error log matching in checkAsan.sh
  test/ci/checkAsan.sh
Labels: team platform

#33003 feat: support extend option in state window
  docs/en/05-basic/03-query.md
  docs/en/06-advanced/03-stream.md
  docs/en/14-reference/03-taos-sql/20-select.md
  docs/en/14-reference/03-taos-sql/24-distinguished.md
  docs/en/14-reference/03-taos-sql/41-stream.md
  docs/en/14-reference/09-error-code.md
  docs/zh/05-basic/03-query.md
  docs/zh/06-advanced/03-stream.md
  docs/zh/14-reference/03-taos-sql/20-select.md
  docs/zh/14-reference/03-taos-sql/24-distinguished.md
  docs/zh/14-reference/03-taos-sql/41-stream.md
  docs/zh/14-reference/09-error-code.md
  include/common/streamMsg.h
  include/libs/nodes/plannodes.h
  include/libs/nodes/querynodes.h
  include/util/taoserror.h
  source/common/src/msg/streamMsg.c
  source/dnode/mnode/impl/src/mndStreamUtil.c
  source/libs/command/src/explain.c
  source/libs/executor/inc/executorInt.h
  source/libs/executor/inc/operator.h
  source/libs/executor/src/anomalywindowoperator.c
  source/libs/executor/src/eventwindowoperator.c
  source/libs/executor/src/operator.c
  source/libs/executor/src/timewindowoperator.c
  source/libs/executor/test/queryPlanTests.cpp
  source/libs/new-stream/inc/streamTriggerTask.h
  source/libs/new-stream/src/streamTriggerTask.c
  source/libs/nodes/src/nodesCloneFuncs.c
  source/libs/nodes/src/nodesCodeFuncs.c
  source/libs/nodes/src/nodesMsgFuncs.c
  source/libs/nodes/src/nodesTraverseFuncs.c
  source/libs/nodes/src/nodesUtilFuncs.c
  source/libs/parser/inc/parAst.h
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parAstCreater.c
  source/libs/parser/src/parTranslater.c
  source/libs/parser/src/parUtil.c
  source/libs/parser/test/parStreamTest.cpp
  source/libs/planner/src/planLogicCreater.c
  source/libs/planner/src/planPhysiCreater.c
  source/util/src/terror.c
  test/cases/05-VirtualTables/ans/test_vctable_select_test_partition.ans
  test/cases/05-VirtualTables/ans/test_vctable_select_test_state.ans
  test/cases/05-VirtualTables/ans/test_vstable_select_test_partition.ans
  test/cases/05-VirtualTables/ans/test_vstable_select_test_state.ans
  test/cases/05-VirtualTables/ans/test_vtable_select_test_partition.ans
  test/cases/05-VirtualTables/ans/test_vtable_select_test_state.ans
  test/cases/05-VirtualTables/in/test_vstable_select_test_partition.in
  test/cases/uncatalog/system-test/2-query/test_state_window_extend.py
  test/ci/cases.task
  test/temp_explain_tsorder.result
Labels: team engine

#32726 fix(tmq): set pointer = NULL to avoid double free
  source/dnode/mnode/impl/src/mndDef.c
  source/dnode/mnode/impl/src/mndSubscribe.c
Labels: team engine

#33026 fix: test bug
  source/dnode/mnode/impl/src/mndScan.c
  test/ci/cases.task
Labels: team engine

#33048 fix: TS-7385-report-statusinterval-main
  source/dnode/mgmt/mgmt_dnode/src/dmHandle.c
Labels: team engine

#33053 docs(explorer): add env set instructions for explorer
  docs/en/14-reference/01-components/07-explorer.md
  docs/zh/14-reference/01-components/07-explorer.md
Labels: team tools

#33054 fix(ci): smaBasic performance check affectd by debug level log
  test/cases/uncatalog/system-test/2-query/test_smaBasic.py
Labels: team engine

#32926 Enh/supportTLS
  include/common/tglobal.h
  include/libs/transport/trpc.h
  source/client/src/clientEnv.c
  source/client/src/clientImpl.c
  source/common/CMakeLists.txt
  source/common/src/tglobal.c
  source/dnode/mgmt/node_mgmt/src/dmTransport.c
  source/libs/function/src/udfd.c
  source/libs/tmqtt/mqtt/src/tmqttDaemon.c
  source/libs/transport/CMakeLists.txt
  source/libs/transport/inc/transComm.h
  source/libs/transport/inc/transTLS.h
  source/libs/transport/inc/transportInt.h
  source/libs/transport/src/thttp.c
  source/libs/transport/src/trans.c
  source/libs/transport/src/transCli.c
  source/libs/transport/src/transComm.c
  source/libs/transport/src/transSvr.c
  source/libs/transport/src/transTLS.c
  tools/shell/src/shellNettest.c
Labels: team engine

#33030 enh: TS-6480-auto-weight-balance-leader
  include/common/tmsg.h
  include/common/tmsgdef.h
  include/libs/sync/sync.h
  source/common/src/msg/tmsg.c
  source/dnode/mgmt/mgmt_mnode/src/mmHandle.c
  source/dnode/mgmt/mgmt_vnode/inc/vmInt.h
  source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
  source/dnode/mgmt/mgmt_vnode/src/vmWorker.c
  source/dnode/mnode/impl/src/mndVgroup.c
  source/dnode/vnode/src/inc/vnd.h
  source/dnode/vnode/src/vnd/vnodeSync.c
  source/libs/sync/src/syncMain.c
  test/cases/uncatalog/system-test/0-others/test_kill_balance_leader.py
  test/ci/cases.task
Labels: team engine

#33068 feat: enhance workflow dispatch inputs and concurrency handling in new-framework-test
  .github/workflows/new-framework-test.yml
Labels: team platform

#33069 Add installation of prophet library in install.sh
  packaging/docker/DockerfileTDgpt.base
  tools/tdgpt/script/install.sh
Labels: team platform

#33055 fix[TD-37678]: taos command line support '-uroot' on windows
  tools/shell/src/shellArguments.c
Labels: team engine

#33067 Feat/ts 6480 auto balance add case
  source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
  test/cases/02-Databases/05-Sync/test_balance_leader.py
  test/ci/cases.task
Labels: team engine

#33075 docs: update driver-go version history to include v3.7.6 changes
  docs/en/14-reference/05-connector/20-go.md
  docs/zh/14-reference/05-connector/20-go.mdx
Labels: team tools

#33074 fix(stmt): table not exist error return
  source/libs/parser/src/parInsertUtil.c
Labels: team engine

#33073 fix[TD-37673]: rand returns different value with same seed on windows
  source/os/src/osRand.c
Labels: team engine

#33077 docs: upgrade the Node.js connector version
  docs/en/14-reference/05-connector/35-node.md
  docs/examples/node/package.json
  docs/zh/14-reference/05-connector/35-node.mdx
Labels: team tools

#33080 fix: stream ci issues
  include/libs/new-stream/streamReader.h
  source/common/src/tdatablock.c
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/executor/src/executil.c
  source/libs/new-stream/src/streamReader.c
  source/libs/new-stream/src/streamTriggerMerger.c
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#33070 fix[TD-38138]: build and execute issues on windows
  cmake/define.cmake
  source/os/CMakeLists.txt
Labels: team engine

#33084 merge: from main to 3.0 branch
  cmake/define.cmake
  docs/en/14-reference/05-connector/35-node.md
  docs/examples/node/package.json
  docs/zh/14-reference/03-taos-sql/41-stream.md
  docs/zh/14-reference/05-connector/35-node.mdx
  source/os/CMakeLists.txt
  source/os/src/osRand.c
Labels: team engine

#33079 case: fix bug to repair case on main branch
  test/cases/41-StreamProcessing/20-UseCase/idmp_meters_bug1.py
  test/cases/41-StreamProcessing/20-UseCase/idmp_meters_bug14.py
  test/cases/41-StreamProcessing/20-UseCase/idmp_meters_bug3.py
  test/cases/41-StreamProcessing/20-UseCase/test_idmp_meters.py
Labels: team tools

#33059 open tls on enterprice
  source/libs/transport/CMakeLists.txt
  source/libs/transport/inc/transTLS.h
  source/libs/transport/src/transTLS.c
Labels: team engine

#33062 feat(query): add corr function.
  docs/zh/14-reference/03-taos-sql/22-function.md
  include/libs/function/functionMgt.h
  source/libs/function/inc/builtins.h
  source/libs/function/inc/builtinsimpl.h
  source/libs/function/inc/functionResInfoInt.h
  source/libs/function/src/builtins.c
  source/libs/function/src/builtinsimpl.c
  source/libs/function/src/detail/tavgfunction.c
  source/libs/function/src/functionMgt.c
  source/libs/scalar/src/sclfunc.c
  test/cases/10-DataIngestion/test_write_update.py
  test/cases/44-TDgpt/test_tdgpt.py
  test/ci/tdgpt_cases.task
Labels: team engine

#33095 fix: move tsdb retention monitor to community
  source/dnode/mnode/impl/src/mndRetention.c
  source/dnode/vnode/CMakeLists.txt
  source/dnode/vnode/src/tsdb/tsdbOpen.c
  source/dnode/vnode/src/tsdb/tsdbRetention.c
  source/dnode/vnode/src/tsdb/tsdbRetentionMonitor.c
  source/dnode/vnode/src/vnd/vnodeSvr.c
  source/libs/parser/src/parTranslater.c
Labels: team engine

#33061 feat: add status check on compatibility cases.
  tests/system-test/0-others/compatibility_basic.py
Labels: team engine

#33102 merge: from 3.0 to main branch
  include/libs/function/functionMgt.h
  include/libs/new-stream/stream.h
  include/libs/scalar/scalar.h
  source/dnode/mgmt/mgmt_snode/src/smWorker.c
  source/libs/executor/src/anomalywindowoperator.c
  source/libs/executor/src/executorInt.c
  source/libs/function/inc/functionMgtInt.h
  source/libs/function/src/builtins.c
  source/libs/function/src/functionMgt.c
  source/libs/new-stream/inc/streamTriggerTask.h
  source/libs/new-stream/src/streamTriggerTask.c
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parTokenizer.c
  source/libs/parser/src/parTranslater.c
  source/libs/planner/src/planLogicCreater.c
  source/libs/scalar/src/sclfunc.c
  test/cases/41-StreamProcessing/04-Options/test_abnormal_data_table.py
  test/cases/41-StreamProcessing/04-Options/test_abnormal_data_vtable.py
  tools/tdgpt/taosanalytics/algo/anomaly.py
  tools/tdgpt/taosanalytics/app.py
  tools/tdgpt/taosanalytics/test/unit_test.py
  tools/tdgpt/taosanalytics/util.py
Labels: team engine

#33103 fix(query): don't free rowkey when suspending tsdb reader.
  source/dnode/vnode/src/tsdb/tsdbRead2.c
  source/dnode/vnode/src/tsdb/tsdbReadUtil.c
  source/dnode/vnode/src/tsdb/tsdbReadUtil.h
  test/cases/06-DataIngestion/04-Update/test_insert_update2.py
Labels: team engine

#33115 merge: from 3.3.6 to main
  test/new_test_framework/utils/compatibilityUtil.py
Labels: team engine

#33116 fix(stream): fix sliding trigger for ignore disorder option
  source/libs/new-stream/src/streamTriggerMerger.c
  source/libs/new-stream/src/streamTriggerTask.c
  test/ci/cases.task
Labels: team engine

#33088 feat(query): add high priority queries process queue in mnode to avoid normal queries blocking critical processing.
  include/dnode/mnode/mnode.h
  include/libs/nodes/plannodes.h
  include/libs/planner/planner.h
  include/libs/qcom/query.h
  include/libs/qworker/qworker.h
  source/dnode/mgmt/mgmt_mnode/inc/mmInt.h
  source/dnode/mgmt/mgmt_mnode/src/mmWorker.c
  source/dnode/mgmt/mgmt_vnode/inc/vmInt.h
  source/dnode/mgmt/mgmt_vnode/src/vmWorker.c
  source/dnode/mnode/impl/src/mndQuery.c
  source/dnode/qnode/src/qnode.c
  source/dnode/vnode/src/vnd/vnodeSvr.c
  source/libs/planner/inc/planInt.h
  source/libs/planner/src/planLogicCreater.c
  source/libs/planner/src/planPhysiCreater.c
  source/libs/planner/src/planScaleOut.c
  source/libs/qworker/src/qwMsg.c
  source/libs/qworker/src/qworker.c
  source/libs/scheduler/inc/schInt.h
  source/libs/scheduler/src/schJob.c
  source/libs/scheduler/src/schRemote.c
  source/libs/scheduler/src/schTask.c
  source/libs/scheduler/src/schUtil.c
  source/libs/scheduler/test/schedulerTests.cpp
  source/util/src/terror.c
Labels: team engine

#33138 merge: from 3.0 to main branch
  include/dnode/mnode/mnode.h
  include/libs/nodes/plannodes.h
  include/libs/planner/planner.h
  include/libs/qcom/query.h
  include/libs/qworker/qworker.h
  source/dnode/mgmt/mgmt_mnode/inc/mmInt.h
  source/dnode/mgmt/mgmt_mnode/src/mmWorker.c
  source/dnode/mgmt/mgmt_vnode/inc/vmInt.h
  source/dnode/mgmt/mgmt_vnode/src/vmWorker.c
  source/dnode/mnode/impl/src/mndQuery.c
  source/dnode/qnode/src/qnode.c
  source/dnode/vnode/src/tsdb/tsdbCacheRead.c
  source/dnode/vnode/src/vnd/vnodeSvr.c
  source/libs/new-stream/src/streamTriggerMerger.c
  source/libs/new-stream/src/streamTriggerTask.c
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parTranslater.c
  source/libs/parser/test/parStreamTest.cpp
  source/libs/planner/inc/planInt.h
  source/libs/planner/src/planLogicCreater.c
  source/libs/planner/src/planPhysiCreater.c
  source/libs/planner/src/planScaleOut.c
  source/libs/planner/src/planSpliter.c
  source/libs/qworker/src/qwMsg.c
  source/libs/qworker/src/qworker.c
  source/libs/scheduler/inc/schInt.h
  source/libs/scheduler/src/schJob.c
  source/libs/scheduler/src/schRemote.c
  source/libs/scheduler/src/schTask.c
  source/libs/scheduler/src/schUtil.c
  source/libs/scheduler/test/schedulerTests.cpp
  source/util/src/terror.c
  test/cases/41-StreamProcessing/02-Stream/stream_partitionby.py
  test/ci/cases.task
  test/temp_test_vctable_select_test_function.result
  test/temp_test_vstable_select_test_function.result
  test/temp_test_vtable_select_test_function.result
Labels: team engine

#33131 fix: [TD-38020] fix mem leak.
  source/dnode/mgmt/node_mgmt/src/dmTransport.c
  source/libs/executor/src/dataInserter.c
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#33093 fix possible mem leak while driver quit
  source/libs/transport/src/transCli.c
  source/libs/transport/src/transComm.c
Labels: team engine

#32458 add stmt2 blob c test
  include/common/tdataformat.h
  source/common/src/msg/tmsg.c
  source/common/src/tdatablock.c
  source/common/src/tdataformat.c
  source/dnode/vnode/src/bse/bseInc.h
  source/dnode/vnode/src/bse/bseMgt.c
  source/dnode/vnode/src/bse/bseSnapshot.c
  source/dnode/vnode/src/bse/bseTable.c
  source/dnode/vnode/src/bse/bseTable.h
  source/dnode/vnode/src/bse/bseTableMgt.c
  source/dnode/vnode/src/bse/bseTableMgt.h
  source/dnode/vnode/src/bse/bseUtil.c
  source/dnode/vnode/src/bse/bseUtil.h
  source/dnode/vnode/test/bseTest.cpp
  source/libs/parser/src/parInsertUtil.c
  test/cases/01-DataTypes/test_datatype_blob.py
  test/cases/01-DataTypes/test_datatype_varbinary.py
  test/cases/06-DataIngestion/01-Insert/test_insert_blob.py
  tests/coverage/covtests.task
  utils/test/c/CMakeLists.txt
  utils/test/c/blob_test.c
  utils/test/c/tmq_blob.c
  utils/test/c/tmq_write_raw_with_blob_test.c
Labels: team engine

#33133 fix: [TD-38518] Fix wrong timeLineResMode of virtual super table.
  source/libs/parser/src/parTranslater.c
Labels: team engine

#33089 fix: update Windows test workflow to use specific branch for error handling
  .github/workflows/new-framework-test.yml
  .github/workflows/tdengine-test.yml
Labels: team platform

#32734 feat(scan): add directory scanning option and support for concurrent file processing
  test/ci/filter_for_return_values
  test/ci/scan_file_path.py
Labels: team platform

#33127 feat: add taosgen binary to installation and removal scripts
  packaging/deb/DEBIAN/prerm
  packaging/deb/makedeb.sh
  packaging/rpm/tdengine.spec
  packaging/tools/install.sh
  packaging/tools/install_client.sh
  packaging/tools/post.sh
  packaging/tools/preun.sh
  packaging/tools/remove.sh
  packaging/tools/remove_client.sh
Labels: team platform

#33135 fix conn info error
  source/dnode/mnode/impl/src/mndProfile.c
Labels: team engine

#33126 docs: taosgen supports data cache generation
  docs/doxgen/taosgen_config.md
  docs/en/14-reference/02-tools/11-taosgen.md
  docs/zh/14-reference/02-tools/11-taosgen.md
Labels: team tools

#33065 feat: add status check on compatibility cases.
  test/cases/41-StreamProcessing/23-Compatibility/test_compatibility_backward_forward.py
  test/new_test_framework/utils/compatibilityUtil.py
Labels: team engine

#33155 docs: update release note for 3.3.8.0 in office web
  docs/en/28-releases/03-notes/3.3.8.0.md
  docs/zh/28-releases/03-notes/3.3.8.0.md
Labels: team platform

#33159 Fix/TS-6789-336
  source/dnode/mnode/impl/src/mndProfile.c
Labels: team engine

#33162 docs: update pkg to 3.3.8.0 and use pkgType to get version url
  docs/zh/08-operation/03-install.md
Labels: team platform

#33151 fix: last error
  source/libs/executor/src/scanoperator.c
  test/cases/22-Functions/02-Aggregate/test_agg_last.py
  test/cases/41-StreamProcessing/03-TriggerMode/ans/test_stream_sliding_trigger.0-0-0-1-1.csv
  test/cases/41-StreamProcessing/03-TriggerMode/test_sliding.py
  test/ci/cases.task
Labels: team engine

#33132 fix: [TD-38160] Disable delete_recalc when trigger window is count wi…
  source/libs/parser/src/parTranslater.c
  test/cases/41-StreamProcessing/03-TriggerMode/count_new_dbg.py
  test/cases/41-StreamProcessing/03-TriggerMode/period.py
  test/cases/41-StreamProcessing/03-TriggerMode/test_count_new.py
  test/cases/41-StreamProcessing/03-TriggerMode/test_sliding.py
  test/cases/41-StreamProcessing/08-Recalc/test_recalc_combined_options.py
  test/cases/41-StreamProcessing/08-Recalc/test_recalc_delete_recalc.py
  test/cases/41-StreamProcessing/20-UseCase/idmp_meters_bug13.py
  test/cases/41-StreamProcessing/20-UseCase/idmp_meters_bug17.py
  test/cases/41-StreamProcessing/20-UseCase/idmp_meters_bug18.py
  test/cases/41-StreamProcessing/20-UseCase/idmp_meters_bug19.py
  test/cases/41-StreamProcessing/20-UseCase/test_idmp_meters.py
  test/cases/41-StreamProcessing/30-OldPyCases/test_oldcase_at_once.py
Labels: team engine

#33167 Docs/ipv6Update
  docs/en/08-operation/13-ipv6.md
  docs/zh/04-get-started/_01-install.md
  docs/zh/08-operation/13-ipv6.md
  docs/zh/14-reference/07-supported.md
Labels: team engine
