Repository taosdata/TDengine, pull requests merged in 2025-07, with the labels that each got.

#31559 feat(stream): fix thread run out for runner
  include/dnode/snode/snode.h
  include/libs/new-stream/stream.h
  source/dnode/mgmt/mgmt_snode/src/smWorker.c
  source/dnode/snode/src/snode.c
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/new-stream/src/streamRunner.c
Labels: team engine

#31563 feat: [TS-6100] Extract fill range from RANGE()
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31517 feat(stmt2):interlace support bind same table repeatedly
  include/libs/qcom/query.h
  source/client/src/clientMain.c
  source/client/src/clientStmt.c
  source/client/src/clientStmt2.c
  source/client/test/stmt2Test.cpp
  source/libs/parser/src/parInsertUtil.c
Labels: team engine

#31546 docs: Node-RED plugin required version change to latest version
  docs/en/10-third-party/09-iot/01-Node-RED.md
  docs/zh/10-third-party/09-iot/01-Node-RED.md
Labels: team tools

#31564 fix: fill
  source/libs/executor/src/filloperator.c
  source/libs/scalar/src/scalar.c
Labels: team engine

#31566 feat:stmt2 interlace mode merge same table data
  include/libs/qcom/query.h
  source/client/src/clientMain.c
  source/client/src/clientStmt.c
  source/client/src/clientStmt2.c
  source/client/test/stmt2Test.cpp
  source/libs/parser/src/parInsertUtil.c
Labels: team engine

#31573 add debug info
  source/libs/transport/src/transComm.c
Labels: team engine

#31574 CollectD website url is not correct
  docs/en/10-third-party/01-collection/05-collectd.md
  docs/zh/10-third-party/01-collection/05-collectd.md
Labels: team tools

#31567 fix: update config error while start dnode.
  source/dnode/mnode/impl/inc/mndConfig.h
  source/dnode/mnode/impl/src/mndConfig.c
  source/util/src/tconfig.c
  source/util/test/cfgTest.cpp
Labels: team engine

#31576 fix: [TD-35945] fix memory leak of logic node's vgroup info
  source/libs/planner/src/planScaleOut.c
Labels: team engine

#31580 test: update ci
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
Labels: team engine

#31577 fix(tdgpt): update container build scripts and test cases for configuration
  .github/workflows/tdgpt-test.yml
  .gitignore
  test/ci/container_build.sh
  tests/parallel_test/container_build.sh
  tests/parallel_test/tdgpt_cases.task
Labels: team platform

#31560 feat(taosd): enhance ASan support in start command for better error tracking
  test/ci/pytest.sh
  test/new_test_framework/taostest/components/taosd.py
Labels: team platform

#31575 fix taos log miss
  test/conftest.py
  test/new_test_framework/utils/before_test.py
Labels: team platform

#31082 refactor: add ci dockerfile
  test/ci/container_build.sh
  test/ci/pytest.sh
  tests/ci/dockerfile_ci
  tests/ci/setup.sh
  tests/parallel_test/container_build.sh
  tests/parallel_test/container_build_coverage.sh
  tests/parallel_test/run_check_assert_container.sh
  tests/parallel_test/run_check_void_container.sh
  tests/parallel_test/run_container.sh
  tests/parallel_test/run_coverage_container.sh
  tests/parallel_test/run_scan_container.sh
Labels: team platform

#31579 fix: memory issues
  source/common/src/msg/tmsg.c
  source/dnode/mgmt/mgmt_snode/src/smWorker.c
  source/dnode/mnode/impl/src/mndStreamMgmt.c
  source/libs/executor/src/dataInserter.c
  source/libs/executor/src/dataSinkMgt.c
  source/libs/executor/src/executil.c
  source/libs/new-stream/src/streamReader.c
  source/libs/new-stream/src/streamRunner.c
  source/libs/new-stream/src/streamTriggerTask.c
  source/libs/nodes/src/nodesUtilFuncs.c
  source/libs/parser/src/parTranslater.c
  test/cases/13-StreamProcessing/03-TriggerMode/test_sliding.py
  test/conftest.py
  test/new_test_framework/utils/before_test.py
Labels: team engine

#31585 fix: get vginfo
  source/dnode/vnode/src/meta/metaEntry2.c
  source/libs/executor/src/dataInserter.c
Labels: team engine

#31583 fix: remove duplicate feature entry for MQTT support in release notes
  docs/en/28-releases/03-notes/3.3.6.13.md
  docs/zh/28-releases/03-notes/3.3.6.13.md
Labels: team platform

#31588 fix: crash and memory issues
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/executor/inc/executil.h
  source/libs/executor/src/dataInserter.c
  source/libs/new-stream/src/streamReader.c
Labels: team engine

#31582 mnd/bnode: release dnode to fix memleak with bnode dropping
  source/dnode/mnode/impl/src/mndBnode.c
  source/dnode/mnode/impl/src/mndDnode.c
Labels: team engine

#31591 fix: remove unused configs
  include/common/tglobal.h
  source/common/src/tglobal.c
Labels: team engine

#31598 docs: new stream
  docs/zh/06-advanced/03-stream.md
  docs/zh/14-reference/03-taos-sql/14-stream.md
Labels: team engine

#31599 fix: runner cancel calc
  include/util/tlockfree.h
  source/libs/new-stream/src/streamRunner.c
  source/util/src/tlockfree.c
Labels: team engine

#31601 feat: [TS-6100] Transport limit from projection to external window
  source/libs/planner/src/planLogicCreater.c
Labels: team engine

#31604 feat: [TS-6100] Refact streamScanSplit logic
  source/libs/planner/src/planSpliter.c
Labels: team engine

#31590 fix: enable DBUILD_TEST in Asan Docker build
  test/ci/container_build.sh
  tests/ci/dockerfile_ci
  tests/parallel_test/container_build.sh
Labels: team platform

#31610 fix: add missing log file copy for JDBC example
  test/ci/run_case.sh
Labels: team platform

#31613 fix(stream): fix table meta of virtual tables
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31620 docs: new stream
  docs/zh/06-advanced/03-stream.md
  docs/zh/14-reference/03-taos-sql/14-stream.md
Labels: team engine

#31593 fix/TS-6785-fix-return-code
  source/dnode/vnode/src/vnd/vnodeOpen.c
  source/util/src/terror.c
Labels: team engine

#31625 feat(stream): fix sarray init error in vTableInfo & optimize getting …
  include/common/streamMsg.h
  include/libs/executor/executor.h
  include/libs/new-stream/streamReader.h
  source/common/src/msg/streamMsg.c
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/executor/src/executor.c
  source/libs/new-stream/src/streamReader.c
Labels: team engine

#31627 fix: mem leak
  include/common/tmsg.h
  source/common/src/msg/tmsg.c
  source/dnode/vnode/src/vnd/vnodeSvr.c
  source/libs/executor/src/dataInserter.c
Labels: team engine

#31380 enh: grant support vnodes and storage size
  include/common/tgrant.h
  source/common/src/tglobal.c
  source/common/src/tgrant.c
  source/dnode/mgmt/mgmt_vnode/src/vmWorker.c
  source/dnode/mnode/impl/src/mndDb.c
  source/dnode/mnode/impl/src/mndMain.c
  source/dnode/vnode/inc/vnode.h
  source/dnode/vnode/src/vnd/vnodeQuery.c
  tests/system-test/0-others/grant.py
  tests/system-test/0-others/information_schema.py
Labels: team engine

#31629 docs: update stream documentation for clarity and structure
  docs/.markdownlint-cli2.jsonc
  docs/zh/14-reference/03-taos-sql/14-stream.md
Labels: team platform

#31639 fix: incorrect stream name in the notification
  include/libs/new-stream/stream.h
  source/libs/new-stream/inc/streamInt.h
  source/libs/new-stream/inc/streamTriggerTask.h
  source/libs/new-stream/src/streamRunner.c
  source/libs/new-stream/src/streamTriggerTask.c
  source/libs/new-stream/src/streamUtil.c
Labels: team engine

#31640 fix: memory issues
  source/common/src/ttime.c
  source/dnode/mgmt/mgmt_snode/src/smWorker.c
  source/dnode/mnode/impl/inc/mndStream.h
  source/dnode/mnode/impl/src/mndStreamMgmt.c
  source/dnode/mnode/impl/src/mndStreamUtil.c
  source/libs/new-stream/inc/streamInt.h
  source/libs/new-stream/src/streamMgmt.c
  source/libs/new-stream/src/streamRunner.c
  source/libs/new-stream/src/streamTriggerTask.c
  source/libs/new-stream/src/streamUtil.c
  source/libs/parser/src/parTranslater.c
  source/util/src/tutil.c
Labels: team engine

#31643 fx: invalid vgroup
  source/libs/executor/src/dataInserter.c
Labels: team engine

#31647 fix: memory issues
  include/common/streamMsg.h
  source/common/src/msg/streamMsg.c
  source/dnode/mnode/impl/src/mndStreamMgmt.c
  source/dnode/mnode/impl/src/mndStreamUtil.c
  source/libs/executor/src/externalwindowoperator.c
Labels: team engine

#31646 fix invalid epset2
  source/client/src/clientHb.c
Labels: team engine

#31617 Feat/ts 6100 smj tsma
  include/common/streamMsg.h
  include/common/tcommon.h
  include/common/tmsg.h
  include/common/tmsgdef.h
  include/libs/nodes/cmdnodes.h
  include/libs/nodes/querynodes.h
  source/common/src/msg/streamMsg.c
  source/common/src/msg/tmsg.c
  source/common/src/tglobal.c
  source/dnode/mgmt/mgmt_mnode/src/mmHandle.c
  source/dnode/mgmt/mgmt_snode/src/smHandle.c
  source/dnode/mgmt/mgmt_snode/src/smWorker.c
  source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
  source/dnode/mnode/impl/inc/mndSma.h
  source/dnode/mnode/impl/inc/mndStream.h
  source/dnode/mnode/impl/src/mndDb.c
  source/dnode/mnode/impl/src/mndSma.c
  source/dnode/mnode/impl/src/mndStb.c
  source/dnode/mnode/impl/src/mndStreamMgmt.c
  source/dnode/mnode/impl/test/sma/sma.cpp
  source/dnode/vnode/inc/vnode.h
  source/dnode/vnode/src/vnd/vnodeSvr.c
  source/libs/catalog/inc/catalogInt.h
  source/libs/catalog/src/ctgAsync.c
  source/libs/catalog/src/ctgRemote.c
  source/libs/catalog/src/ctgUtil.c
  source/libs/executor/src/aggregateoperator.c
  source/libs/new-stream/src/streamTriggerTask.c
  source/libs/nodes/src/nodesCloneFuncs.c
  source/libs/nodes/src/nodesUtilFuncs.c
  source/libs/parser/inc/parInt.h
  source/libs/parser/src/parAstParser.c
  source/libs/parser/src/parTranslater.c
  source/libs/parser/src/parser.c
  source/libs/parser/test/parInitialCTest.cpp
  source/libs/planner/src/planSpliter.c
  source/libs/planner/test/planTestUtil.cpp
  source/libs/qcom/src/querymsg.c
  test/cases/26-TSMAs/test_tsma.py
  tests/system-test/2-query/tsma.py
Labels: team engine

#31648 feat: [TS-6100] Do not eliminate projection
  source/libs/planner/src/planLogicCreater.c
Labels: team engine

#31535 fix: virtual table disable write
  source/libs/parser/src/parInsertSql.c
  test/cases/05-VirtualTables/test_vtable_insert.py
  test/ci/cases.task
Labels: team engine

#31633 docs: update collectd configuration instructions
  docs/en/assets/resources/_collectd.mdx
  docs/zh/14-reference/01-components/_collectd.mdx
Labels: team tools

#31623 use no-default-index
  source/dnode/vnode/src/meta/metaQuery.c
Labels: team engine

#31539 fix(doc) select statement add field explanation
  docs/en/14-reference/03-taos-sql/07-select.md
  docs/zh/14-reference/03-taos-sql/07-select.md
Labels: team engine

#31651 feat: [TS-6100] Do not generate external window when query has limit.
  source/libs/executor/src/virtualtablescanoperator.c
  source/libs/planner/src/planLogicCreater.c
Labels: team engine

#31654 fix: notify eventtype
  source/libs/new-stream/src/streamUtil.c
Labels: team engine

#31655 Feat/ts 6100 3.0 mm
  include/libs/new-stream/stream.h
  include/libs/new-stream/streamReader.h
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/executor/src/externalwindowoperator.c
  source/libs/executor/src/tsort.c
  source/libs/executor/src/virtualtablescanoperator.c
  source/libs/new-stream/src/streamReader.c
Labels: team engine

#31660 feat: [TS-6100] Add trigger TS slot id when using %%trows
  include/common/streamMsg.h
  source/common/src/msg/streamMsg.c
  source/dnode/mnode/impl/src/mndStreamMgmt.c
  source/dnode/mnode/impl/src/mndStreamUtil.c
  source/libs/new-stream/src/streamTriggerTask.c
  source/libs/parser/src/parTranslater.c
  source/libs/parser/test/parStreamTest.cpp
Labels: team engine

#31659 test: add cases
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_limit.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
  test/ci/streamlist_for_ci.task
Labels: team engine

#31662 feat: [TS-6100] Push down time range expr to virtual table's ref tabl…
  source/libs/planner/src/planLogicCreater.c
Labels: team engine

#31609 Docs: official document for Ontop product
  docs/en/10-third-party/05-bi/17-Ontop.md
  docs/en/10-third-party/05-bi/img/ontop-query.webp
  docs/zh/10-third-party/05-bi/17-Ontop.md
  docs/zh/10-third-party/05-bi/img/ontop-query.webp
  docs/zh/14-reference/02-tools/08-taos-cli.md
Labels: team tools

#31663 fix(stream): tsIndex error in trigger & runner thread wait because wa…
  source/client/src/clientTmq.c
  source/libs/executor/src/dataInserter.c
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31664 test: add cases
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding_bug6.py
Labels: team engine

#31665 fix(stream): double free of notify content and timestamp not the firs…
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/new-stream/src/streamRunner.c
Labels: team engine

#31668 feat: [TS-6100] Fix wrong timerange when using join.
  source/libs/parser/src/parTranslater.c
  source/libs/planner/src/planOptimizer.c
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding_bug7.py
Labels: team engine

#31670 feat: [TS-6100] Fix external window judge condition.
  source/libs/planner/src/planLogicCreater.c
Labels: team engine

#31669 test: add cases
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding_bug5.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding_bug7.py
Labels: team engine

#31602 fix: audit case fail
  tests/system-test/0-others/taosd_audit.py
Labels: team engine

#31671 fix: memory issues
  include/libs/new-stream/stream.h
  source/common/src/msg/streamMsg.c
  source/dnode/mnode/impl/inc/mndStream.h
  source/dnode/mnode/impl/src/mndSnode.c
  source/dnode/mnode/impl/src/mndStream.c
  source/dnode/mnode/impl/src/mndStreamMgmt.c
  source/dnode/mnode/impl/src/mndStreamUtil.c
  source/libs/executor/src/externalwindowoperator.c
  source/libs/new-stream/src/streamCheckpoint.c
  source/libs/new-stream/src/streamTriggerTask.c
  test/ci/streamlist_for_ci.task
Labels: team engine

#31676 fix(stream): fix recalc check in stream trigger task
  source/libs/new-stream/inc/streamTriggerTask.h
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31690 fix(stream): checkpoint error & tsIndex error in event window
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/new-stream/src/streamCheckpoint.c
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31684 docs: update rust connector doc
  docs/en/14-reference/05-connector/10-cpp.md
  docs/en/14-reference/05-connector/26-rust.md
  docs/en/14-reference/05-connector/30-python.md
  docs/zh/14-reference/05-connector/10-cpp.mdx
  docs/zh/14-reference/05-connector/26-rust.mdx
  docs/zh/14-reference/05-connector/30-python.mdx
Labels: team tools

#31695 feat: [TS-6100] Fix no mgmt epset.
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31612 fix(query): order by used the qsort function heap buffer over flow
  include/util/tcompare.h
  source/util/src/talgo.c
  source/util/src/tcompare.c
  test/cases/07-DataQuerying/04-OrderBy/test_sort_double_col.py
  test/ci/cases.task
Labels: team engine

#31638 fix(query): fix bug caused by shallow copy.
  source/dnode/vnode/src/tsdb/tsdbRead2.c
  test/cases/01-DataTypes/test_composite_key_load.py
  test/ci/cases.task
Labels: team engine

#31700 fix: memory issues
  include/libs/new-stream/streamReader.h
  source/dnode/mgmt/mgmt_mnode/src/mmHandle.c
  source/dnode/mgmt/mgmt_mnode/src/mmWorker.c
  source/dnode/mnode/impl/src/mndStreamUtil.c
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/new-stream/src/streamReader.c
Labels: team engine

#31701 fix(stream): fix hist calc of stream trigger task
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/new-stream/inc/streamInt.h
  source/libs/new-stream/inc/streamTriggerMerger.h
  source/libs/new-stream/inc/streamTriggerTask.h
  source/libs/new-stream/src/streamReader.c
  source/libs/new-stream/src/streamTriggerMerger.c
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31694 fix:(stmt2) alter table schema bind
  source/client/test/stmt2Test.cpp
  source/common/src/tdataformat.c
Labels: team engine

#31693 fix: fill math operator resType precision in translation
  source/libs/scalar/src/scalar.c
  tests/system-test/2-query/func_to_char_timestamp.py
Labels: team engine

#31705 fix: writev on windows
  include/os/osFile.h
  source/libs/new-stream/src/dataSinkFile.c
  source/os/src/osFile.c
Labels: team engine

#31709 Feat/ts 6100 smj
  include/common/streamMsg.h
  include/libs/nodes/cmdnodes.h
  source/common/src/msg/streamMsg.c
  source/libs/parser/inc/parAst.h
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parAstCreater.c
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31710 feat:insert into subquery (#31401)
  docs/en/14-reference/03-taos-sql/06-insert.md
  docs/zh/14-reference/03-taos-sql/06-insert.md
  include/libs/executor/storageapi.h
  source/dnode/vnode/inc/vnode.h
  source/dnode/vnode/src/inc/tsdb.h
  source/dnode/vnode/src/tsdb/tsdbRead2.c
  source/dnode/vnode/src/vnd/vnodeQuery.c
  source/libs/executor/src/dataInserter.c
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parTranslater.c
  test/cases/06-DataIngestion/05-Others/test_insert_select.py
Labels: team engine

#31712 merge: from main to 3.0 branch
  .github/workflows/tdengine-build.yml
  .github/workflows/tdengine-docs-ci.yml
  .github/workflows/tdengine-release-build.yml
  .github/workflows/tdengine-test.yml
  docs/en/10-third-party/05-bi/17-Ontop.md
  docs/en/10-third-party/05-bi/img/ontop-query.webp
  docs/en/14-reference/03-taos-sql/07-select.md
  docs/en/14-reference/05-connector/10-cpp.md
  docs/en/14-reference/05-connector/26-rust.md
  docs/en/14-reference/05-connector/30-python.md
  docs/en/assets/resources/_collectd.mdx
  docs/zh/10-third-party/05-bi/17-Ontop.md
  docs/zh/10-third-party/05-bi/img/ontop-query.webp
  docs/zh/14-reference/01-components/_collectd.mdx
  docs/zh/14-reference/02-tools/08-taos-cli.md
  docs/zh/14-reference/03-taos-sql/07-select.md
  docs/zh/14-reference/05-connector/10-cpp.mdx
  docs/zh/14-reference/05-connector/26-rust.mdx
  docs/zh/14-reference/05-connector/30-python.mdx
  include/common/tgrant.h
  include/util/taoserror.h
  include/util/tcompare.h
  source/client/src/clientHb.c
  source/client/src/clientImpl.c
  source/client/test/stmt2Test.cpp
  source/common/src/tdataformat.c
  source/common/src/tglobal.c
  source/common/src/tgrant.c
  source/dnode/mgmt/mgmt_vnode/src/vmWorker.c
  source/dnode/mnode/impl/src/mndDb.c
  source/dnode/mnode/impl/src/mndMain.c
  source/dnode/vnode/inc/vnode.h
  source/dnode/vnode/src/meta/metaQuery.c
  source/dnode/vnode/src/tsdb/tsdbRead2.c
  source/dnode/vnode/src/vnd/vnodeOpen.c
  source/dnode/vnode/src/vnd/vnodeQuery.c
  source/libs/parser/src/parInsertSql.c
  source/libs/scalar/src/scalar.c
  source/util/src/talgo.c
  source/util/src/tcompare.c
  source/util/src/terror.c
  test/cases/01-DataTypes/test_composite_key_load.py
  test/cases/05-VirtualTables/test_vtable_insert.py
  test/cases/07-DataQuerying/04-OrderBy/test_sort_double_col.py
  test/ci/cases.task
  tests/system-test/0-others/grant.py
  tests/system-test/0-others/information_schema.py
  tests/system-test/2-query/func_to_char_timestamp.py
Labels: team engine

#31706 Feat/ts 6100 3.0 mm
  include/libs/new-stream/streamReader.h
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/executor/src/executor.c
  source/libs/new-stream/src/streamReader.c
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
Labels: team engine

#31680 fix/send-heartbeat-statis
  source/libs/sync/src/syncMain.c
Labels: team engine

#31717 test: add subquery limit cases
  docs/zh/14-reference/03-taos-sql/14-stream.md
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_limit.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
Labels: team engine

#31715 fix: delete stream-test.py case
  tests/army/tools/benchmark/basic/json/stream_exist_stb_tag_insert_partition.json
  tests/army/tools/benchmark/basic/json/stream_exist_stb_tag_prepare.json
  tests/army/tools/benchmark/basic/stream-test.py
  tests/army/tools/benchmark/basic/stream_function_test.py
  tests/coverage/old_covtests.task
  tests/parallel_test/cases.task
  tools/taos-tools/src/benchInsert.c
  tools/taos-tools/src/benchJsonOpt.c
Labels: team tools

#31486 chore: support cmake option TAOSWS_GIT_TAG like taosadapter
  CMakeLists.txt
  cmake/external.cmake
  cmake/options.cmake
Labels: team tools

#31725 test: add test for save res.
  test/cases/13-StreamProcessing/06-ResultSaved/test_result_saved_bug_1.py
  test/cases/13-StreamProcessing/06-ResultSaved/test_result_saved_comprehensive.py
  test/cases/13-StreamProcessing/06-ResultSaved/test_result_saved_datatype_precision.py
  test/cases/13-StreamProcessing/06-ResultSaved/test_result_saved_errors.py
  test/cases/13-StreamProcessing/06-ResultSaved/test_result_saved_primary_key.py
  test/cases/13-StreamProcessing/06-ResultSaved/test_result_saved_schema_validation.py
Labels: team engine

#31726 Feat/ts 6100 3.0 mm
  source/dnode/vnode/src/vnd/vnodeStream.c
Labels: team engine

#31731 test: add more cases
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_count.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_event.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_period.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_state.py
  test/cases/13-StreamProcessing/20-UseCase/test_nevados_bug1.py
  test/cases/13-StreamProcessing/20-UseCase/test_nevados_bug2.py
  test/ci/streamlist_for_ci.task
Labels: team engine

#31737 feat: [TS-6100] Fix ignore_nodata_trigger syntax error.
  source/libs/parser/src/parTokenizer.c
Labels: team engine

#31740 test: add cases
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_count.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_count_bug.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_event.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_event_bug.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_session.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_session_bug.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_state.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_state_bug.py
  test/ci/streamlist_for_ci.task
Labels: team engine

#31748 feat: [TS-6100] Fix error when no child table in super virtual table.
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31749 feat: [TS-6100] Disable scan path optimize in stream query.
  source/libs/planner/src/planOptimizer.c
Labels: team engine

#31739 fix: timerange
  source/libs/scalar/src/scalar.c
Labels: team engine

#31744 fix: tbname too long
  include/util/taoserror.h
  source/libs/executor/src/executor.c
  source/util/src/terror.c
Labels: team engine

#31755 Update 03-kubernetes.md
  docs/en/08-operation/03-deployment/03-kubernetes.md
Labels: team application

#31752 fix(stream): fix calc data schema of virtual tables
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31681 enh: add log for snapshot
  source/dnode/vnode/src/vnd/vnodeOpen.c
  source/libs/sync/src/syncMain.c
  source/libs/sync/src/syncPipeline.c
  source/libs/sync/src/syncRaftLog.c
  source/libs/sync/src/syncSnapshot.c
Labels: team engine

#31757 Feat/ts 6100 3.0 kjq
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31758 test: add save res test to ci.
  test/cases/13-StreamProcessing/06-ResultSaved/test_result_saved_comprehensive.py
  test/ci/streamlist_for_ci.task
Labels: team engine

#31761 fix(stream): fix meta pull at recalculation
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31770 fix(stream): fix calc data cache range of virtual table
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31765 feat: [TS-6100] Support indef rows function in external window.
  include/libs/nodes/plannodes.h
  source/libs/nodes/src/nodesCloneFuncs.c
  source/libs/nodes/src/nodesCodeFuncs.c
  source/libs/nodes/src/nodesMsgFuncs.c
  source/libs/parser/test/CMakeLists.txt
  source/libs/planner/src/planLogicCreater.c
  source/libs/planner/src/planPhysiCreater.c
Labels: team engine

#31772 feat: [TS-6100] Fix planner cannot find slotId
  source/libs/planner/src/planPhysiCreater.c
Labels: team engine

#31727 enh: TD-36324-improve-sync-heartbeat-log
  source/dnode/mgmt/mgmt_mnode/src/mmWorker.c
  source/libs/sync/inc/syncUtil.h
  source/libs/sync/src/syncMain.c
  source/libs/sync/src/syncReplication.c
  source/libs/sync/src/syncUtil.c
Labels: team engine

#31776 feat: [TS-6100] Fix tbname/tag query of vtable.
  source/libs/executor/src/virtualtablescanoperator.c
  source/libs/planner/src/planLogicCreater.c
  source/libs/planner/src/planPhysiCreater.c
Labels: team engine

#31778 feat(stream): fix dead lock
  source/libs/executor/src/scanoperator.c
Labels: team engine

#31777 Feat/ts 6100 3.0 kjq
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31746 fix: taosd crush in query when insufficient memory
  source/dnode/vnode/src/tsdb/tsdbRead2.c
Labels: team engine

#31779 feat(stream): delete msg from wal
  include/libs/wal/wal.h
  source/dnode/vnode/src/tq/tqMeta.c
  source/dnode/vnode/src/tq/tqRead.c
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/sync/src/syncRaftLog.c
  source/libs/wal/src/walRead.c
  source/libs/wal/test/walMetaTest.cpp
Labels: team engine

#31780 fix: overflow check in snprintf
  source/dnode/vnode/src/vnd/vnodeQuery.c
Labels: team engine

#31781 use scene for test_scene_meters.py
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/dbs.sql
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/asset01.369E6FCE.avro-tbtags
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/asset01.369E6FCE.avro-tbtags.m
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/asset01.8BBF1DE0.avro-tbtags
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/asset01.8BBF1DE0.avro-tbtags.m
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-369E6FCE/asset01.3504228878290.0.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-369E6FCE/stbname
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878219.0.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878221.2.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878223.4.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878227.6.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878229.8.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878230.10.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878231.12.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878235.14.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878244.1.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878247.3.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878249.5.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878252.13.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878254.9.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878255.11.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/asset01.3504228878256.7.avro
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/data0-8BBF1DE0/stbname
  test/cases/13-StreamProcessing/20-UseCase/asset01/data/taosdump.3504228878192/dbs.sql
  test/cases/13-StreamProcessing/20-UseCase/asset01/streams.sql
  test/cases/13-StreamProcessing/20-UseCase/asset01/vtables.sql
  test/cases/13-StreamProcessing/20-UseCase/test_scene_meters.py
  test/new_test_framework/utils/eos.py
  test/new_test_framework/utils/etool.py
Labels: team tools

#31784 fix: needn't windows info in sliding/period notify
  source/libs/new-stream/src/streamUtil.c
Labels: team engine

#31785 test: add join cases
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
Labels: team engine

#31786 fix(stream): fix data cache of period trigger
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31788 feat: [TS-6100] Support alias name for place holder table
  source/libs/parser/inc/parAst.h
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parAstCreater.c
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31793 fix(stream): handle redundant orig table reader info of stream trigger task
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31794 fix: out put ts is null
  source/libs/executor/src/dataInserter.c
Labels: team engine

#31795 fix: mem leak when terminating
  source/libs/new-stream/src/dataSinkMgr.c
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31791 test: add cases to ci
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_limit.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_session.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_state.py
Labels: team engine

#31799 fix: auto create table
  source/libs/new-stream/src/streamRunner.c
Labels: team engine

#31782 fix: set lcn before do s3 migrate.
  source/dnode/vnode/src/tsdb/tsdbRetention.c
Labels: team engine

#31804 test: add test for recalc.
  test/cases/13-StreamProcessing/08-Recalc/test_recalc_expired_bug_1.py
  test/cases/13-StreamProcessing/08-Recalc/test_recalc_expired_time.py
  test/cases/13-StreamProcessing/08-Recalc/test_recalc_ignore_disorder.py
  test/cases/13-StreamProcessing/08-Recalc/test_recalc_watermark.py
Labels: team engine

#31812 feat(stream): fix delete msg error
  source/dnode/vnode/src/vnd/vnodeStream.c
Labels: team engine

#31802 test: add cases
  test/cases/13-StreamProcessing/04-Options/test_options_stbl.py
Labels: internal

#31816 feat: [TS-6100] Add watermark and max_delay check.
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31817 fix: gen crash
  source/dnode/vnode/src/vnd/vnodeSvr.c
Labels: team engine

#31811 fix: set valid itype
  source/dnode/mgmt/node_mgmt/src/dmTransport.c
Labels: team engine

#31823 recover log level
  source/dnode/mgmt/node_mgmt/src/dmTransport.c
Labels: team engine

#31824 Fix/6100/datasink/usedafterfree
  include/libs/new-stream/dataSink.h
  source/libs/new-stream/src/dataSinkMgr.c
Labels: team engine

#31825 fix: external window and msg response issues
  source/common/src/tglobal.c
  source/dnode/mgmt/mgmt_snode/src/smWorker.c
  source/dnode/snode/src/snode.c
  source/libs/executor/src/executorInt.c
  source/libs/executor/src/externalwindowoperator.c
  source/libs/new-stream/src/streamCheckpoint.c
  source/util/src/tpagedbuf.c
Labels: team engine

#31829 test: add vtable cases
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_count_1.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_count_2.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_event.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_session.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
Labels: team engine

#31826 Feat/ts 6100 3.0 lihui
  test/cases/13-StreamProcessing/04-Options/test_meta.py
Labels: internal

#31834 feat: [TS-6100] Do not translate const value as column.
  source/libs/parser/src/parAstCreater.c
Labels: team engine

#31798 fix: correct timediff function bug and redress docs
  docs/en/14-reference/03-taos-sql/10-function.md
  docs/zh/14-reference/03-taos-sql/10-function.md
  source/libs/scalar/src/sclfunc.c
  tests/army/query/function/ans/timediff.csv
  tests/army/query/function/in/timediff.in
  tests/system-test/2-query/Timediff.py
Labels: team engine

#31822 docs: update stream docs
  docs/zh/14-reference/01-components/01-taosd.md
  docs/zh/14-reference/03-taos-sql/14-stream.md
Labels: team engine

#31837 feat: [TS-6100] Handle origin table change schema during virtual tabl…
  source/libs/planner/src/planLogicCreater.c
Labels: team engine

#31836 test: add cases
  test/cases/13-StreamProcessing/04-Options/test_meta.py
Labels: internal

#31838 Feat/ts 6100 3.0 zlv
  test/cases/13-StreamProcessing/01-Snode/snode_mgmt_zlv.py
Labels: internal

#31840 Feat/ts 6100 3.0 mm
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/new-stream/src/streamReader.c
Labels: team engine

#31843 feat: [TS-6100] Fix leaks.
  source/libs/executor/src/dynqueryctrloperator.c
Labels: team engine

#31841 Feat/ts 6100 3.0.pw10
  include/common/streamMsg.h
  source/common/src/msg/streamMsg.c
  source/dnode/mnode/impl/inc/mndStream.h
  source/dnode/mnode/impl/src/mndStreamMgmt.c
  source/dnode/mnode/impl/src/mndStreamUtil.c
  source/libs/new-stream/inc/streamInt.h
  source/libs/new-stream/src/streamMgmt.c
Labels: team engine

#31796 fix: TD-36442 show full condition
  source/libs/nodes/src/nodesToSQLFuncs.c
Labels: team engine

#31828 enh: TS-5926-force-repair-wal
  docs/en/14-reference/01-components/01-taosd.md
  docs/zh/14-reference/01-components/01-taosd.md
  include/common/tglobal.h
  source/common/src/tglobal.c
  source/libs/wal/src/walMeta.c
Labels: team engine

#31853 submit test_idmp_meters_bug3.py
  test/cases/13-StreamProcessing/20-UseCase/test_idmp_meters.py
  test/cases/13-StreamProcessing/20-UseCase/test_idmp_meters_bug3.py
Labels: team tools

#31856 fix: error code check
  source/dnode/vnode/src/vnd/vnodeSvr.c
Labels: team engine

#31845 test: add cases
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding_bug4.py
  test/new_test_framework/utils/streamUtil.py
Labels: team engine

#31855 rename taos & taosd
  include/util/cus_name.h
Labels: team engine

#31857 Feat/ts 6100 3.0 mm
  include/libs/executor/storageapi.h
  include/libs/new-stream/streamReader.h
  source/dnode/vnode/src/vnd/vnodeApi.c
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/new-stream/src/streamReader.c
Labels: team engine

#31867 test: add case test_idmp_meters_bug5.py
  test/cases/13-StreamProcessing/20-UseCase/test_idmp_meters.py
  test/cases/13-StreamProcessing/20-UseCase/test_idmp_meters_bug5.py
Labels: team tools

#31869 feat: [TS-6100] Restore deleted code in mndSma.c since they are still…
  source/dnode/mnode/impl/src/mndSma.c
Labels: team engine

#31872 feat: [TS-6100] Fix fill range check
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31880 fix: ci case issues
  include/common/tglobal.h
  source/common/src/tdatablock.c
  source/common/src/tglobal.c
  source/dnode/mgmt/mgmt_mnode/src/mmWorker.c
  source/dnode/mnode/impl/src/mndShow.c
  source/libs/executor/src/externalwindowoperator.c
  source/libs/new-stream/src/streamRunner.c
  source/libs/parser/src/parTranslater.c
  tests/army/cmdline/fullopt.py
  tests/army/temp_test_vtable_select_test_function.result
  tests/develop-test/2-query/table_count_scan.py
  tests/parallel_test/cases.task
  tests/script/tsim/parser/tags_filter.sim
  tests/script/tsim/parser/union.sim
  tests/script/tsim/query/sys_tbname.sim
  tests/script/tsim/query/tableCount.sim
  tests/script/tsim/snode/basic1.sim
  tests/script/tsim/valgrind/checkError1.sim
  tests/system-test/0-others/information_schema.py
  tests/system-test/0-others/splitVGroup.py
  tests/system-test/0-others/splitVGroupWal.py
  tests/system-test/0-others/tag_index_basic.py
  tests/system-test/0-others/test_hot_refresh_configurations.py
  tests/system-test/0-others/view/non_marterial_view/test_view.py
  tests/system-test/1-insert/precisionNS.py
  tests/system-test/1-insert/precisionUS.py
  tests/system-test/2-query/cols_function.py
  tests/system-test/2-query/union.py
Labels: team engine

#31876 test: modify for partition by %%1
  test/cases/13-StreamProcessing/03-TriggerMode/test_count.py
  test/cases/13-StreamProcessing/03-TriggerMode/test_fill_history.py
  test/cases/13-StreamProcessing/03-TriggerMode/test_state.py
  test/cases/13-StreamProcessing/04-Options/test_options_stbl.py
  test/cases/13-StreamProcessing/04-Options/test_options_vtbl.py
Labels: internal

#31864 Feat/ts 6100 3.0 mm
  include/common/streamMsg.h
  include/libs/executor/executor.h
  include/libs/executor/storageapi.h
  include/libs/new-stream/streamReader.h
  source/common/src/msg/streamMsg.c
  source/dnode/vnode/src/tq/tqRead.c
  source/dnode/vnode/src/vnd/vnodeApi.c
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/executor/src/executor.c
  source/libs/executor/src/scanoperator.c
  source/libs/new-stream/src/streamReader.c
  source/libs/new-stream/src/streamTriggerTask.c
  test/cases/13-StreamProcessing/01-Snode/snode_params_alter.py
  tests/system-test/7-tmq/td-33225.py
  tests/system-test/7-tmq/tmq_taosx.py
  utils/test/c/tmq_taosx_ci.c
Labels: team engine

#31890 fix: calc timerange
  source/libs/scalar/src/sclfunc.c
Labels: team engine

#31879 fix new testcases
  test/cases/uncatalog/system-test/2-query/test_tagFilter.py
  test/cases/uncatalog/system-test/7-tmq/test_stbTagFilter_multiCtb.py
  test/cases/uncatalog/system-test/7-tmq/tmqCommon.py
Labels: team platform
