Repository taosdata/TDengine, pull requests merged in 2025-05, with the labels that each got.

#30969 test: migrate cases
  test/cases/03-Tables/01-NormalTables/02-Drop/test_normal_table_delete_reuse1.py
  test/cases/03-Tables/01-NormalTables/02-Drop/test_normal_table_delete_reuse2.py
  test/cases/03-Tables/01-NormalTables/02-Drop/test_normal_table_delete_writing.py
  test/cases/23-Users/test_user_basic.py
  test/cases/23-Users/test_user_password.py
  test/cases/23-Users/test_user_privilege_create_db.py
  test/cases/23-Users/test_user_privilege_db.py
  test/cases/23-Users/test_user_privilege_sysinfo.py
  test/cases/23-Users/test_user_privilege_table.py
  test/cases/23-Users/test_user_privilege_topic.py
  test/cases/23-Users/test_user_whitelist.py
  test/ci/cases.task
  test/new_test_framework/utils/sql.py
Labels: team engine

#30972 test: migrate cases
  test/cases/19-ManageNodes/01-Dnode/test_dnode_alter_debugflag.py
  test/cases/19-ManageNodes/02-Mnode/test_mnode_basic1.py
  test/cases/19-ManageNodes/02-Mnode/test_mnode_basic2.py
  test/cases/19-ManageNodes/02-Mnode/test_mnode_basic3.py
  test/cases/19-ManageNodes/02-Mnode/test_mnode_basic4.py
  test/cases/19-ManageNodes/02-Mnode/test_mnode_basic5.py
  test/cases/19-ManageNodes/02-Mnode/test_mnode_basic6.py
  test/ci/cases.task
  test/new_test_framework/utils/clusterCommonCheck.py
  test/new_test_framework/utils/server/dnode.py
  test/new_test_framework/utils/sql.py
Labels: team engine

#30973 test: migrate cases
  test/cases/02-Databases/05-Vnode/test_stable_balance_replica1.py
  test/cases/02-Databases/05-Vnode/test_stable_dnode2.py
  test/cases/02-Databases/05-Vnode/test_stable_dnode2_stop.py
  test/cases/02-Databases/05-Vnode/test_stable_dnode3.py
  test/cases/02-Databases/05-Vnode/test_stable_replica3_dnode6.py
  test/cases/02-Databases/05-Vnode/test_stable_replica3_vnode3.py
  test/cases/02-Databases/05-Vnode/test_vnode_replica3_basic.py
  test/cases/02-Databases/05-Vnode/test_vnode_replica3_import.py
  test/cases/02-Databases/05-Vnode/test_vnode_replica3_many.py
  test/cases/02-Databases/05-Vnode/test_vnode_replica3_repeat.py
  test/cases/02-Databases/05-Vnode/test_vnode_replica3_vgroup.py
  test/cases/19-ManageNodes/03-Qnode/test_qnode_basic1.py
  test/cases/19-ManageNodes/04-Snode/test_snode_basic1.py
  test/cases/22-Show/test_show_alive.py
  test/ci/cases.task
  test/new_test_framework/utils/clusterCommonCheck.py
  test/new_test_framework/utils/server/dnode.py
Labels: team engine

#30974 test: migrate cases
  test/cases/02-Databases/06-Sync/test_sync_3Replica1VgElect.py
  test/cases/02-Databases/06-Sync/test_sync_3Replica5VgElect.py
  test/cases/02-Databases/06-Sync/test_sync_vnodesnapshot_rsma.py
  test/cases/50-Others/01-Valgrind/test_valgrind_basic1.py
  test/cases/50-Others/01-Valgrind/test_valgrind_basic2.py
  test/cases/50-Others/01-Valgrind/test_valgrind_basic3.py
  test/cases/50-Others/01-Valgrind/test_valgrind_basic4.py
  test/cases/50-Others/01-Valgrind/test_valgrind_checkerror1.py
  test/cases/50-Others/01-Valgrind/test_valgrind_checkerror2.py
  test/cases/50-Others/01-Valgrind/test_valgrind_checkerror3.py
  test/cases/50-Others/01-Valgrind/test_valgrind_checkerror4.py
  test/cases/50-Others/01-Valgrind/test_valgrind_checkerror5.py
  test/cases/50-Others/01-Valgrind/test_valgrind_checkerror6.py
  test/cases/50-Others/01-Valgrind/test_valgrind_checkerror7.py
  test/cases/50-Others/01-Valgrind/test_valgrind_checkerror8.py
  test/ci/cases.task
Labels: team engine

#30975 fix(stream): fix checkpoint hang in vtable stream processing
  source/libs/executor/src/virtualtablescanoperator.c
  source/libs/stream/src/streamCheckpoint.c
  source/libs/stream/src/streamDispatch.c
  source/libs/stream/src/streamExec.c
  tests/army/stream/test_stream_vtable.py
Labels: team engine

#30942 fix(stream): fix the double release stream object in mnode.
  source/dnode/mnode/impl/src/mndAnode.c
  source/dnode/mnode/impl/src/mndStreamHb.c
  source/dnode/mnode/impl/src/mndStreamTrans.c
  source/dnode/mnode/impl/src/mndStreamUtil.c
  source/dnode/mnode/sdb/src/sdbHash.c
Labels: team engine

#30935 use official repo of xz and other stuffs
  build.sh
  cmake/external.cmake
  tools/CMakeLists.txt
Labels: from community

#30991 test: migrate cases
  test/cases/07-DataQuerying/01-Operator/test_like.py
  test/cases/07-DataQuerying/02-Filter/test_condition.py
  test/cases/07-DataQuerying/02-Filter/test_condition_scl.py
  test/cases/07-DataQuerying/02-Filter/test_stable_filter_column.py
  test/cases/07-DataQuerying/02-Filter/test_stable_filter_column_tag_timestamp.py
  test/cases/07-DataQuerying/02-Filter/test_stable_filter_no.py
  test/cases/07-DataQuerying/02-Filter/test_stable_filter_tag.py
  test/cases/07-DataQuerying/02-Filter/test_stable_filter_timestamp.py
  test/cases/07-DataQuerying/02-Filter/test_table_filter_column.py
  test/cases/07-DataQuerying/02-Filter/test_table_filter_column_timestamp.py
  test/cases/07-DataQuerying/02-Filter/test_table_filter_no.py
  test/cases/07-DataQuerying/02-Filter/test_table_filter_timestamp.py
  test/cases/07-DataQuerying/06-Limit/test_limit1.py
  test/cases/07-DataQuerying/06-Limit/test_limit2.py
  test/cases/07-DataQuerying/09-SelectList/test_column_1.py
  test/cases/07-DataQuerying/09-SelectList/test_column_7.py
  test/cases/07-DataQuerying/09-SelectList/test_const_col.py
  test/cases/07-DataQuerying/09-SelectList/test_distinct.py
  test/cases/10-Functions/03-Selection/test_func_last_basic.py
  test/cases/10-Functions/03-Selection/test_func_last_both.py
  test/cases/10-Functions/03-Selection/test_func_last_cache.py
  test/cases/10-Functions/03-Selection/test_func_last_groupby.py
  test/cases/10-Functions/03-Selection/test_func_last_lru.py
  test/cases/10-Functions/03-Selection/test_func_last_row1.py
  test/cases/10-Functions/03-Selection/test_func_last_row2.py
  test/cases/10-Functions/03-Selection/test_func_last_row3.py
  test/ci/cases.task
Labels: team engine

#30995 docs: dbeaver with 25.0.4 version make picture
  docs/en/10-third-party/07-tool/01-dbeaver.md
  docs/en/assets/dbeaver-01.png
  docs/en/assets/dbeaver-01.webp
  docs/en/assets/dbeaver-02.png
  docs/en/assets/dbeaver-02.webp
  docs/en/assets/dbeaver-03.png
  docs/en/assets/dbeaver-03.webp
  docs/en/assets/dbeaver-04.png
  docs/en/assets/dbeaver-04.webp
  docs/en/assets/dbeaver-05.png
  docs/en/assets/dbeaver-05.webp
  docs/zh/10-third-party/07-tool/01-dbeaver.md
  docs/zh/10-third-party/07-tool/dbeaver/dbeaver-browse-data-zh.webp
  docs/zh/10-third-party/07-tool/dbeaver/dbeaver-config-tdengine-zh.webp
  docs/zh/10-third-party/07-tool/dbeaver/dbeaver-connect-tdengine-test-zh.webp
  docs/zh/10-third-party/07-tool/dbeaver/dbeaver-connect-tdengine-zh.webp
  docs/zh/10-third-party/07-tool/dbeaver/dbeaver-sql-execution-zh.webp
Labels: team tools

#31003 docs:set the minimum required version of CMake to 3.18
  README.md
Labels: team platform

#30997 test: migrate cases
  test/cases/01-DataTypes/test_const.py
  test/cases/01-DataTypes/test_nchar.py
  test/cases/01-DataTypes/test_null.py
  test/cases/01-DataTypes/test_null_char.py
  test/cases/02-Databases/06-Precision/test_db_precision_ns.py
  test/cases/02-Databases/07-Flush/test_db_flush.py
  test/cases/03-Tables/02-SubTables/01-Create/test_tags_dynamically_specifiy.py
  test/cases/03-Tables/02-SubTables/03-Alter/test_set_tag_vals.py
  test/cases/04-SuperTables/03-Alter/test_parser_op.py
  test/cases/06-DataIngestion/03-Delete/test_delete.py
  test/cases/06-DataIngestion/03-Delete/test_insert_drop.py
  test/cases/07-DataQuerying/01-Operator/test_case_when_sum.py
  test/cases/07-DataQuerying/02-Filter/test_filter_timestamp.py
  test/cases/07-DataQuerying/02-Filter/test_filter_where.py
  test/cases/07-DataQuerying/02-Filter/test_tags_filter.py
  test/cases/07-DataQuerying/03-GroupBy/test_groupby2.py
  test/cases/07-DataQuerying/03-GroupBy/test_groupby_distinct.py
  test/cases/07-DataQuerying/03-GroupBy/test_groupby_top.py
  test/cases/07-DataQuerying/06-Limit/test_projection_limit_offset.py
  test/cases/07-DataQuerying/06-Limit/test_table_merge_limit.py
  test/cases/07-DataQuerying/07-SLimit/test_slimit1.py
  test/cases/07-DataQuerying/07-SLimit/test_slimit2.py
  test/cases/07-DataQuerying/07-SLimit/test_slimit_alter_tags.py
  test/cases/07-DataQuerying/07-SLimit/test_slimit_limit.py
  test/cases/07-DataQuerying/08-SubQuery/test_nestquery.py
  test/cases/07-DataQuerying/09-SelectList/test_select_res_num.py
  test/cases/07-DataQuerying/10-Union/test_union.py
  test/cases/07-DataQuerying/10-Union/test_union_sysinfo.py
  test/cases/07-DataQuerying/13-Distinct/test_distinct.py
  test/cases/07-DataQuerying/14-Explain/r/explain_tsorder.result
  test/cases/07-DataQuerying/14-Explain/t/explain_tsorder.sql
  test/cases/07-DataQuerying/14-Explain/test_explain.py
  test/cases/07-DataQuerying/14-Explain/test_explain_tsorder.py
  test/cases/07-DataQuerying/16-PsedoColumn/test_tbname_in.py
  test/cases/07-DataQuerying/17-Tags/test_select_distinct_tag.py
  test/cases/07-DataQuerying/17-Tags/test_select_with_tags.py
  test/cases/07-DataQuerying/18-Regexp/test_regex.py
  test/cases/07-DataQuerying/19-BiMode/test_bi_star_table.py
  test/cases/07-DataQuerying/19-BiMode/test_bi_tag_scan.py
  test/cases/07-DataQuerying/19-BiMode/test_bi_tbname_col.py
  test/cases/07-DataQuerying/99-Others/test_select_across_vnodes.py
  test/cases/07-DataQuerying/99-Others/test_select_from_cache_disk.py
  test/cases/07-DataQuerying/99-Others/test_select_mixed_block.py
  test/cases/10-Functions/01-SingleRow/test_func_char_scalar.py
  test/cases/10-Functions/01-SingleRow/test_single_row_in_tb.py
  test/cases/10-Functions/02-Aggregate/test_func_apercentile.py
  test/cases/10-Functions/02-Aggregate/test_func_spread.py
  test/cases/10-Functions/03-Selection/test_func_topbot.py
  test/cases/11-TimeSeriesExtensions/03-TimeWindow/test_interval_empty_range.py
  test/cases/11-TimeSeriesExtensions/03-TimeWindow/test_interval_empty_range_scl.py
  test/cases/11-TimeSeriesExtensions/03-TimeWindow/test_sliding.py
  test/cases/11-TimeSeriesExtensions/05-EventWindow/test_event.py
  test/ci/cases.task
Labels: team engine

#30992 Update make_install.bat
  packaging/tools/make_install.bat
Labels: team platform

#31006 opt:update workflow to support fork repo pull request
  .github/workflows/label-pr-by-team.yml
Labels: team platform

#31011 opt: modify workflow,change, pull_request to pull_request_target
  .github/workflows/label-pr-by-team.yml
Labels: team platform

#31013 modify workflow,change, pull_request to pull_request_target
  .github/workflows/label-pr-by-team.yml
Labels: team platform

#30994 fix(rpc): update log level
  source/libs/transport/src/transCli.c
Labels: team engine

#31018 fix: fix seq for JAVA_PATH and enh apt install
  packaging/setup_env.sh
Labels: team platform

#31008 fix: [TS-6448] Fix schema is old when origin table's column has same prefix during virtual supertable query.
  source/libs/executor/src/scanoperator.c
  tests/army/vtable/test_vtable_schema_is_old.py
Labels: team engine

#31022 test: migrate cases
  test/cases/07-DataQuerying/04-OrderBy/test_multi_orderby.py
  test/cases/10-Functions/01-SingleRow/test_func_scalar.py
  test/cases/11-TimeSeriesExtensions/01-PartitionBy/test_partitonby.py
  test/cases/11-TimeSeriesExtensions/03-TimeWindow/test_interval2.py
  test/cases/11-TimeSeriesExtensions/03-TimeWindow/test_interval_offset.py
  test/cases/11-TimeSeriesExtensions/07-CountWindow/test_count.py
  test/cases/11-TimeSeriesExtensions/07-CountWindow/test_count_sliding.py
  test/cases/29-JoinQueries/test_join_interval.py
  test/cases/29-JoinQueries/test_join_order.py
  test/cases/29-JoinQueries/test_join_pk.py
  test/ci/cases.task
Labels: team engine

#31023 test: migrate cases
  docs/zh/05-basic/02-insert.md
  test/cases/06-DataIngestion/01-Insert/test_insert_timestamp.py
  test/cases/06-DataIngestion/03-Delete/test_delete_query.py
  test/cases/07-DataQuerying/01-Operator/test_like_tag.py
  test/cases/07-DataQuerying/02-Filter/test_filter_where_complex.py
  test/cases/07-DataQuerying/03-GroupBy/test_groupby_complex.py
  test/cases/07-DataQuerying/04-OrderBy/test_sort_pre_cols.py
  test/cases/07-DataQuerying/06-Limit/test_limit_complex.py
  test/cases/07-DataQuerying/08-SubQuery/test_timeline.py
  test/cases/07-DataQuerying/09-SelectList/test_read.py
  test/cases/07-DataQuerying/09-SelectList/test_select_complex.py
  test/cases/07-DataQuerying/10-Union/test_union_precision.py
  test/cases/07-DataQuerying/10-Union/test_unionall_as_table.py
  test/cases/07-DataQuerying/12-Having/test_having_agg.py
  test/cases/07-DataQuerying/12-Having/test_having_complex.py
  test/cases/07-DataQuerying/17-Tags/test_tags_scan.py
  test/cases/10-Functions/01-SingleRow/test_func_scalar_null.py
  test/cases/10-Functions/02-Aggregate/test_func_stddev2.py
  test/cases/10-Functions/03-Selection/test_func_last_tag.py
  test/cases/10-Functions/04-TimeseriesSpecfic/test_func_diff3.py
  test/cases/11-TimeSeriesExtensions/06-SessionWindow/test_session.py
  test/cases/11-TimeSeriesExtensions/07-CountWindow/test_count1.py
  test/cases/12-DataSubscription/sh/consume.sh
  test/cases/12-DataSubscription/test_tmq_basic1.py
  test/cases/12-DataSubscription/test_tmq_basic2.py
  test/cases/12-DataSubscription/test_tmq_basic3.py
  test/cases/12-DataSubscription/test_tmq_basic4.py
  test/cases/12-DataSubscription/test_tmq_cons1.py
  test/cases/12-DataSubscription/test_tmq_cons2.py
  test/cases/12-DataSubscription/test_tmq_cons3.py
  test/cases/12-DataSubscription/test_tmq_cons4.py
  test/cases/12-DataSubscription/test_tmq_cons_overlap.py
  test/cases/12-DataSubscription/test_tmq_snapshot1.py
  test/cases/12-DataSubscription/test_tmq_snapshot2.py
  test/cases/12-DataSubscription/test_tmq_topic.py
  test/cases/20-Metadata/test_show_db_table_kind.py
  test/cases/20-Metadata/test_sys_tbname.py
  test/cases/20-Metadata/test_table_count.py
  test/cases/25-UDFs/sh/bit_and.c
  test/cases/25-UDFs/sh/compile_udf.sh
  test/cases/25-UDFs/sh/gpd.c
  test/cases/25-UDFs/sh/l2norm.c
  test/cases/25-UDFs/sh/prepare_pyudf.sh
  test/cases/25-UDFs/sh/pybitand.py
  test/cases/25-UDFs/sh/pycumsum.py
  test/cases/25-UDFs/sh/pyl2norm.py
  test/cases/25-UDFs/test_udf_c.py
  test/cases/25-UDFs/test_udf_py.py
  test/cases/25-UDFs/test_udf_with_const.py
  test/ci/cases.task
  test/new_test_framework/utils/sql.py
Labels: team engine

#30956 feat: add tsRoutineReportInterval and integrate into syncNodeTimerRou…
  include/common/tglobal.h
  source/common/src/tglobal.c
  source/dnode/vnode/src/vnd/vnodeSync.c
  source/libs/sync/src/syncReplication.c
  source/libs/sync/src/syncTimeout.c
Labels: team engine

#30746 feat: added crc32 SQL function
  docs/en/14-reference/03-taos-sql/10-function.md
  docs/zh/14-reference/03-taos-sql/10-function.md
  include/libs/function/functionMgt.h
  include/libs/scalar/scalar.h
  source/libs/function/src/builtins.c
  source/libs/scalar/src/sclfunc.c
  tests/army/query/function/ans/crc32.csv
  tests/army/query/function/in/crc32.err
  tests/army/query/function/in/crc32.in
  tests/army/query/function/test_function.py
Labels: from community

#31009 enh: add test case for dual replica
  tests/system-test/0-others/grant.py
Labels: team engine

#31020 fix(stmt2):memleak get fields when parser error
  source/client/src/clientStmt.c
  source/client/src/clientStmt2.c
Labels: team engine

#31005 enh: update database fetch functions to include status in JSON output
  source/dnode/mnode/impl/src/mndDb.c
  source/dnode/mnode/impl/src/mndDump.c
Labels: team engine

#31033 update user's manual for delivery tool v1.3.3
  docs/zh/08-operation/20-inspect-tools/03-taosinstall.md
  docs/zh/08-operation/20-inspect-tools/04-taosinspect.md
  docs/zh/08-operation/20-inspect-tools/index.md
Labels: internal

#31032 test: migrat cases
  test/cases/01-DataTypes/test_column_timestamp.py
  test/cases/02-Databases/01-Create/test_db_keep.py
  test/cases/02-Databases/02-Drop/test_db_delete_writing1.py
  test/cases/07-DataQuerying/19-BiMode/test_bi_star_table.py
  test/cases/07-DataQuerying/19-BiMode/test_bi_tag_scan.py
  test/cases/07-DataQuerying/19-BiMode/test_bi_tbname_col.py
  test/cases/11-TimeSeriesExtensions/03-TimeWindow/test_interval.py
  test/cases/11-TimeSeriesExtensions/03-TimeWindow/test_interval_empty_range_scl.py
  test/cases/31-Views/test_view_mgmt.py
  test/ci/cases.task
  test/new_test_framework/utils/sql.py
  test/new_test_framework/utils/srvCtl.py
Labels: team engine

#31031 docs(datain): rename TDengine 2.x to Query, TDengine 3.x to Data Subscription
  docs/en/06-advanced/05-data-in/index.md
  docs/en/08-operation/01-intro.md
  docs/zh/06-advanced/05-data-in/index.md
  docs/zh/08-operation/01-intro.md
Labels: team tools

#30999 fix: [TS-6445] Fix virtual tables not detecting schema changes.
  .gitignore
  include/common/tmsg.h
  include/libs/catalog/catalog.h
  include/libs/executor/executor.h
  include/libs/qcom/query.h
  source/client/src/clientImpl.c
  source/common/src/msg/tmsg.c
  source/dnode/mnode/impl/src/mndInfoSchema.c
  source/dnode/mnode/impl/src/mndPerfSchema.c
  source/dnode/mnode/impl/src/mndStb.c
  source/dnode/vnode/src/meta/metaTable.c
  source/dnode/vnode/src/meta/metaTable2.c
  source/dnode/vnode/src/vnd/vnodeQuery.c
  source/libs/catalog/inc/catalogInt.h
  source/libs/catalog/src/catalog.c
  source/libs/catalog/src/ctgAsync.c
  source/libs/catalog/src/ctgCache.c
  source/libs/executor/inc/executorInt.h
  source/libs/executor/src/executor.c
  source/libs/executor/src/operator.c
  source/libs/executor/src/querytask.c
  source/libs/nodes/src/nodesCodeFuncs.c
  source/libs/parser/src/parUtil.c
  source/libs/planner/src/planPhysiCreater.c
  source/libs/qcom/src/querymsg.c
  source/libs/qworker/src/qwUtil.c
  tests/army/vtable/test_vtable_query_after_alter.py
Labels: team engine

#31019 enh: add more feat for stb keep.
  docs/en/14-reference/03-taos-sql/04-stable.md
  docs/zh/14-reference/03-taos-sql/04-stable.md
  source/common/src/systable.c
  source/dnode/mnode/impl/src/mndStb.c
  source/libs/parser/src/parTranslater.c
  tests/army/create/create_stb_keep.py
  tests/army/create/test_stb_keep_compact.py
  tests/system-test/0-others/information_schema.py
Labels: team engine

#31041 test: migrate cases
  test/cases/01-DataTypes/test_column_int.py
  test/cases/01-DataTypes/test_datatype_bigint.py
  test/cases/01-DataTypes/test_datatype_bool.py
  test/cases/01-DataTypes/test_datatype_double.py
  test/cases/01-DataTypes/test_datatype_float.py
  test/cases/01-DataTypes/test_datatype_geometry.py
  test/cases/01-DataTypes/test_datatype_int.py
  test/cases/01-DataTypes/test_datatype_json.py
  test/cases/01-DataTypes/test_datatype_nchar1.py
  test/cases/01-DataTypes/test_datatype_nchar2.py
  test/cases/01-DataTypes/test_datatype_smallint.py
  test/cases/01-DataTypes/test_datatype_timestamp.py
  test/cases/01-DataTypes/test_datatype_tinyint.py
  test/cases/01-DataTypes/test_datatype_uint.py
  test/cases/01-DataTypes/test_datatype_unsign.py
  test/cases/01-DataTypes/test_datatype_varbinary.py
  test/cases/01-DataTypes/test_datatype_varchar.py
  test/cases/01-DataTypes/test_null_column.py
  test/cases/01-DataTypes/test_null_tag.py
  test/cases/07-DataQuerying/09-SelectList/test_const.py
  test/ci/cases.task
Labels: team engine

#31045 doc(gpt): update the doc.
  docs/en/06-advanced/06-tdgpt/01-introduction.md
  docs/en/06-advanced/06-tdgpt/09-dev/03-ml/index.md
  docs/zh/06-advanced/06-TDgpt/01-introduction.md
  docs/zh/06-advanced/06-TDgpt/09-dev/03-ml/index.md
Labels: team engine

#31016 fix: standardize shell shebangs and improve code formatting in scripts
  packaging/tools/install.sh
  packaging/tools/make_install.sh
  packaging/tools/remove.sh
  packaging/tools/remove_client.sh
  packaging/tools/tdengine.iss
Labels: team platform

#31049 Add tdsvc.sh script for managing TAOS components
  packaging/tools/how-to-install.md
  packaging/tools/install_spec.sh
  packaging/tools/tdsvc.sh
Labels: team platform

#31046 docs: add out-of-order phenomenon problem
  docs/en/27-train-faq/index.md
  docs/zh/27-train-faq/01-faq.md
Labels: team tools

#31052 fix: remove unnecessary IP/port validation check in transSvr.c
  source/libs/transport/src/transSvr.c
Labels: team platform

#31044 test(stream): update the test cases.
  source/dnode/mnode/impl/src/mndStreamUtil.c
  source/dnode/vnode/src/tqCommon/tqCommon.c
  tests/parallel_test/cases.task
  tests/parallel_test/cases_tdengine.task
  tests/script/tsim/stream/basic2.sim
Labels: team engine

#30985 fix: possible coredump when repair meta file
  source/dnode/vnode/src/meta/metaEntry2.c
  source/dnode/vnode/src/meta/metaOpen.c
Labels: team engine

#31026 enh: grant support data source SparkplugB
  tests/system-test/0-others/grant.py
  tests/system-test/0-others/information_schema.py
Labels: team engine

#31042 fix: TD-34752
  test/new_test_framework/taostest/components/taosd.py
  test/new_test_framework/utils/server/dnode.py
  test/new_test_framework/utils/server/dnodes.py
  test/new_test_framework/utils/srvCtl.py
Labels: team platform

#31055 ci: add localhost as fqdn in tdengine-build.yml
  .github/workflows/tdengine-build.yml
Labels: team platform

#31056 ci: add supportVnodes for /etc/taos/taos.cfg
  .github/workflows/tdengine-release-build.yml
Labels: team platform

#31028 fix: ignore hb send failed issue
  source/client/src/clientEnv.c
  source/client/src/clientImpl.c
  source/client/src/clientMain.c
  source/libs/scheduler/inc/schInt.h
  source/libs/scheduler/src/schJob.c
  source/libs/scheduler/src/schRemote.c
  source/libs/scheduler/src/schUtil.c
  source/libs/scheduler/src/scheduler.c
Labels: team engine

#30996 fix(stmt2):memleak
  source/client/src/clientStmt2.c
  source/libs/parser/src/parInsertUtil.c
Labels: team engine

#31063 feat: [TS-6100] Parse create stream sql: Add unit test.
  source/libs/parser/test/parInitialCTest.cpp
  source/libs/parser/test/parStreamTest.cpp
Labels: team engine

#31066 feat: [TS-6100] Parse create stream sql: Fix partition by tbname error.
  source/dnode/mnode/impl/src/mndStream.c
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31064 fix: delete the default database creation parameter vgroup
  tools/taos-tools/inc/bench.h
  tools/taos-tools/src/benchInsert.c
  tools/taos-tools/src/benchUtil.c
Labels: team tools

#30927 docs: submit spark doc
  docs/en/10-third-party/05-bi/11-superset.md
  docs/en/10-third-party/05-bi/15-spark.md
  docs/en/10-third-party/05-bi/spark-result.png
  docs/en/10-third-party/05-bi/superset-demo1.jpeg
  docs/en/10-third-party/05-bi/superset-demo1.webp
  docs/en/10-third-party/05-bi/superset-demo2.jpeg
  docs/en/10-third-party/05-bi/superset-demo2.webp
  docs/zh/10-third-party/05-bi/11-superset.md
  docs/zh/10-third-party/05-bi/15-spark.md
  docs/zh/10-third-party/05-bi/spark-result.png
  docs/zh/10-third-party/05-bi/superset-demo1.jpeg
  docs/zh/10-third-party/05-bi/superset-demo1.webp
  docs/zh/10-third-party/05-bi/superset-demo2.jpeg
  docs/zh/10-third-party/05-bi/superset-demo2.webp
Labels: team tools

#31068 feat: [TS-6100] Parse create stream sql: Fix wrong subplan num.
  source/dnode/mnode/impl/src/mndStreamMgmt.c
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31072 doc: update a figure.
  docs/zh/06-advanced/06-TDgpt/pic/data-analysis.png
Labels: team engine

#31075 feat: [TS-6100] Parse create stream sql: Fix external window plan.
  source/common/src/msg/streamMsg.c
  source/libs/parser/src/parTranslater.c
  source/libs/planner/src/planScaleOut.c
  source/libs/planner/src/planSpliter.c
Labels: team engine

#31048 fix(stream): extends the node update check interval.
  include/libs/stream/tstream.h
  source/common/src/tglobal.c
  source/dnode/mnode/impl/src/mndMain.c
  source/dnode/mnode/impl/src/mndStream.c
  source/dnode/mnode/impl/src/mndStreamHb.c
  source/dnode/mnode/impl/src/mndStreamUtil.c
  source/dnode/vnode/src/tq/tq.c
  source/dnode/vnode/src/tqCommon/tqCommon.c
  source/libs/executor/src/executil.c
  source/libs/executor/src/streamtimewindowoperator.c
  source/libs/stream/src/streamMeta.c
  tests/system-test/8-stream/checkpoint_info.py
  tests/system-test/8-stream/snode_restart_with_checkpoint.py
Labels: team engine

#31078 feat: [TS-6100] Parse create stream sql: Fix time range condition.
  include/libs/planner/planner.h
  source/libs/parser/inc/parTranslater.h
  source/libs/parser/src/parTranslater.c
  source/libs/planner/src/planLogicCreater.c
Labels: team engine

#31079 feat: [TS-6100] Parse create stream sql: Fix scan node no scanCols.
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31081 feat: [TS-6100] Parse create stream sql: Add encode/decode func for t…
  source/libs/nodes/src/nodesCodeFuncs.c
  source/libs/nodes/src/nodesMsgFuncs.c
Labels: team engine

#31059 fix: double close wal meta file.
  source/libs/wal/src/walMeta.c
Labels: team engine

#30925 feat: persist local configs' stypes.
  include/common/tglobal.h
  source/common/src/tglobal.c
Labels: team engine

#30856 test: add more versions while exec compatibility.py.
  tests/parallel_test/cases.task
  tests/system-test/0-others/compatibility.py
  tests/system-test/0-others/compatibility_basic.py
  tests/system-test/0-others/compatibility_rolling_upgrade.py
  tests/system-test/0-others/compatibility_rolling_upgrade_all.py
  tests/system-test/0-others/part_insertmode.json
  tests/system-test/0-others/sml_restart.py
Labels: team engine

#31088 feat: [TS-6100] Parse create stream sql: Fix external window on super…
  source/libs/parser/src/parTranslater.c
  source/libs/planner/src/planSpliter.c
Labels: team engine

#31087 fix: concurrent execution compatibility test cases.
  tests/parallel_test/cases.task
  tests/system-test/0-others/compatibility_basic.py
Labels: team engine

#31092 feat: [TS-6100] Parse create stream sql: Support period window.
  source/common/src/msg/streamMsg.c
  source/libs/nodes/src/nodesTraverseFuncs.c
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parAstParser.c
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31083 fix: double close wal meta file.
  source/libs/wal/src/walMeta.c
Labels: team engine

#31091 docs: update release note for 3.3.6.6 in office web
  cmake/version.cmake
  docs/en/28-releases/01-tdengine.md
  docs/en/28-releases/03-notes/3.3.6.6.md
  docs/zh/28-releases/01-tdengine.md
  docs/zh/28-releases/03-notes/3.3.6.6.md
Labels: team platform

#31089 fix(ipWhiteList): Refresh user IP white list when drop-dnode finished
  source/dnode/mnode/impl/src/mndDnode.c
  source/dnode/mnode/impl/src/mndTrans.c
Labels: team engine

#30993 opti(tmq): save tmq offset in vnode commit time & change log level
  source/client/src/clientTmq.c
  source/common/src/systable.c
  source/dnode/mnode/impl/inc/mndDef.h
  source/dnode/mnode/impl/src/mndConsumer.c
  source/dnode/mnode/impl/src/mndSubscribe.c
  source/dnode/vnode/inc/vnode.h
  source/dnode/vnode/src/tq/tq.c
  source/dnode/vnode/src/tq/tqOffset.c
  source/dnode/vnode/src/vnd/vnodeCommit.c
  source/libs/planner/src/planOptimizer.c
  tests/parallel_test/cases.task
  tests/system-test/0-others/information_schema.py
  tests/system-test/7-tmq/tmqParamsTest.py
  tests/system-test/7-tmq/tmq_tx484.py
Labels: team engine

#31080 fix(parser):core
  source/client/test/stmt2Test.cpp
  source/libs/parser/src/parInsertSql.c
Labels: team engine

#31036 fix: table schema is too old while upgrade taosd version from 3358 to 3360.
  source/client/src/clientSml.c
Labels: team engine

#31093 doc: add description of configuration parameters that can only be mod…
  docs/zh/14-reference/01-components/01-taosd.md
  docs/zh/14-reference/01-components/02-taosc.md
Labels: team engine

#31095 refactor(stream): print some logs.
  source/common/src/tdatablock.c
  source/libs/executor/inc/executorInt.h
  source/libs/executor/src/executil.c
  source/libs/executor/src/groupoperator.c
  source/libs/executor/src/scanoperator.c
Labels: team engine

#31074 update test doc format
  .github/scripts/generate_case_md.py
  .github/workflows/deploy-case-docs.yml
  test/cases/02-Databases/01-Create/test_db_basic1.py
  test/mkdocs.yml
  test/templates/python/material/function.html.jinja
  test/templates/python/material/partials/nav.html
  test/templates/python/material/partials/toc.html
Labels: team platform

#31099 reorganized catalog
  .github/scripts/generate_case_md.py
  .github/workflows/deploy-case-docs.yml
  test/cases/02-Databases/01-Create/test_db_basic1.py
  test/mkdocs.yml
  test/templates/python/material/function.html.jinja
  test/templates/python/material/partials/nav.html
  test/templates/python/material/partials/toc.html
Labels: team platform

#31098 enh: update the method for generating driver version numbers
  packaging/tools/make_install.sh
  source/client/CMakeLists.txt
  source/client/wrapper/CMakeLists.txt
Labels: team engine

#31067 test: support caselist and env clean
  test/README.md
  test/cases/03-Tables/01-NormalTables/04-Query/test_normal_table_basic04.py
  test/ci/cases.task
  test/conftest.py
  test/new_test_framework/taostest/components/taosd.py
  test/new_test_framework/taostest/frame.py
  test/new_test_framework/taostest/main.py
  test/new_test_framework/utils/before_test.py
  test/run_tests.sh
  test/start_run_test_list.sh
  test/stop_run_test_list.sh
  test/test_list.txt
Labels: team platform

#31102 feat: [TS-6100] Parse create stream sql: No force output when first c…
  source/libs/parser/src/parTranslater.c
  source/libs/parser/test/parStreamTest.cpp
  test/cases/13-StreamProcessing/07-SubQuery/test_create_stream_syntax.py
Labels: team engine

#31107 fix: update symbolic links for libtaosws to support versioned files
  packaging/tools/install.sh
Labels: team platform

#31037 test: migrate cases
  test/cases/02-Databases/02-Drop/test_db_delete_writing1.py
  test/cases/02-Databases/02-Drop/test_db_delete_writing2.py
  test/cases/02-Databases/05-Sync/test_vnode_replica3_many.py
  test/cases/02-Databases/05-Sync/test_vnode_replica3_repeat.py
  test/cases/03-Tables/01-NormalTables/02-Drop/test_normal_table_delete_writing.py
  test/cases/11-TimeSeriesExtensions/03-TimeWindow/test_interval_empty_range_scl.py
  test/ci/cases.task
  test/new_test_framework/utils/server/dnode.py
Labels: team engine

#31109 feat: [TS-6100] Parse create stream sql: Fix placeholder func check.
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31103 chinese characters cannot be entered in the aarch64 version of taos
  tools/shell/inc/shellInt.h
  tools/shell/src/shellCommand.c
  tools/shell/test/shellTest.cpp
Labels: team tools

#31112 test: add batch test description in README
  test/README.md
Labels: team platform

#31065 test: rename tdsql functions
  test/cases/02-Databases/01-Create/test_db_keep.py
  test/cases/02-Databases/05-Sync/test_vnode_replica3_repeat.py
  test/cases/06-DataIngestion/01-Insert/test_insert_double.py
  test/cases/06-DataIngestion/01-Insert/test_insert_query_multi_file.py
  test/cases/07-DataQuerying/12-Having/test_having_with_interval_and_fill.py
  test/cases/10-Functions/04-TimeseriesSpecfic/test_func_diff2.py
  test/cases/12-DataSubscription/test_drop_lost_comsumers.py
  test/cases/12-DataSubscription/test_tmq_params.py
  test/cases/12-DataSubscription/tmqCommon.py
  test/cases/13-StreamProcessing/test_max_delay_interval.py
  test/cases/19-ManageNodes/01-Dnode/clusterCommonCheck.py
  test/cases/19-ManageNodes/01-Dnode/clusterCommonCreate.py
  test/cases/19-ManageNodes/01-Dnode/test_5dnode_3mnode_add_1dnode.py
  test/cases/19-ManageNodes/01-Dnode/test_5dnode_3mnode_stop.py
  test/cases/19-ManageNodes/01-Dnode/test_cluster_basic.py
  test/cases/20-Metadata/test_keep_time_offset.py
  test/cases/22-Show/test_show_basic.py
  test/cases/26-TSMAs/compa4096_tsma.json
  test/cases/26-TSMAs/test_tsma.py
  test/cases/30-DataCompression/mlevel_basic.json
  test/cases/30-DataCompression/test_compress_basic.py
  test/cases/30-DataCompression/test_mlevel_basic.py
  test/cases/tools/benchmark/json/queryInsertdata.json
  test/cases/tools/benchmark/json/queryInsertrestdata.json
  test/cases/tools/benchmark/json/queryQps.json
  test/cases/tools/benchmark/json/queryQps1.json
  test/cases/tools/benchmark/json/queryRestful.json
  test/cases/tools/benchmark/json/queryRestful1.json
  test/cases/tools/benchmark/json/querySpeciMutisql100.json
  test/cases/tools/benchmark/json/querySuperMutisql100.json
  test/cases/tools/benchmark/json/queryTaosc.json
  test/cases/tools/benchmark/json/queryTaosc1.json
  test/cases/tools/benchmark/test_taosdemo_query_with_json.py
  test/ci/cases.task
  test/new_test_framework/utils/frame/sql.py
  test/new_test_framework/utils/sql.py
  test/new_test_framework/utils/util/sql.py
Labels: team engine

#31118 Cd/fix/libtaos version
  packaging/tools/makepkg.sh
Labels: team platform

#31122 fix: update library file paths in makepkg.sh for consistency across platforms
  packaging/tools/makepkg.sh
Labels: team platform

#31123 feat: [TS-6100] Parse create stream sql: Auto generate create stream …
  test/cases/13-StreamProcessing/07-SubQuery/test_create_stream_syntax.py
Labels: team engine

#31121 fix: update APR version to 1.7.6 and adjust URL_HASH
  cmake/external.cmake
Labels: team platform

#31124 fix: update library file paths in makepkg.sh for consistency
  packaging/tools/makepkg.sh
Labels: team platform

#31104 fix: null rpc handler issue
  source/libs/qcom/src/queryUtil.c
  source/libs/scheduler/src/schRemote.c
  source/libs/transport/src/transComm.c
Labels: team engine

#31130 feat: [TS-6100] Parse create stream sql: Use %%tbname in SELECT and W…
  include/libs/function/functionMgt.h
  source/libs/function/src/builtins.c
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parTranslater.c
  test/cases/13-StreamProcessing/07-SubQuery/test_create_stream_syntax.py
Labels: team engine

#31132 docs: jdbc release 3.6.3 version
  docs/en/07-develop/07-tmq.md
  docs/en/14-reference/05-connector/14-java.md
  docs/examples/JDBC/JDBCDemo/pom.xml
  docs/examples/JDBC/SpringJdbcTemplate/pom.xml
  docs/examples/JDBC/connectionPools/pom.xml
  docs/examples/JDBC/consumer-demo/pom.xml
  docs/examples/JDBC/highvolume/pom.xml
  docs/examples/JDBC/mybatisplus-demo/pom.xml
  docs/examples/JDBC/springbootdemo/pom.xml
  docs/examples/JDBC/taosdemo/pom.xml
  docs/examples/java/pom.xml
  docs/zh/07-develop/01-connect/index.md
  docs/zh/07-develop/07-tmq.md
  docs/zh/14-reference/05-connector/14-java.mdx
Labels: team tools

#31100 docs: superset with Other item to config
  docs/en/10-third-party/05-bi/11-superset.md
  docs/zh/10-third-party/05-bi/11-superset.md
Labels: team tools

#31133 feat: [TS-6100] Parse create stream sql: Fix external window wrong plan.
  source/dnode/mgmt/test/snode/dsnode.cpp
  source/libs/parser/src/parTranslater.c
  source/libs/planner/src/planScaleOut.c
  source/libs/planner/src/planSpliter.c
Labels: team engine

#31137 feat: [TS-6100] Parse create stream sql: Fix external window wrong plan.
  source/libs/planner/src/planScaleOut.c
Labels: team engine

#31138 feat: [TS-6100] Parse create stream sql: Fix external window wrong plan.
  source/libs/planner/src/planSpliter.c
Labels: team engine

#31140 feat: [TS-6100] Parse create stream sql: Fix merge node no srcEndGrou…
  source/libs/nodes/src/nodesCodeFuncs.c
Labels: team engine

#31141 feat: [TS-6100] Parse create stream sql: Fix merge node no srcEndGrou…
  source/libs/nodes/src/nodesCodeFuncs.c
Labels: team engine

#31135 fix: invalid time parse in compact database command
  source/libs/parser/inc/sql.y
Labels: team engine

#31144 doc: Update index.md
  docs/zh/06-advanced/06-TDgpt/09-dev/04-tsfm/index.md
Labels: team engine

#31146 docs: add timezone handling information for query results in Go documentation
  docs/en/14-reference/05-connector/20-go.md
  docs/zh/14-reference/05-connector/20-go.mdx
Labels: team tools

#31147 docs(datain): add topic meta options docs in tmq
  docs/zh/06-advanced/05-data-in/02-tmq.md
  docs/zh/06-advanced/05-data-in/tmq-pre2.png
Labels: team tools

#31148 update flink connector version
  docs/en/10-third-party/01-collection/flink.md
  docs/zh/10-third-party/01-collection/12-flink.md
Labels: team tools

#31153 ci: change the exec frequency of the release build
  .github/workflows/tdengine-release-build.yml
Labels: team platform

#31154 fix: ci compatibility test while alter tag size.
  tests/system-test/0-others/compatibility.py
  tests/system-test/0-others/compatibility_basic.py
Labels: team engine

#31161 merge: from main to 3.0 branch
  .github/workflows/tdengine-release-build.yml
  cmake/external.cmake
  docs/en/10-third-party/01-collection/flink.md
  docs/en/10-third-party/05-bi/11-superset.md
  docs/en/14-reference/05-connector/14-java.md
  docs/en/14-reference/05-connector/20-go.md
  docs/examples/JDBC/JDBCDemo/pom.xml
  docs/examples/JDBC/SpringJdbcTemplate/pom.xml
  docs/examples/JDBC/connectionPools/pom.xml
  docs/examples/JDBC/consumer-demo/pom.xml
  docs/examples/JDBC/highvolume/pom.xml
  docs/examples/JDBC/mybatisplus-demo/pom.xml
  docs/examples/JDBC/springbootdemo/pom.xml
  docs/examples/JDBC/taosdemo/pom.xml
  docs/examples/java/pom.xml
  docs/zh/06-advanced/06-TDgpt/09-dev/04-tsfm/index.md
  docs/zh/07-develop/01-connect/index.md
  docs/zh/10-third-party/01-collection/12-flink.md
  docs/zh/10-third-party/05-bi/11-superset.md
  docs/zh/14-reference/05-connector/14-java.mdx
  docs/zh/14-reference/05-connector/20-go.mdx
  packaging/tools/makeclient.sh
  packaging/tools/makepkg.sh
  source/client/src/clientStmt2.c
  source/client/test/stmt2Test.cpp
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parInsertSql.c
  source/libs/qcom/src/queryUtil.c
  source/libs/scheduler/src/schRemote.c
  source/libs/transport/src/transComm.c
  tests/script/api/stmt2-memleak.c
  tests/system-test/0-others/compatibility.py
  tests/system-test/0-others/compatibility_basic.py
Labels: team engine

#31163 fix(stream): reset the sched status if sched failed.
  source/dnode/mnode/impl/inc/mndStream.h
  source/dnode/mnode/impl/src/mndStream.c
  source/dnode/mnode/impl/src/mndStreamTransAct.c
  source/dnode/vnode/src/tq/tq.c
  source/dnode/vnode/src/tqCommon/tqCommon.c
  source/libs/stream/src/streamSched.c
Labels: team engine

#31170 feat: [TS-6100] Parse create stream sql: Fix syntax error.
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parAstCreater.c
  test/cases/13-StreamProcessing/07-SubQuery/test_create_stream_syntax.py
Labels: team engine

#31160 fix: some variables lost while excute taosd -C.
  source/util/src/tconfig.c
Labels: team engine

#31162 Update new-framework-test.yml
  .github/workflows/new-framework-test.yml
Labels: team platform

#31176 feat: [TS-6100] Parse create stream sql: Fix default tag expr
  include/libs/nodes/cmdnodes.h
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parAstCreater.c
  source/libs/parser/src/parTranslater.c
  test/cases/13-StreamProcessing/07-SubQuery/test_create_stream_syntax.py
Labels: team engine

#31157 fix: 修正变量DATA_DIR的大小写使用问题。
  packaging/docker/bin/entrypoint.sh
Labels: from community

#31156 fix: 修正LD_LIBRARY_PATH定义时存在空路径问题。
  packaging/docker/Dockerfile
Labels: from community

#31168 chore: remove grafana gui installation
  docs/en/10-third-party/03-visual/01-grafana.md
  docs/zh/10-third-party/03-visual/01-grafana.mdx
Labels: team tools

#31152 docs: add support for SSRS (SQL Server Reporting Services)
  docs/en/10-third-party/05-bi/16-SSRS.md
  docs/en/10-third-party/05-bi/img/browser-1.webp
  docs/en/10-third-party/05-bi/img/browser-2.webp
  docs/en/10-third-party/05-bi/img/browser-3.webp
  docs/en/10-third-party/05-bi/img/browser-4.webp
  docs/en/10-third-party/05-bi/img/cfg-1.webp
  docs/en/10-third-party/05-bi/img/cfg-2.webp
  docs/en/10-third-party/05-bi/img/create-1.webp
  docs/en/10-third-party/05-bi/img/create-2.webp
  docs/en/10-third-party/05-bi/img/create-3.webp
  docs/en/10-third-party/05-bi/img/deploy.webp
  docs/en/10-third-party/05-bi/img/pre-1.webp
  docs/en/10-third-party/05-bi/img/pre-2.webp
  docs/en/10-third-party/05-bi/img/report-1.webp
  docs/en/10-third-party/05-bi/img/report-2.webp
  docs/en/10-third-party/05-bi/img/report-3.webp
  docs/zh/10-third-party/05-bi/16-SSRS.md
  docs/zh/10-third-party/05-bi/img/browser-1.webp
  docs/zh/10-third-party/05-bi/img/browser-2.webp
  docs/zh/10-third-party/05-bi/img/browser-3.webp
  docs/zh/10-third-party/05-bi/img/browser-4.webp
  docs/zh/10-third-party/05-bi/img/cfg-1.webp
  docs/zh/10-third-party/05-bi/img/cfg-2.webp
  docs/zh/10-third-party/05-bi/img/cfg-4.webp
  docs/zh/10-third-party/05-bi/img/create-1.webp
  docs/zh/10-third-party/05-bi/img/create-2.webp
  docs/zh/10-third-party/05-bi/img/create-3.webp
  docs/zh/10-third-party/05-bi/img/deploy.webp
  docs/zh/10-third-party/05-bi/img/pre-1.webp
  docs/zh/10-third-party/05-bi/img/pre-2.webp
  docs/zh/10-third-party/05-bi/img/report-1.webp
  docs/zh/10-third-party/05-bi/img/report-2.webp
  docs/zh/10-third-party/05-bi/img/report-3.webp
Labels: team tools

#31171 enh(stmt2):add stmt2 log
  source/client/inc/clientStmt2.h
  source/client/src/clientMain.c
  source/client/src/clientStmt2.c
  source/libs/parser/src/parInsertStmt.c
  source/libs/parser/src/parInsertUtil.c
Labels: team engine

#31125 enh: add error code for alter minReservedMemorySize.
  docs/en/14-reference/09-error-code.md
  docs/zh/14-reference/01-components/01-taosd.md
  docs/zh/14-reference/09-error-code.md
  include/util/taoserror.h
  source/util/src/terror.c
  source/util/src/tmempool.c
Labels: team engine

#31172 refactor(stream): check for write queue size for sink tasks.
  include/common/tglobal.h
  include/dnode/vnode/tqCommon.h
  include/libs/stream/tstream.h
  source/common/src/tglobal.c
  source/dnode/snode/src/snode.c
  source/dnode/vnode/src/tq/tq.c
  source/dnode/vnode/src/tq/tqStreamTask.c
  source/dnode/vnode/src/tqCommon/tqCommon.c
  source/libs/stream/src/streamCheckpoint.c
  source/libs/stream/src/streamDispatch.c
  source/libs/stream/src/streamMeta.c
  source/libs/stream/src/streamSched.c
  tests/script/tsim/show/basic.sim
  tests/script/tsim/valgrind/checkError1.sim
Labels: team engine

#31185 fix doc format
  docs/zh/14-reference/03-taos-sql/02-database.md
Labels: team platform

#31186 fix doc format
  docs/zh/14-reference/03-taos-sql/02-database.md
Labels: team platform

#31181 test: fix ci test compatibility.
  tests/system-test/0-others/compatibility_basic.py
Labels: team engine

#31164 test: migrate stream cases
  test/cases/13-StreamProcessing/30-OldPyCases/test_max_delay_interval.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_basic1.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_basic2.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_check.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_checkpoint.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_concat.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_continuewindowclose.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_count.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_delete.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_distribute.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_event.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_fillhistory.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_fillinternal.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_forcewindowclose.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_delete.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_fill.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_history.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_partitionby.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_primary.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_update.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_options.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_partitionby.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_primary.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_session.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_snode.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_state.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_twa.py
  test/ci/cases.task
  test/new_test_framework/utils/clusterCommonCheck.py
  test/new_test_framework/utils/sql.py
Labels: team engine

#31195 feat: [TS-6100] Parse create stream sql: Fix wrong msg type.
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31197 Update 01-taosd.md 修改错别字“checkponit”为“checkpoint”
  docs/zh/14-reference/01-components/01-taosd.md
Labels: from community

#31190 test: update stream utils
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_basic1.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_basic2.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_check.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_checkpoint.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_concat.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_continuewindowclose.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_count.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_delete.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_distribute.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_event.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_fillhistory.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_fillinternal.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_forcewindowclose.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_delete.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_fill.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_history.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_partitionby.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_primary.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_update.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_options.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_partitionby.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_primary.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_session.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_snode.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_state.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_twa.py
  test/cases/13-StreamProcessing/99-Others/test_dev_basic1.py
  test/new_test_framework/utils/__init__.py
  test/new_test_framework/utils/clusterCommonCheck.py
  test/new_test_framework/utils/sql.py
  test/new_test_framework/utils/streamUtil.py
Labels: team engine

#31201 test: frame work
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_basic1.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_basic2.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_check.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_checkpoint.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_concat.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_continuewindowclose.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_count.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_delete.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_distribute.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_event.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_fillhistory.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_fillinternal.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_forcewindowclose.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_delete.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_fill.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_history.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_partitionby.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_primary.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_interp_update.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_options.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_partitionby.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_primary.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_session.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_snode.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_state.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_twa.py
  test/cases/13-StreamProcessing/99-Others/test_dev_basic1.py
  test/new_test_framework/utils/sql.py
  test/new_test_framework/utils/streamUtil.py
  tests/script/tmp/test_subquery_basic.py
Labels: team engine

#31209 New test framework docs
  .github/scripts/generate_case_md.py
  .github/workflows/deploy-case-docs.yml
  test/docs/stylesheets/extra.css
  test/mkdocs.yml
  test/templates/python/material/function.html.jinja
Labels: team platform

#31216 test: adding continue running method
  test/tools/gdb.sh
  test/tools/streamlist.txt
  test/tools/tjenkins
Labels: team engine

#31180 fix: naming rule with quotation char
  include/libs/parser/parser.h
  source/libs/command/src/command.c
  source/libs/parser/inc/parToken.h
  source/libs/parser/inc/parUtil.h
  source/libs/parser/src/parAstCreater.c
  source/libs/parser/src/parAstParser.c
  source/libs/parser/src/parTokenizer.c
  tests/system-test/2-query/tbname.py
Labels: team engine

#31212 enh: add memory usage monitor for vnode
  docs/en/14-reference/03-taos-sql/22-meta.md
  docs/zh/14-reference/03-taos-sql/22-meta.md
  include/common/tmsg.h
  source/common/src/msg/tmsg.c
  source/common/src/systable.c
  source/dnode/mnode/impl/inc/mndDef.h
  source/dnode/mnode/impl/src/mndDnode.c
  source/dnode/mnode/impl/src/mndVgroup.c
  source/dnode/vnode/src/vnd/vnodeQuery.c
  tests/system-test/0-others/information_schema.py
Labels: team engine

#31224 feat: [TS-6100] Parse create stream sql: Support _tprev_ts/_tnext_ts/…
  include/common/streamMsg.h
  include/libs/function/functionMgt.h
  source/libs/function/src/builtins.c
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parTokenizer.c
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31227 TD-35056
  test/README.md
  test/conftest.py
  test/new_test_framework/utils/before_test.py
Labels: team platform

#31228 Feat/ts 6100 smj
  source/libs/parser/src/parTranslater.c
  test/cases/13-StreamProcessing/07-SubQuery/test_create_stream_syntax.py
Labels: team engine

#31229 TD-35056 keep env alive
  test/README.md
  test/conftest.py
Labels: team platform

#31231 feat: [TS-6100] Parse create stream sql: Get trigger table's meta dur…
  source/libs/parser/src/parAstParser.c
  test/cases/13-StreamProcessing/07-SubQuery/test_create_stream_syntax.py
Labels: team engine

#31234 feat: [TS-6100] Parse create stream sql: Sql gen refacotr.
  .gitignore
  source/dnode/vnode/src/vnd/vnodeApi.c
  test/cases/13-StreamProcessing/07-SubQuery/test_create_stream_syntax.py
Labels: team engine

#31217 fix: add duplicate tolerance
  source/dnode/vnode/src/tsdb/tsdbIter.c
  source/dnode/vnode/src/tsdb/tsdbMergeTree.c
Labels: team engine

#31226 fix(stmt): wrong sql type core
  source/client/inc/clientStmt2.h
  source/client/src/clientStmt2.c
  source/client/test/stmt2Test.cpp
  tests/army/tools/benchmark/basic/json/TD-32913-2.json
Labels: team engine

#31244 feat: [TS-6100] Parse create stream sql: Sql gen refacotr.
  test/cases/13-StreamProcessing/02-Stream/test_create_stream_syntax.py
Labels: team engine

#31225 fix: avoid using : in consumer group
  docs/en/07-develop/07-tmq.md
  docs/zh/07-develop/07-tmq.md
  source/client/src/clientTmq.c
  source/dnode/mnode/impl/src/mndSubscribe.c
Labels: team engine

#31232 feat: [TD-29445] add error handling for offline vnode state
  include/util/taoserror.h
  source/dnode/mgmt/mgmt_vnode/src/vmInt.c
  source/dnode/mnode/impl/src/mndDnode.c
  source/util/src/terror.c
  tests/army/whole/checkErrorCode.py
Labels: team engine

#30265 enh: [TS-6089] trans-parallel
  docs/en/14-reference/01-components/01-taosd.md
  docs/zh/14-reference/01-components/01-taosd.md
  include/common/tglobal.h
  source/common/src/tglobal.c
  source/dnode/mnode/impl/inc/mndDef.h
  source/dnode/mnode/impl/inc/mndTrans.h
  source/dnode/mnode/impl/src/mndDb.c
  source/dnode/mnode/impl/src/mndDnode.c
  source/dnode/mnode/impl/src/mndMnode.c
  source/dnode/mnode/impl/src/mndQnode.c
  source/dnode/mnode/impl/src/mndSnode.c
  source/dnode/mnode/impl/src/mndStb.c
  source/dnode/mnode/impl/src/mndSync.c
  source/dnode/mnode/impl/src/mndTrans.c
  source/dnode/mnode/impl/src/mndVgroup.c
  tests/script/tsim/show/basic.sim
  tests/script/tsim/valgrind/checkError1.sim
  tests/system-test/3-enterprise/restore/restoreBasic.py
Labels: pending, team engine

#31247 doc: Update index.md
  docs/zh/06-advanced/06-TDgpt/05-forecast/index.md
Labels: team engine

#31249 add grafana windows installation
  docs/en/10-third-party/03-visual/01-grafana.md
  docs/zh/10-third-party/03-visual/01-grafana.mdx
Labels: team tools

#31252 feat: [TS-6100] Parse create stream sql: Sql gen refacotr.
  .gitignore
  include/common/streamMsg.h
  include/libs/nodes/cmdnodes.h
  source/libs/parser/src/parAstCreater.c
  source/libs/parser/src/parAstParser.c
  source/libs/parser/src/parTranslater.c
  test/cases/13-StreamProcessing/02-Stream/test_create_stream_syntax.py
Labels: team engine

#31254 feat: [TS-6100] Parse create stream sql: Sql gen refactor and fix bugs.
  source/libs/parser/src/parTranslater.c
  test/cases/13-StreamProcessing/02-Stream/test_create_stream_syntax.py
Labels: team engine

#31246 fix(stmt2):defined col bind in interlace mode
  source/client/test/stmt2Test.cpp
  source/common/src/tdataformat.c
Labels: team engine

#31257 enh(stmt2):add interlace defined col insert
  source/client/test/stmt2Test.cpp
  source/common/src/tdataformat.c
Labels: team engine
