Repository taosdata/TDengine, pull requests merged in 2025-08, with the labels that each got.

#32421 docs: escape_character parameter in document classification error
  docs/en/14-reference/02-tools/10-taosbenchmark.md
  docs/zh/14-reference/02-tools/10-taosbenchmark.md
  tools/taos-tools/src/benchData.c
Labels: team tools

#32389 merge: from 3.3.6 to main branch
  source/common/src/systable.c
  source/dnode/mnode/impl/src/mndStb.c
  source/libs/executor/src/sysscanoperator.c
  source/libs/parser/src/parTranslater.c
  test/cases/05-VirtualTables/ans/test_vtable_meta.ans
  test/cases/05-VirtualTables/in/test_vtable_meta.in
  test/cases/07-DataQuerying/08-SubQuery/test_last_row.py
  test/cases/uncatalog/system-test/2-query/test_odbc.py
  test/ci/cases.task
  tests/army/vtable/ans/test_vtable_meta.ans
Labels: team engine

#32393 docs: update WebSocket connection API support status and usage restrictions
  docs/en/14-reference/05-connector/10-cpp.md
  docs/zh/14-reference/05-connector/10-cpp.mdx
Labels: team tools

#32430 fix: enhance removal logic to check for non-empty install directory before deletion
  packaging/tools/remove.sh
Labels: team platform

#32423 fix: update dnode state from offline to online
  source/dnode/mnode/impl/src/mndDnode.c
Labels: team engine

#32424 fix: update dnode state from offline to online
  source/dnode/mnode/impl/src/mndDnode.c
Labels: team engine

#32434 doc: simplify get started for docker
  docs/zh/04-get-started/01-docker.mdx
Labels: team platform

#32435 fix: enhance removal script to handle empty service names and add directory cleanup
  packaging/tools/remove.sh
Labels: team platform

#32433 docs(taosx): update Data-In tasks name to TDengine Subscription and T…
  docs/en/06-advanced/05-data-in/01-migrate.md
  docs/en/06-advanced/05-data-in/02-tmq.md
  docs/en/assets/tdengine-2-01.png
  docs/en/assets/tdengine-2-02.png
  docs/en/assets/tdengine-3-04.png
  docs/en/assets/tdengine-3-05.png
  docs/zh/06-advanced/05-data-in/01-migrate.md
  docs/zh/06-advanced/05-data-in/02-tmq.md
  docs/zh/06-advanced/05-data-in/migrate-step1.png
  docs/zh/06-advanced/05-data-in/migrate-step2.png
  docs/zh/06-advanced/05-data-in/tmq-step1.png
  docs/zh/06-advanced/05-data-in/tmq-step2.png
Labels: team tools

#32439 merge: from 3.3.6 to main branch
  source/dnode/vnode/src/meta/metaOpen.c
Labels: team engine

#32405 fix: [TD-37190] Disable ignore_nodata_trigger when window type is not interval/sliding or period.
  source/libs/parser/src/parTranslater.c
Labels: team engine

#32453 feat(stmt):add more cases
  include/libs/parser/parser.h
  source/client/inc/clientStmt.h
  source/client/src/clientStmt.c
  source/client/test/stmtTest.cpp
  source/libs/parser/src/parInsertStmt.c
  source/libs/parser/src/parser.c
Labels: team engine

#32448 fix(client) select json on tags with escape
  source/client/src/clientImpl.c
  source/libs/parser/src/parTokenizer.c
  source/libs/parser/src/parUtil.c
  test/cases/07-DataQuerying/17-Tags/test_select_with_json_tags.py
  test/ci/cases.task
Labels: team engine

#32438 fix(tmq): [td-37265]poll error if insering some cols with stmt
  source/dnode/vnode/src/tq/tq.c
  source/dnode/vnode/src/tq/tqRead.c
  test/cases/12-DataSubscription/02-Native/test_tmq_force_drop_topic.py
  tests/parallel_test/cases.task
  tests/system-test/7-tmq/tmq_td37265.py
  utils/test/c/CMakeLists.txt
  utils/test/c/tmq_td37265.c
Labels: team engine

#32444 feat: add enum compatibility check in CI workflow
  .github/scripts/check_enum_append_only.py
  .github/workflows/tdengine-check-enum.yml
Labels: team engine

#32480 enh: [TS-7009] Modify snode error msg
  source/util/src/terror.c
Labels: team engine

#32487 merge: from 3.3.6 to main
  source/client/src/clientImpl.c
  source/dnode/vnode/src/tq/tq.c
  source/dnode/vnode/src/tq/tqRead.c
  source/libs/executor/src/sysscanoperator.c
  source/libs/parser/src/parTokenizer.c
  source/libs/parser/src/parUtil.c
  test/cases/07-DataQuerying/17-Tags/test_select_with_json_tags.py
  test/cases/12-DataSubscription/02-Native/test_tmq_force_drop_topic.py
  test/ci/cases.task
  tests/system-test/7-tmq/tmq_td37265.py
  utils/test/c/CMakeLists.txt
  utils/test/c/tmq_td37265.c
Labels: team engine

#32500 update default retry parameter
  docs/en/14-reference/01-components/01-taosd.md
  docs/zh/14-reference/01-components/01-taosd.md
  source/common/src/tglobal.c
Labels: team engine

#32496 docs(driver-go): add timezone parameter descriptions
  docs/en/07-develop/01-connect.md
  docs/en/07-develop/07-tmq.md
  docs/en/14-reference/05-connector/20-go.md
  docs/zh/07-develop/01-connect/index.md
  docs/zh/07-develop/07-tmq.md
  docs/zh/14-reference/05-connector/20-go.mdx
Labels: team tools

#32512 case: test_idmp_meters.py stream8 fixed(main)
  test/cases/13-StreamProcessing/20-UseCase/test_idmp_meters.py
Labels: team tools

#32521 docs(taosX): support data import from orc file
  docs/zh/14-reference/01-components/04-taosx.md
Labels: team tools

#32523 fix: case not passed queryMain.py and taosShellError.py(main)
  test/cases/uncatalog/army/tools/benchmark/basic/test_query_main.py
  test/cases/uncatalog/army/tools/benchmark/basic/test_website_case.py
  test/cases/uncatalog/system-test/0-others/test_taos_shell_error.py
Labels: team tools

#32528 fix: case not passed queryMain.py and taosShellError.py(3.3.6)
  tests/army/tools/benchmark/basic/queryMain.py
  tests/army/tools/benchmark/basic/websiteCase.py
  tests/system-test/0-others/taosShellError.py
Labels: team tools

#32526 fix: merge sort in column insert mode
  source/common/src/tdataformat.c
  test/cases/uncatalog/system-test/1-insert/test_test_stmt_muti_insert_query.py
Labels: team engine

#32502 fix: merge sort in column insert mode
  source/common/src/tdataformat.c
  test/cases/uncatalog/system-test/1-insert/test_test_stmt_muti_insert_query.py
Labels: team engine

#32497 docs: enhance timezone settings documentation for C# driver
  docs/en/14-reference/05-connector/40-csharp.md
  docs/zh/14-reference/05-connector/40-csharp.mdx
Labels: team tools

#32483 enh[ts-6869]: support using file system as shared storage
  docs/en/04-get-started/06-enterprise.md
  docs/en/08-operation/12-multi.md
  docs/zh/08-operation/12-multi.md
  source/libs/tss/test/tssTest.cpp
Labels: team engine

#32538 enh[ts-6869]: support using file system as shared storage (for main branch)
  docs/en/04-get-started/06-enterprise.md
  docs/en/08-operation/12-multi.md
  docs/zh/08-operation/12-multi.md
  source/libs/tss/test/tssTest.cpp
Labels: team engine

#32507 Fix/td 37280/bool value and other
  source/client/src/clientMain.c
  source/dnode/mnode/impl/src/mndStream.c
  source/libs/function/src/udfd.c
  source/libs/new-stream/src/dataSinkMgr.c
  source/libs/new-stream/src/streamRunner.c
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_concat.py
Labels: team engine

#32548 Opti/td 37251
  include/common/streamMsg.h
  include/common/tmsg.h
  include/libs/executor/executor.h
  include/libs/new-stream/streamReader.h
  include/util/taoserror.h
  source/common/src/msg/streamMsg.c
  source/common/src/msg/tmsg.c
  source/common/src/tglobal.c
  source/dnode/vnode/src/sma/smaRollup.c
  source/dnode/vnode/src/tq/tqMeta.c
  source/dnode/vnode/src/tq/tqRead.c
  source/dnode/vnode/src/tsdb/tsdbRead2.c
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/dnode/vnode/src/vnd/vnodeSvr.c
  source/libs/executor/src/executor.c
  source/libs/new-stream/inc/streamTriggerMerger.h
  source/libs/new-stream/src/streamReader.c
  source/libs/new-stream/src/streamTriggerTask.c
  source/util/src/terror.c
  test/cases/13-StreamProcessing/03-TriggerMode/test_td37251.py
  test/cases/uncatalog/army/whole/test_check_error_code.py
Labels: team engine

#32547 refactor: get started for installer and docker
  docs/zh/04-get-started/01-docker.mdx
  docs/zh/04-get-started/03-package.mdx
  docs/zh/04-get-started/_get_started.mdx
  docs/zh/04-get-started/explorer.png
  docs/zh/04-get-started/grafana.png
Labels: team platform

#32546 feat(stream): opti thread mode of stream reader
  source/common/src/tglobal.c
  source/dnode/mgmt/mgmt_vnode/inc/vmInt.h
  source/dnode/mgmt/mgmt_vnode/src/vmWorker.c
Labels: team engine

#32565 docs(jdbc): jdbc release 3.7.2
  docs/en/14-reference/05-connector/14-java.md
  docs/examples/JDBC/JDBCDemo/pom.xml
  docs/examples/JDBC/SpringJdbcTemplate/pom.xml
  docs/examples/JDBC/SpringJdbcTemplate/src/main/resources/applicationContext.xml
  docs/examples/JDBC/connectionPools/pom.xml
  docs/examples/JDBC/consumer-demo/pom.xml
  docs/examples/JDBC/highvolume/pom.xml
  docs/examples/JDBC/mybatisplus-demo/pom.xml
  docs/examples/JDBC/springbootdemo/pom.xml
  docs/examples/JDBC/taosdemo/pom.xml
  docs/examples/java/pom.xml
  docs/zh/07-develop/01-connect/index.md
  docs/zh/14-reference/05-connector/14-java.mdx
Labels: team tools

#32537 fix(stream): fix mem leak in trigger history context
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#32559 fix: check output tbname calc result
  include/util/taoserror.h
  source/libs/executor/src/executor.c
  source/libs/new-stream/src/streamRunner.c
  source/util/src/terror.c
  test/cases/13-StreamProcessing/20-UseCase/test_three_gorges_case5.py
Labels: team engine

#32463 fix: merge external win
  source/libs/executor/src/externalwindowoperator.c
Labels: team engine

#32556 add retry for TSDB_CODE_SYNC_WRITE_STALL
  source/client/src/clientEnv.c
  source/libs/transport/src/transCli.c
Labels: team engine

#32533 support stmt2 test cases
  test/cases/demo/test_stmt2.py
  test/conftest.py
  test/new_test_framework/utils/__init__.py
  test/new_test_framework/utils/stmt2.py
Labels: team platform

#32570 doc:alter faq md
  docs/en/27-train-faq/index.md
  docs/zh/27-train-faq/01-faq.md
Labels: team platform

#32536 fix(ctg): add timeout for catlog rpc request
  source/libs/catalog/inc/catalogInt.h
  source/libs/catalog/src/ctgRemote.c
  source/libs/catalog/test/catalogTests.cpp
  source/libs/transport/src/transCli.c
Labels: team engine

#32571 fix: resolve the issue of taosdump being unable to filter microsecond…
  tests/army/tools/benchmark/basic/queryMain.py
  tools/taos-tools/inc/dump.h
Labels: team tools

#32574 fix(stmt): disable stmt retries
  source/client/src/clientImpl.c
  source/client/src/clientMain.c
  source/client/src/clientStmt2.c
  source/client/test/stmt2Test.cpp
Labels: team engine

#32590 docs: update python ws doc
  docs/en/14-reference/05-connector/30-python.md
  docs/zh/14-reference/05-connector/30-python.mdx
Labels: team tools

#32588 fix: crash when using only notify stream
  source/libs/new-stream/src/streamRunner.c
Labels: team engine

#32593 update test frame parameter
  tests/pytest/util/dnodes.py
Labels: team engine

#32597 fix: add retention policy to database creation in test_distinct.py
  test/cases/07-DataQuerying/13-Distinct/test_distinct.py
Labels: team platform

#32610 merge: from 3.3.6 to main branch
  source/client/src/clientStmt2.c
  source/client/test/connectOptionsTest.cpp
  source/client/test/stmt2Test.cpp
  source/libs/catalog/inc/catalogInt.h
  source/libs/catalog/src/ctgRemote.c
  source/libs/catalog/test/catalogTests.cpp
  source/libs/executor/src/sysscanoperator.c
  source/libs/nodes/src/nodesCloneFuncs.c
  source/libs/parser/src/parAstCreater.c
  source/libs/transport/src/transCli.c
  test/cases/07-DataQuerying/13-Distinct/test_distinct.py
  test/cases/uncatalog/system-test/1-insert/test_test_stmt_muti_insert_query.py
Labels: team engine

#32626 docs: update catalog
  docs/zh/14-reference/03-taos-sql/01-datatype.md
  docs/zh/14-reference/03-taos-sql/10-insert.md
  docs/zh/14-reference/03-taos-sql/11-delete-data.md
  docs/zh/14-reference/03-taos-sql/12-compress.md
  docs/zh/14-reference/03-taos-sql/17-json.md
  docs/zh/14-reference/03-taos-sql/20-select.md
  docs/zh/14-reference/03-taos-sql/21-operators.md
  docs/zh/14-reference/03-taos-sql/22-function.md
  docs/zh/14-reference/03-taos-sql/23-udf.md
  docs/zh/14-reference/03-taos-sql/24-distinguished.md
  docs/zh/14-reference/03-taos-sql/25-join.md
  docs/zh/14-reference/03-taos-sql/26-tag-index.md
  docs/zh/14-reference/03-taos-sql/27-view.md
  docs/zh/14-reference/03-taos-sql/28-escape.md
  docs/zh/14-reference/03-taos-sql/40-tmq.md
  docs/zh/14-reference/03-taos-sql/41-stream.md
  docs/zh/14-reference/03-taos-sql/42-tsma.md
  docs/zh/14-reference/03-taos-sql/50-limit.md
  docs/zh/14-reference/03-taos-sql/51-keywords.md
  docs/zh/14-reference/03-taos-sql/60-meta.md
  docs/zh/14-reference/03-taos-sql/61-perf.md
  docs/zh/14-reference/03-taos-sql/62-show.md
  docs/zh/14-reference/03-taos-sql/70-user.md
  docs/zh/14-reference/03-taos-sql/71-grant.md
  docs/zh/14-reference/03-taos-sql/80-node.md
  docs/zh/14-reference/03-taos-sql/81-recovery.md
  docs/zh/14-reference/03-taos-sql/82-mount.md
  docs/zh/14-reference/03-taos-sql/90-changes.md
Labels: team engine

#32632 fix: stmt errors
  source/client/src/clientImpl.c
  source/client/test/stmt2Test.cpp
Labels: team engine

#32581 enh[TD-37462]: improve error messages for CREATE DATABASE operations
  docs/en/14-reference/09-error-code.md
  docs/zh/14-reference/09-error-code.md
  include/util/taoserror.h
  source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
  source/util/src/terror.c
Labels: team engine

#32634 fix: Commented out some test cases
  tests/parallel_test/cases.task
Labels: team platform

#32655 fix: semaphore wait count mismatch
  source/util/src/tqueue.c
Labels: team engine

#32649 fix: fix keeper operations client_address length
  tools/keeper/api/audit.go
  tools/keeper/api/audit_test.go
Labels: team tools

#32627 fix[TD-37161]: check createdb conflict
  source/dnode/mnode/impl/src/mndDb.c
  test/ci/cases.task
Labels: team engine

#32601 fix(scheduler): use task retry when meet error on vnode leader election
  source/libs/scheduler/inc/schInt.h
  source/libs/scheduler/src/schRemote.c
  test/cases/07-DataQuerying/99-Others/test_select_during_leader_election.py
  test/ci/cases.task
Labels: team engine

#32673 docs: refactor function
  docs/zh/14-reference/03-taos-sql/22-function.md
Labels: team engine

#32658 fix(gpt): fix overwrite of error code.
  source/libs/executor/src/forecastoperator.c
Labels: team engine

#32633 feat[TD-37210]: trigger scan plan optimize
  include/common/streamMsg.h
  include/libs/nodes/cmdnodes.h
  include/libs/nodes/querynodes.h
  include/libs/planner/planner.h
  source/common/src/msg/streamMsg.c
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/new-stream/src/streamReader.c
  source/libs/new-stream/src/streamRunner.c
  source/libs/new-stream/src/streamTriggerTask.c
  source/libs/nodes/src/nodesTraverseFuncs.c
  source/libs/parser/src/parTranslater.c
  source/libs/parser/test/parStreamTest.cpp
  source/libs/planner/src/planLogicCreater.c
  tests/army/storage/ss/ssAzure.py
Labels: team engine

#32667 merge: from 3.3.6 to main branch
  docs/en/14-reference/09-error-code.md
  docs/zh/14-reference/09-error-code.md
  include/util/taoserror.h
  source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
  source/libs/scheduler/inc/schInt.h
  source/libs/scheduler/src/schRemote.c
  source/util/src/terror.c
  source/util/src/tqueue.c
  test/cases/04-SuperTables/04-Query/test_stable_query_during_leader_election.py
  test/cases/05-VirtualTables/test_vtable_query_cross_db.py
  test/cases/05-VirtualTables/test_vtable_query_cross_db_stb_group.py
  test/cases/05-VirtualTables/test_vtable_query_cross_db_stb_project.py
  test/cases/05-VirtualTables/test_vtable_query_cross_db_stb_window.py
  test/ci/cases.task
  tests/coverage/old_covtests.task
  tools/keeper/api/audit.go
  tools/keeper/api/audit_test.go
Labels: team engine

#32676 enh[TD-3757]: only block createdb for normal user
  source/dnode/mnode/impl/src/mndDb.c
Labels: team engine

#32468 enh[TS-6867]: support for REDISTRIBUTE command on dual-replica databases
  source/dnode/mnode/impl/src/mndVgroup.c
Labels: team engine

#32456 fix(agg/stddev): variance overflow
  source/libs/function/src/builtinsimpl.c
  test/cases/05-VirtualTables/ans/test_vctable_select_test_function.ans
  test/cases/05-VirtualTables/ans/test_vtable_select_test_function.ans
  test/cases/uncatalog/army/query/function/ans/stddev.csv
  test/cases/uncatalog/army/query/function/ans/varpop.csv
Labels: team engine

#32545 feat: support for the date function
  docs/en/14-reference/03-taos-sql/10-function.md
  docs/zh/14-reference/03-taos-sql/10-function.md
  include/libs/function/functionMgt.h
  include/libs/scalar/scalar.h
  source/libs/function/src/builtins.c
  source/libs/scalar/src/sclfunc.c
  test/cases/10-Functions/ans/avg.csv
  test/cases/10-Functions/ans/date.csv
  test/cases/10-Functions/ans/timediff.csv
  test/cases/10-Functions/in/date.in
  test/cases/10-Functions/test_function.py
  test/ci/cases.task
Labels: team engine

#32670 fix: Do not generate external window when stream query has UNIQUE/TAIL/FORECAST.
  source/libs/planner/src/planLogicCreater.c
Labels: team engine

#32671 fix: twrowsnum calc error
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#32690 enh: clarify the return value format of the date function
  docs/en/14-reference/03-taos-sql/10-function.md
  docs/zh/14-reference/03-taos-sql/10-function.md
Labels: team engine

#32576 enh[TD-37432]add config item syncApplyQueueSize (for 3.3.6)
  docs/en/14-reference/01-components/01-taosd.md
  docs/zh/14-reference/01-components/01-taosd.md
  include/common/tglobal.h
  include/util/tdef.h
  source/common/src/tglobal.c
  source/libs/sync/src/syncPipeline.c
  test/cases/22-Show/test_show_basic.py
  test/cases/50-Others/01-Valgrind/test_valgrind_checkerror1.py
Labels: team engine

#32562 enh[TD-37432]: add variable 'syncApplyQueueSize'
  docs/en/14-reference/01-components/01-taosd.md
  docs/zh/14-reference/01-components/01-taosd.md
  include/common/tglobal.h
  include/util/tdef.h
  source/common/src/tglobal.c
  source/libs/sync/src/syncPipeline.c
Labels: team engine

#32701 merge: 3.3.6 to main branch
  docs/en/14-reference/01-components/01-taosd.md
  docs/zh/14-reference/01-components/01-taosd.md
  include/common/tglobal.h
  include/util/tdef.h
  source/common/src/tglobal.c
  source/libs/sync/src/syncPipeline.c
Labels: team engine

#32680 fix(stmt):dbeaver delete sql core in stmt get_fileds
  include/libs/parser/parser.h
  source/client/inc/clientStmt2.h
  source/client/src/clientMain.c
  source/client/src/clientStmt2.c
  source/client/test/stmt2Test.cpp
  source/libs/parser/src/parser.c
Labels: team engine

#32685 enh(stmt): set tbname support all characters
  include/libs/parser/parser.h
  source/client/src/clientStmt2.c
  source/client/test/stmt2Test.cpp
  source/libs/parser/src/parInsertSml.c
  source/libs/parser/src/parInsertUtil.c
Labels: team engine

#32703 enh(stmt): set tbname support all characters
  include/libs/parser/parser.h
  source/client/src/clientStmt2.c
  source/client/test/stmt2Test.cpp
  source/libs/parser/src/parInsertSml.c
  source/libs/parser/src/parInsertUtil.c
Labels: team engine

#32662 docs : update for dbeaver 3.3.6 branch
  docs/en/10-third-party/07-tool/01-dbeaver.md
  docs/en/assets/dbeaver-01.webp
  docs/en/assets/dbeaver-02.webp
  docs/en/assets/dbeaver-03.webp
  docs/en/assets/dbeaver-04.webp
  docs/en/assets/dbeaver-05.webp
  docs/zh/10-third-party/07-tool/01-dbeaver.md
  docs/zh/10-third-party/07-tool/dbeaver/dbeaver-browse-data-zh.webp
  docs/zh/10-third-party/07-tool/dbeaver/dbeaver-config-tdengine-zh.webp
  docs/zh/10-third-party/07-tool/dbeaver/dbeaver-connect-tdengine-test-zh.webp
  docs/zh/10-third-party/07-tool/dbeaver/dbeaver-connect-tdengine-zh.webp
  docs/zh/10-third-party/07-tool/dbeaver/dbeaver-sql-execution-zh.webp
Labels: team tools

#32706 fix: add bss encode test compress rate tools
  tools/auto/testBss/json/gencsv.sh
  tools/auto/testBss/json/generate.json
  tools/auto/testBss/json/query.json
  tools/auto/testBss/json/template.json
  tools/auto/testBss/result.txt
  tools/auto/testBss/run.sh
  tools/auto/testBss/testBss.py
Labels: team tools

#32707 fix(tmq): [tTD-37592]double free if subplan string decode error
  source/dnode/mnode/impl/src/mndSubscribe.c
Labels: team engine

#32728 Fix win cases
  test/cases/uncatalog/army/tools/taosdump/native/test_taosdump_commandline.py
  test/cases/uncatalog/army/tools/taosdump/native/test_taosdump_test_inspect.py
  test/ci/win_ignore_cases
Labels: team platform

#32719 fix: [TD-37537] Fix deadlock cause by incorrect vtable meta response.
  source/dnode/vnode/src/meta/metaTable.c
  source/dnode/vnode/src/meta/metaTable2.c
  test/cases/05-VirtualTables/test_vtable_auth_alter_drop.py
  test/cases/05-VirtualTables/test_vtable_auth_alter_drop_child.py
  test/cases/05-VirtualTables/test_vtable_auth_create.py
  test/cases/05-VirtualTables/test_vtable_auth_select.py
  tests/army/vtable/test_vtable_auth_alter_drop.py
  tests/army/vtable/test_vtable_auth_alter_drop_child.py
  tests/army/vtable/test_vtable_auth_create.py
  tests/army/vtable/test_vtable_auth_select.py
  tests/parallel_test/cases.task
Labels: team engine

#32724 enh(stmt2): interlace bind return error
  source/client/src/clientStmt2.c
Labels: team engine

#32725 test: remove unused files
  test/cases/22-Functions/02-Aggregate/test_agg_special_elapsed.py
  test/ci/cases.task
  test/tools/tmux.conf
  tests/script/api/test.sh
  tests/script/log
  tests/script/runAllSimCases.sh
  tests/script/sh/bit_and.c
  tests/script/sh/cfg.bat
  tests/script/sh/cfg.sh
  tests/script/sh/checkAsan.sh
  tests/script/sh/checkValgrind.bat
  tests/script/sh/checkValgrind.sh
  tests/script/sh/clear.sh
  tests/script/sh/compile_udf.sh
  tests/script/sh/copy_udf.bat
  tests/script/sh/copy_udf.sh
  tests/script/sh/deploy.bat
  tests/script/sh/deploy.sh
  tests/script/sh/dockerbuilder/addDnodeToCluster.sh
  tests/script/sh/dockerbuilder/addFqdnToHost.sh
  tests/script/sh/dockerbuilder/clientCfg/taos.cfg
  tests/script/sh/dockerbuilder/createComposeYml.sh
  tests/script/sh/dockerbuilder/createDnodeStorage.sh
  tests/script/sh/dockerbuilder/tdserver/Dockerfile
  tests/script/sh/exec-default.sh
  tests/script/sh/exec-no-random-fail.sh
  tests/script/sh/exec-random-fail.sh
  tests/script/sh/exec.bat
  tests/script/sh/exec.sh
  tests/script/sh/exec_tarbitrator.sh
  tests/script/sh/extract_avg.c
  tests/script/sh/gpd.c
  tests/script/sh/ip.sh
  tests/script/sh/l2norm.c
  tests/script/sh/massiveTable/cleanCluster.sh
  tests/script/sh/massiveTable/compileVersion.sh
  tests/script/sh/massiveTable/deployCluster.sh
  tests/script/sh/massiveTable/setupDnodes.sh
  tests/script/sh/max_vol.c
  tests/script/sh/mv_old_data.sh
  tests/script/sh/prepare_pyudf.sh
  tests/script/sh/prepare_udf.sh
  tests/script/sh/pybitand.py
  tests/script/sh/pycumsum.py
  tests/script/sh/pyl2norm.py
  tests/script/sh/scalar_demo.lua
  tests/script/sh/sigint_stop_dnodes.sh
  tests/script/sh/stop_dnodes.bat
  tests/script/sh/stop_dnodes.sh
  tests/script/sim.sql
  tests/script/test-all.bat
  tests/script/test-win.bat
  tests/script/test.sh
  tests/script/win-test-file
  tests/script/wtest.bat
Labels: team engine

#32692 fix: ouput nodata window
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#32718 fix(test): remove unnecessary call to sxny_data2 in test_three_gorges_second_case18
  test/cases/13-StreamProcessing/20-UseCase/test_three_gorges_second_case18.py
Labels: team platform

#32735 fix(docs): update UDF examples to correct file paths in documentation
  docs/en/07-develop/09-udf.md
  docs/zh/07-develop/09-udf.md
  test/cases/25-UDFs/sh/extract_avg.c
  test/cases/25-UDFs/sh/max_vol.c
Labels: team platform

#32708 fix: add taosBenchmark windows support params
  tools/taos-tools/src/benchSys.c
Labels: team tools

#32746 merge: from 3.3.6 to main branch
  source/dnode/vnode/src/meta/metaTable.c
  source/dnode/vnode/src/meta/metaTable2.c
  source/libs/parser/src/parTranslater.c
  test/cases/05-VirtualTables/test_vtable_auth_alter_normaltable.py
  test/cases/05-VirtualTables/test_vtable_auth_alter_subtable.py
  test/cases/05-VirtualTables/test_vtable_auth_create.py
  test/cases/05-VirtualTables/test_vtable_auth_select.py
  test/ci/cases.task
  tests/army/vtable/test_vtable_auth_alter_drop.py
  tests/army/vtable/test_vtable_auth_alter_drop_child.py
  tests/army/vtable/test_vtable_auth_create.py
  tests/army/vtable/test_vtable_auth_select.py
  tests/parallel_test/cases_tdengine.task
Labels: team engine

#32721 enh: change float/double default encoding to byte_stream_split
  docs/en/14-reference/03-taos-sql/32-compress.md
  docs/zh/14-reference/03-taos-sql/12-compress.md
  source/common/src/tcol.c
  test/cases/uncatalog/army/create/test_create_stb_keep.py
  utils/test/c/tmq_taosx_ci.c
Labels: team engine

#32738 docs: update driver-go version history to include support for connection-level time zone settings
  docs/en/14-reference/05-connector/20-go.md
  docs/zh/14-reference/05-connector/20-go.mdx
Labels: team tools

#32681 enh: trigger scan tags optimize
  source/libs/parser/src/parTranslater.c
Labels: team engine

#32635 fix: [TD-37529] Sliding offset cannot be used with interval in trigge…
  docs/en/14-reference/09-error-code.md
  docs/zh/14-reference/09-error-code.md
  include/util/taoserror.h
  source/libs/parser/src/parTranslater.c
  source/libs/parser/src/parUtil.c
  source/libs/parser/test/parStreamTest.cpp
  source/util/src/terror.c
  test/cases/13-StreamProcessing/08-Recalc/test_recalc_watermark.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_basic2.py
Labels: team engine

#32752 add retry to sync error
  source/client/src/clientEnv.c
Labels: team engine

#32759 feat: add logging function and installation completion messages to install script
  packaging/tools/install.sh
Labels: team platform

#32758 fix: modify the prompt language of the taos-shell
  docs/en/08-operation/03-deployment/03-kubernetes.md
  docs/en/27-train-faq/03-password.md
  include/util/cus_name.h
  test/cases/uncatalog/army/cmdline/test_taos_cli.py
  test/cases/uncatalog/army/query/function/generate_answer.sh
  test/new_test_framework/utils/common.py
  tests/army/frame/common.py
  tools/shell/inc/shellInt.h
  tools/shell/src/shellArguments.c
  tools/shell/src/shellEngine.c
  tools/shell/src/shellUtil.c
  tools/shell/test/shellTest.cpp
Labels: team tools

#32761 fix(query): wait for a while before trying next endpoint for tasks.
  source/client/src/clientSml.c
  source/libs/catalog/src/ctgCache.c
  source/libs/scheduler/inc/schInt.h
  source/libs/scheduler/src/schJob.c
  source/libs/scheduler/src/schRemote.c
  source/libs/scheduler/src/schTask.c
  source/libs/scheduler/src/schUtil.c
  source/libs/scheduler/test/schedulerTests.cpp
Labels: team engine

#32766 merge: from main to 3.0 branch
  docs/en/04-get-started/06-enterprise.md
  docs/en/07-develop/01-connect.md
  docs/en/08-operation/03-deployment/02-docker.md
  docs/en/08-operation/03-deployment/03-kubernetes.md
  docs/en/08-operation/12-multi.md
  docs/en/14-reference/05-connector/30-python.md
  docs/en/14-reference/05-connector/45-php.md
  docs/en/14-reference/05-connector/index.md
  docs/en/27-train-faq/03-password.md
  docs/examples/python/connect_websocket_examples.py
  docs/examples/python/connect_websocket_sqlalchemy_examples.py
  docs/examples/python/sqlalchemy_demo.py
  docs/zh/07-develop/01-connect/index.md
  docs/zh/08-operation/04-deployment.md
  docs/zh/08-operation/12-multi.md
  docs/zh/14-reference/05-connector/30-python.mdx
  docs/zh/14-reference/05-connector/45-php.mdx
  docs/zh/14-reference/05-connector/index.md
  include/common/tmsg.h
  include/common/tmsgdef.h
  include/util/cus_name.h
  packaging/tools/install.sh
  source/client/src/clientEnv.c
  source/common/src/msg/tmsg.c
  source/common/test/msgTypeTable.ini
  source/dnode/bnode/src/bnode.c
  source/dnode/mgmt/mgmt_mnode/src/mmHandle.c
  source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
  source/dnode/mgmt/node_mgmt/src/dmTransport.c
  source/dnode/mnode/impl/inc/mndDef.h
  source/dnode/mnode/impl/src/mndBnode.c
  source/dnode/mnode/impl/src/mndDb.c
  source/dnode/mnode/impl/src/mndMain.c
  source/dnode/mnode/impl/src/mndSsMigrate.c
  source/dnode/mnode/impl/src/mndVgroup.c
  source/dnode/vnode/src/inc/tsdbInt.h
  source/dnode/vnode/src/tsdb/tsdbMigrate.c
  source/dnode/vnode/src/tsdb/tsdbRetention.c
  source/dnode/vnode/src/vnd/vnodeRetention.c
  source/dnode/vnode/src/vnd/vnodeSvr.c
  source/libs/tss/src/s3.c
  test/cases/uncatalog/army/cmdline/test_taos_cli.py
  test/cases/uncatalog/army/query/function/generate_answer.sh
  test/ci/run_case.sh
  test/new_test_framework/utils/common.py
  test/pyproject.toml
  test/requirements.txt
  test/uv.lock
  tests/army/frame/common.py
  tests/ci/Dockerfile
  tests/ci/container_build_newmachine.sh
  tests/ci/dockerfile_ci
  tests/docs-examples-test/python.sh
  tests/parallel_test/run_case.sh
  tools/shell/inc/shellInt.h
  tools/shell/src/shellArguments.c
  tools/shell/src/shellEngine.c
  tools/shell/src/shellUtil.c
  tools/shell/test/shellTest.cpp
  tools/tdgpt/requirements.txt
Labels: team engine

#32745 fix: TD-37640-fix-monitor-case
  test/cases/uncatalog/system-test/0-others/test_taosd_monitor.py
Labels: team engine

#32765 fix:(stmt2) async query core
  source/client/src/clientStmt2.c
Labels: team engine

#32779 docs: update release note for 3.3.7.5 in office web
  cmake/version.cmake
  docs/en/28-releases/03-notes/3.3.7.5.md
  docs/zh/28-releases/03-notes/3.3.7.5.md
Labels: team platform

#32785 docs(taosX-Agent): add `keep_online` config param
  docs/zh/14-reference/01-components/05-taosx-agent.md
Labels: team tools

#32790 docs: update idmp info
  docs/zh/01-index.md
Labels: team engine

#32793 refactor: tdgpt image name and port number
  docs/en/06-advanced/06-tdgpt/02-tutorial.md
  docs/en/06-advanced/06-tdgpt/03-management.md
  docs/en/06-advanced/06-tdgpt/10-faq.md
  docs/zh/06-advanced/06-TDgpt/02-tutorial.md
  docs/zh/06-advanced/06-TDgpt/03-management.md
  docs/zh/06-advanced/06-TDgpt/11-faq.md
  docs/zh/08-operation/02-planning.md
  tools/tdgpt/README.md
Labels: team platform

#32796 docs: increase the usage restrictions of taosdump's lzma
  docs/en/14-reference/02-tools/09-taosdump.md
  docs/zh/14-reference/02-tools/09-taosdump.md
  tools/taos-tools/src/taosdump.c
Labels: team tools

#32802 Fix/ts 7142/rewrite null value2
  source/libs/scalar/inc/sclInt.h
  source/libs/scalar/src/filter.c
  source/libs/scalar/src/scalar.c
Labels: team engine

#32782 fix: resolve the issue of CI failure in taosdump Windows environment
  tools/taos-tools/inc/dump.h
  tools/taos-tools/src/taosdump.c
Labels: team tools

#31323 docs(taosx): update thread resource configuation
  docs/en/14-reference/01-components/04-taosx.md
  docs/zh/14-reference/01-components/04-taosx.md
Labels: team tools

#32800 fix(gpt): fix race-condition in preparing tmp files
  include/common/tanalytics.h
  source/common/src/tanalytics.c
  source/dnode/mnode/impl/src/mndAnode.c
  source/libs/executor/inc/querytask.h
  source/libs/executor/src/anomalywindowoperator.c
  source/libs/executor/src/executor.c
  source/libs/executor/src/forecastoperator.c
  source/libs/executor/src/querytask.c
Labels: team engine

#32801 fix(stream): send data by order of cids
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/new-stream/src/streamTriggerTask.c
  test/cases/41-StreamProcessing/20-UseCase/test_idmp_ts-7152.py
  test/ci/cases.task
Labels: team engine

#32816 merge: from 3.3.6 to main branch
  source/libs/scalar/inc/sclInt.h
  source/libs/scalar/src/filter.c
  source/libs/scalar/src/scalar.c
Labels: team engine

#32815 fix(gpt): fix race-condition in pareparing files for forecast.
  include/common/tanalytics.h
  source/common/src/tanalytics.c
  source/dnode/mnode/impl/src/mndAnode.c
  source/libs/executor/src/anomalywindowoperator.c
  source/libs/executor/src/forecastoperator.c
Labels: team engine

#32822 refactor: keep the download link for tsdb server enterprise editions only
  docs/zh/04-get-started/03-package.mdx
Labels: team platform
