Repository taosdata/TDengine, pull requests merged in 2025-04, with the labels that each got.

#30568 fix(s3): wrong condition where alter db ops s3_compact.
  source/dnode/mnode/impl/src/mndDb.c
  tests/army/alter/alter_db_option.py
  tests/parallel_test/cases.task
Labels: team engine

#30555 fix: [TD-34250] wrong-createdb
  source/common/src/msg/tmsg.c
  source/dnode/mnode/impl/src/mndUser.c
Labels: team engine

#30575 test: add workflow add-pr-labels [ci skip]
  .github/workflows/label-pr-by-team.yml
Labels: team platform

#30550 ci: update doc-build workflow to add option to check build chinese or…
  .github/workflows/tdengine-build.yml
  .github/workflows/tdengine-doc-build.yml
  .github/workflows/tdengine-test.yml
Labels: team platform

#30551 ci: update doc-build workflow to add option to check build chinese or…
  .github/workflows/tdengine-doc-build.yml
Labels: team platform

#30581 ci: update doc build workflow to verify third party tool
  .github/workflows/tdengine-doc-build.yml
Labels: team platform

#30579 fix: update GitHub Actions workflow to trigger on main branch and specific condition
  .github/workflows/new-framework-test.yml
Labels: team platform

#30587 add workflow for main branch[ci skip]
  .github/workflows/label-pr-by-team.yml
Labels: team platform

#30577 refactor: adjust qid for connector log
  source/client/src/clientImpl.c
  source/client/src/clientMain.c
  source/dnode/mgmt/exe/dmMain.c
  tests/script/tmp/r1.sim
Labels: team engine

#30590 docs: add concurrency in tdengine-doc-build.yml
  .github/workflows/tdengine-doc-build.yml
Labels: team platform

#30589 feat: add workflow for spell checking TDengine documentation typos
  .github/workflows/tdengine-doc-build.yml
  docs/en/06-advanced/03-stream.md
  docs/en/06-advanced/06-tdgpt/05-forecast/03-holtwinters.md
  docs/en/06-advanced/06-tdgpt/06-anomaly-detection/index.md
  docs/en/06-advanced/06-tdgpt/09-dev/02-algo/02-forecast.md
  docs/en/06-advanced/06-tdgpt/09-dev/02-algo/index.md
  docs/en/08-operation/14-user.md
  docs/en/10-third-party/01-collection/flink.md
  docs/en/10-third-party/05-bi/03-powerbi.md
  docs/en/14-reference/03-taos-sql/02-database.md
  docs/en/14-reference/03-taos-sql/10-function.md
  docs/en/14-reference/03-taos-sql/24-show.md
  docs/en/14-reference/03-taos-sql/28-tsma.md
  docs/en/14-reference/05-connector/10-cpp.md
  docs/en/14-reference/05-connector/50-odbc.md
  docs/en/14-reference/09-error-code.md
  docs/en/28-releases/03-notes/3.3.4.3.md
  docs/en/28-releases/03-notes/3.3.5.0.md
  docs/en/28-releases/03-notes/3.3.5.2.md
  docs/en/28-releases/03-notes/3.3.5.8.md
  docs/en/28-releases/03-notes/3.3.6.0.md
  docs/typos.toml
Labels: team platform

#30520 fix(gpt): check for the number of rows for analysis
  docs/zh/06-advanced/06-TDgpt/09-dev/index.md
  include/common/tanalytics.h
  include/util/taoserror.h
  source/libs/executor/src/anomalywindowoperator.c
  source/libs/executor/src/forecastoperator.c
  source/libs/nodes/src/nodesUtilFuncs.c
  source/util/src/terror.c
  tests/script/tsim/analytics/basic0.sim
  tools/tdgpt/taosanalytics/algo/fc/holtwinters.py
Labels: team engine

#30597 fix: downgrade CMake version to 3.31.6
  .github/workflows/taoskeeper-build.yml
  .github/workflows/tdengine-build.yml
  .github/workflows/tdengine-release-build.yml
Labels: team tools

#30600 docs: TS-5927-add-reference
  docs/en/14-reference/03-taos-sql/25-user.md
  docs/zh/14-reference/03-taos-sql/25-user.md
Labels: team engine

#30586 fix: [TS-6094] Fix virtual table get wrong origin table's meta
  source/libs/parser/src/parTranslater.c
  tests/army/vtable/test_vtable_query_after_drop_origin_table.py
  tests/parallel_test/cases.task
Labels: team engine

#30580 enh: ts6195, support cols in stream
  include/common/tcommon.h
  source/libs/executor/src/streamtimewindowoperator.c
  source/libs/function/src/builtinsimpl.c
  source/libs/nodes/src/nodesCodeFuncs.c
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parTranslater.c
  source/libs/stream/src/streamBackendRocksdb.c
  source/libs/stream/test/backendTest.cpp
  tests/script/tsim/query/cache_last.sim
  tests/system-test/2-query/cols_function.py
Labels: team engine

#30601 doc: update user manual.
  docs/zh/06-advanced/06-TDgpt/01-introduction.md
  docs/zh/06-advanced/06-TDgpt/02-tutorial.md
  docs/zh/06-advanced/06-TDgpt/05-forecast/index.md
  docs/zh/06-advanced/06-TDgpt/06-anomaly-detection/index.md
  docs/zh/06-advanced/06-TDgpt/09-dev/04-tsfm/index.md
  docs/zh/06-advanced/06-TDgpt/09-dev/index.md
  docs/zh/06-advanced/06-TDgpt/10-tools.md
  docs/zh/06-advanced/06-TDgpt/11-faq.md
Labels: doc, team engine

#30603 doc(cfg): add faq for forceReadConfig.
  docs/en/27-train-faq/index.md
  docs/zh/27-train-faq/01-faq.md
Labels: team engine

#30593 fix(stmt2):core when use stmt2 select bind return error
  source/client/inc/clientStmt.h
  source/client/inc/clientStmt2.h
  source/client/src/clientStmt2.c
Labels: team engine

#30610 adjust docs format and remove test code
  .github/workflows/deploy-case-docs.yml
  test/README.md
  test/docs/index.md
  test/mkdocs.yml
  test/new_test_framework/utils/sql.py
  test/templates/python/material/function.html.jinja
Labels: team platform

#30616 refactor: preparatory work before merging the freemin PR
  .gitignore_global
  CMakeLists.txt
  contrib/CMakeLists.txt
  contrib/TSZ/CMakeLists.txt
Labels: team engine

#30613 fix: test case don't check debugFlag value
  tests/system-test/2-query/db.py
Labels: team engine

#30604 feat: taosdump support add or del cols/tags(main)
  cmake/cmake.define
  tests/army/tools/taosdump/native/json/schemaChange.json
  tests/army/tools/taosdump/native/json/schemaChangeNew.json
  tests/army/tools/taosdump/native/taosdumpSchemaChange.py
  tests/army/tools/taosdump/native/taosdumpTestInspect.py
  tests/parallel_test/cases.task
  tools/taos-tools/deps/CMakeLists.txt
  tools/taos-tools/inc/dump.h
  tools/taos-tools/inc/dumpUtil.h
  tools/taos-tools/src/CMakeLists.txt
  tools/taos-tools/src/benchInsert.c
  tools/taos-tools/src/benchJsonOpt.c
  tools/taos-tools/src/dumpUtil.c
  tools/taos-tools/src/taosdump.c
Labels: team tools

#30618 Revert "feat: taosdump support add or del cols/tags(main)"
  cmake/cmake.define
  tests/army/tools/taosdump/native/json/schemaChange.json
  tests/army/tools/taosdump/native/json/schemaChangeNew.json
  tests/army/tools/taosdump/native/taosdumpSchemaChange.py
  tests/army/tools/taosdump/native/taosdumpTestInspect.py
  tests/parallel_test/cases.task
  tools/taos-tools/deps/CMakeLists.txt
  tools/taos-tools/inc/dump.h
  tools/taos-tools/inc/dumpUtil.h
  tools/taos-tools/src/CMakeLists.txt
  tools/taos-tools/src/benchInsert.c
  tools/taos-tools/src/benchJsonOpt.c
  tools/taos-tools/src/dumpUtil.c
  tools/taos-tools/src/taosdump.c
Labels: team engine

#30624 Revert "Revert "feat: taosdump support add or del cols/tags(main)""
  cmake/cmake.define
  tests/army/tools/taosdump/native/json/schemaChange.json
  tests/army/tools/taosdump/native/json/schemaChangeNew.json
  tests/army/tools/taosdump/native/taosdumpSchemaChange.py
  tests/army/tools/taosdump/native/taosdumpTestInspect.py
  tests/parallel_test/cases.task
  tools/taos-tools/deps/CMakeLists.txt
  tools/taos-tools/inc/dump.h
  tools/taos-tools/inc/dumpUtil.h
  tools/taos-tools/src/CMakeLists.txt
  tools/taos-tools/src/benchInsert.c
  tools/taos-tools/src/benchJsonOpt.c
  tools/taos-tools/src/dumpUtil.c
  tools/taos-tools/src/taosdump.c
Labels: team tools

#30628 add pull_request_target for label-pr-by-team.yml
  .github/workflows/label-pr-by-team.yml
Labels: team platform

#30614 fix(stream): add null pointer check
  source/libs/executor/src/executor.c
  source/libs/executor/src/streamscanoperator.c
Labels: team engine

#30585 test:alter coverage script
  .github/workflows/tdengine-test-coverage.yml
  tests/parallel_test/run_coverage_container.sh
  tests/run_workflow_coverage.sh
Labels: team platform

#30606 fix[TD-34340]: enable page recyling and ensure TDB cell size is at least the size of a free cell
  source/dnode/vnode/src/vnd/vnodeSync.c
  source/libs/tdb/src/db/tdbBtree.c
  source/libs/tdb/src/db/tdbPage.c
  source/libs/tdb/src/db/tdbPager.c
  source/libs/tdb/src/inc/tdbInt.h
  source/os/src/osFile.c
Labels: team engine

#30543 fix(stream): remove continuous query test cases
  tests/parallel_test/longtimeruning_cases.task
Labels: team engine

#30611 fix: Update workflow files
  .github/workflows/tdengine-build.yml
  .github/workflows/validate-test-cases.yml
Labels: team platform

#30627 enh: change method to get latest version for grafana
  packaging/setup_env.sh
Labels: team platform

#30639 enh: add statistics for crash counts in different versions
  tests/script/telemetry/crash-report/.env.example
  tests/script/telemetry/crash-report/CrashCounter.py
  tests/script/telemetry/crash-report/README-CN.md
  tests/script/telemetry/crash-report/README.md
Labels: team platform

#30636 fix: CMake errors in an unclean Windows environment
  cmake/cmake.define
  contrib/CMakeLists.txt
Labels: team engine

#30638 fix(s3/cos): correct failed deleting log condition
  source/common/src/cos.c
Labels: team engine

#30643 merge: from main to 3.0 branch
  .github/workflows/tdengine-build.yml
  .github/workflows/tdengine-test-coverage.yml
  .github/workflows/validate-test-cases.yml
  cmake/cmake.define
  contrib/CMakeLists.txt
  docs/en/14-reference/09-error-code.md
  docs/zh/06-advanced/06-TDgpt/09-dev/04-tsfm/index.md
  docs/zh/06-advanced/06-TDgpt/09-dev/index.md
  docs/zh/06-advanced/06-TDgpt/10-tools.md
  docs/zh/14-reference/09-error-code.md
  packaging/setup_env.sh
  source/common/src/cos.c
  source/dnode/vnode/src/vnd/vnodeSync.c
  source/libs/executor/src/executor.c
  source/libs/executor/src/streamscanoperator.c
  source/libs/tdb/src/db/tdbBtree.c
  source/libs/tdb/src/db/tdbPage.c
  source/libs/tdb/src/db/tdbPager.c
  source/libs/tdb/src/inc/tdbInt.h
  source/os/src/osFile.c
  tests/parallel_test/run_coverage_container.sh
  tests/run_workflow_coverage.sh
  tests/script/telemetry/crash-report/.env.example
  tests/script/telemetry/crash-report/CrashCounter.py
  tests/script/telemetry/crash-report/README-CN.md
  tests/script/telemetry/crash-report/README.md
Labels: team engine

#30644 merge: from main to 3.0 branch
  docs/en/14-reference/03-taos-sql/12-distinguished.md
  docs/zh/14-reference/03-taos-sql/12-distinguished.md
  source/libs/executor/inc/tfill.h
  source/libs/executor/src/filloperator.c
  source/libs/executor/src/tfill.c
  tests/parallel_test/cases.task
  tests/system-test/2-query/fill2.py
  tests/system-test/output.txt
Labels: team engine

#30648 docs: update taosadapter monitoring metrics and fix TAG link case sen…
  docs/zh/14-reference/01-components/03-taosadapter.md
  docs/zh/14-reference/03-taos-sql/14-stream.md
Labels: team platform

#30653 merge: from main to 3.0 branch
  docs/zh/14-reference/01-components/03-taosadapter.md
  docs/zh/14-reference/03-taos-sql/14-stream.md
Labels: team platform

#30654 enh: switch from Grafana Enterprise to Community Edition
  packaging/setup_env.sh
Labels: team platform

#30656 refactor: get pr number and user from context
  .github/workflows/label-pr-by-team.yml
Labels: team platform

#30655 refactor: remove two inputs
  .github/workflows/label-pr-by-team.yml
Labels: team platform

#30657 fix[TS-6276]: when the authorization statement exceeds a certain length, it cannot be displayed in full
  source/dnode/mnode/impl/src/mndUser.c
  tests/army/grant/grantBugs.py
Labels: team engine

#30631 enh: test coverage for tlog.c
  source/util/test/log.cpp
Labels: team engine

#30671 refactor: let the enterprise use the cmake files of the community
  .gitignore_global
  CMakeLists.txt
  cmake/preinclude.cmake
Labels: team engine

#30608 fix: [TD-34205] Fix vtable mem leak
  source/libs/executor/src/executor.c
  source/libs/executor/src/executorInt.c
  source/libs/executor/src/querytask.c
  source/libs/qworker/src/qworker.c
Labels: team engine

#30678 refactor: let the enterprise use the cmake files of the community
  .gitignore_global
  cmake/preinclude.cmake
Labels: team engine

#30681 fix: cmake errors in debug mode
  source/os/test/CMakeLists.txt
Labels: team engine

#30690 docs: fix interval syntax error
  docs/zh/14-reference/03-taos-sql/07-select.md
Labels: team engine

#30666 enh: wait checkpoint ready before pause stream
  tests/pytest/util/common.py
  tests/system-test/8-stream/pause_resume_test.py
Labels: team platform

#30693 docs: update for tdengine enterprise using docker
  docs/en/04-get-started/01-docker.md
  docs/en/04-get-started/06-enterprise.md
Labels: team platform

#30476 enh:add two models to tdgpt pkg
  tools/tdgpt/script/install.sh
  tools/tdgpt/script/release.sh
  tools/tdgpt/script/start-tdtsfm.sh
  tools/tdgpt/script/start-timer-moe.sh
  tools/tdgpt/script/start-with-allmd.sh
  tools/tdgpt/script/stop-tdtsfm.sh
  tools/tdgpt/script/stop-timer-moe.sh
  tools/tdgpt/script/uninstall.sh
Labels: team platform

#30696 docs: simplify the repository root directory
  Jenkinsfile
  Jenkinsfile2
  compile_flags.txt
  docs/SECURITY.md
Labels: team engine

#30676 fix: improve process killing logic in remove.sh for mac
  packaging/tools/remove.sh
Labels: team platform

#30694 fix: add tag data type check when create child table
  source/dnode/vnode/src/meta/metaTable2.c
Labels: team engine

#30695 fix: add tag data type check when create child table
  source/dnode/vnode/src/meta/metaTable2.c
Labels: team engine

#30675 fix: [TD-34455] sync-election-timer-log
  source/libs/sync/src/syncMain.c
Labels: team engine

#30672 fix: meta abort clear cache
  source/dnode/vnode/src/inc/vnodeInt.h
  source/dnode/vnode/src/meta/metaCache.c
  source/dnode/vnode/src/meta/metaCommit.c
Labels: team engine

#30697 fix: enterprise edition fails to execute make install cmd
  cmake/cmake.define
  cmake/cmake.install
  cmake/cmake.version
  docs/CODE_OF_CONDUCT-CN.md
  docs/CODE_OF_CONDUCT.md
Labels: team engine

#30637 enh: TD-34420-improve-sync-heartbeat-log
  source/libs/sync/inc/syncUtil.h
  source/libs/sync/src/syncMain.c
  source/libs/sync/src/syncUtil.c
Labels: team engine

#30708 enh: refine ctest command to exclude specific tests
  tests/unit-test/test.sh
Labels: team platform

#30703 feat: fix install.sh taosudf name
  packaging/tools/install.sh
Labels: team platform

#30588 fix/TS-6226-send-check-when-not-sync
  source/common/src/tglobal.c
  source/dnode/mnode/impl/src/mndArbGroup.c
Labels: team engine

#30706 fix: change the default value of the option shareConnlimit from 10 to…
  docs/zh/14-reference/01-components/01-taosd.md
  source/common/src/tglobal.c
Labels: team engine

#30701 fix: [TS-6276] grant-format
  include/libs/nodes/nodes.h
  source/dnode/mnode/impl/src/mndUser.c
  source/libs/nodes/src/nodesToSQLFuncs.c
Labels: team engine

#30668 fix: [TD-34436] double-release
  source/dnode/mnode/impl/src/mndStreamTransAct.c
  source/dnode/mnode/sdb/src/sdbHash.c
  source/dnode/mnode/sdb/src/sdbRow.c
Labels: team engine

#30716 feat: add uv to setup_env.sh
  packaging/setup_env.sh
Labels: team platform

#30677 fix: [TD-34274] add-monitor-case
  tests/system-test/0-others/taosdNewMonitor.py
Labels: team engine

#30633 enh: taosdump support cols or tags changed in anywhere(main)
  tests/army/frame/caseBase.py
  tests/army/tools/taosdump/native/json/schemaChange.json
  tests/army/tools/taosdump/native/json/schemaChangeNew.json
  tests/army/tools/taosdump/native/taosdumpCommandline.py
  tests/army/tools/taosdump/native/taosdumpSchemaChange.py
  tools/taos-tools/src/benchUtil.c
  tools/taos-tools/src/dumpUtil.c
  tools/taos-tools/src/taosdump.c
Labels: team tools

#30711 ci:fix some errror for geting pr status
  .github/workflows/cancel-workflow-on-merge.yml
  tests/unit-test/test.sh
Labels: team platform

#30710 fix: failed to start udfd
  include/libs/function/tudf.h
  source/common/src/tglobal.c
  source/libs/function/src/tudf.c
  source/libs/function/src/udfd.c
Labels: team engine

#30714 fix: fix possible test case failure
  tests/test_new/storage/compact/test_compact_meta.py
Labels: team engine

#30713 fix: fix possible case failure
  tests/test_new/storage/compact/test_compact_meta.py
Labels: team engine

#30717 docs: improve high volume doc
  docs/en/07-develop/15-high.md
  docs/en/10-third-party/01-collection/11-kafka.md
  docs/en/assets/ingesting-data-efficiently-01.png
  docs/zh/07-develop/15-high.md
  docs/zh/07-develop/highvolume.png
  docs/zh/10-third-party/01-collection/11-kafka.md
Labels: team tools

#30707 fix: [TD-34459] add-waiting-leader
  tests/army/cluster/arbitrator.py
  tests/army/cluster/arbitrator_restart.py
Labels: team engine

#30702 Fix: [td 34460] add more log output
  tests/system-test/0-others/taosd_audit.py
Labels: team engine

#30723 ci:add taosa internal in container_build.sh
  tests/parallel_test/container_build.sh
Labels: team platform

#30726 fix(stmt2): interlace ts order
  source/client/test/stmt2Test.cpp
  source/common/src/tdataformat.c
Labels: team engine

#30731 fix: update TDgpt service workflow to use main branch and adjust sche…
  .github/workflows/tdgpt-update-service.yml
Labels: team platform

#30738 fix: update installation scripts for improved model handling
  tools/tdgpt/script/install.sh
  tools/tdgpt/script/release.sh
Labels: team platform

#30725 feat: upgrade go version to 1.23 or above
  .github/workflows/taoskeeper-build.yml
  .github/workflows/tdengine-build.yml
  .github/workflows/tdengine-release-build.yml
  README-CN.md
  README.md
  tools/keeper/README-CN.md
  tools/keeper/README.md
  tools/keeper/go.mod
  tools/keeper/go.sum
Labels: team tools

#30732 fix: the REPLICA parameter supports plural forms when used to create and alter a database
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parTokenizer.c
  tests/script/tsim/db/basic6.sim
Labels: team engine

#30744 refactor: remove unused import of 'insert' from numpy in multiple test files
  tests/system-test/1-insert/insertWithMoreVgroup.py
  tests/system-test/1-insert/mutipythonnodebugtaosd.py
  tests/system-test/1-insert/test_stmt_muti_insert_query.py
  tests/system-test/1-insert/test_stmt_set_tbname_tag.py
  tests/system-test/2-query/queryQnode.py
  tests/system-test/2-query/smaTest.py
  tests/test_new/data_write/stmt/test_stmt_set_tbname_tag.py
Labels: team platform

#30747 fix: prevent installation script from failing on missing model files
  tools/tdgpt/script/install.sh
Labels: team platform

#30730 fix: Update remove.sh
  packaging/tools/remove.sh
Labels: team platform

#30741 enh[TS-6318]: changed the keyword for composite primary keys from "primary key" to "composite key"
  docs/en/07-develop/04-schemaless.md
  docs/en/14-reference/01-components/01-taosd.md
  docs/en/14-reference/03-taos-sql/03-table.md
  docs/en/14-reference/03-taos-sql/04-stable.md
  docs/en/14-reference/03-taos-sql/10-function.md
  docs/en/14-reference/03-taos-sql/14-stream.md
  docs/en/14-reference/03-taos-sql/20-keywords.md
  docs/zh/14-reference/03-taos-sql/03-table.md
  docs/zh/14-reference/03-taos-sql/04-stable.md
  docs/zh/14-reference/03-taos-sql/14-stream.md
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parTokenizer.c
  source/libs/parser/src/parUtil.c
  source/util/src/terror.c
  tests/army/cluster/arbitrator.py
  tests/army/cluster/arbitrator_restart.py
  tests/script/tsim/query/cache_last.sim
  tests/script/tsim/stream/streamPrimaryKey0.sim
  tests/system-test/0-others/taosd_audit.py
Labels: team engine

#30709 enh: wait checkpoint ready before pause stream
  tests/pytest/util/common.py
  tests/system-test/8-stream/pause_resume_test.py
Labels: team platform

#30704 fxi: docker run privileged
  source/libs/function/src/udfd.c
  tests/parallel_test/run_case.sh
  tests/parallel_test/run_container.sh
Labels: team engine

#30667 Fix/ts 6244/show dnodes3.0
  include/common/tmsg.h
  include/libs/catalog/catalog.h
  source/common/src/msg/tmsg.c
  source/dnode/mnode/impl/src/mndDnode.c
  source/libs/parser/inc/parUtil.h
  source/libs/parser/src/parTranslater.c
  source/libs/parser/test/mockCatalogService.cpp
  source/libs/planner/src/planOptimizer.c
Labels: team engine

#30755 fix: failed to retrieve the value of the variable TD_VER_GIT_INTERNAL in cmake.version
  cmake/cmake.version
Labels: team engine

#30686 fix(tmq): add check to avoid heap-use-after-free
  source/client/src/clientTmq.c
Labels: team engine

#30753 chore: update 03-kubernetes.md
  docs/en/08-operation/03-deployment/03-kubernetes.md
Labels: from community

#30745 fix: fix taosadapter.toml lose on Mac
  packaging/tools/make_install.sh
Labels: team platform

#30743 fix(query): duplicate the primary key in case of varchar type, to avoid to dereference invalid memory buffer.
  source/client/test/clientTests.cpp
  source/common/src/tdatablock.c
  source/dnode/vnode/src/tsdb/tsdbRead2.c
  tests/script/tsim/parser/ts-6314.sim
Labels: team engine

#30761 docs: update taosAdapter monitoring description
  docs/en/14-reference/01-components/03-taosadapter.md
  docs/zh/14-reference/01-components/03-taosadapter.md
Labels: team tools

#30767 docs: fix codeblock in explorer doc
  docs/en/14-reference/01-components/07-explorer.md
Labels: from community

#30766 test:alter default branch
  .github/workflows/tdengine-test-coverage.yml
Labels: team platform

#30670 fix: update support link in error message for unsupported platform initialization
  source/dnode/mgmt/exe/dmMain.c
Labels: team platform

#30768 fix: community edition fails to compile the release version
  cmake/cmake.define
Labels: team engine

#30740 fix: [TS-6245]-add-trans-timeout
  source/dnode/mnode/impl/src/mndTrans.c
Labels: team engine

#30567 fix: [TS-6245]add-protection-when-drop-db
  docs/en/14-reference/09-error-code.md
  docs/zh/14-reference/09-error-code.md
  include/util/taoserror.h
  source/dnode/mnode/impl/src/mndDb.c
  source/util/src/terror.c
Labels: team engine

#30756 fix: TD-34514-log-level
  source/libs/sync/src/syncUtil.c
Labels: team engine

#30769 fix(stmt2):refactor stmt2 prepare cache reset
  source/client/inc/clientStmt2.h
  source/client/src/clientStmt2.c
  source/client/test/stmt2Test.cpp
Labels: team engine

#30771 fix: add ThrottleInterval key(600s) to plist for taosd in macOS
  packaging/tools/com.taosdata.taosd.plist
Labels: team platform

#30773 cmake.define /MT -> /MD windows
  cmake/cmake.define
Labels: team tools

#30776 fix: add conditional execution for ReviewDog reporting in CI workflow
  .github/workflows/tdengine-doc-build.yml
Labels: team platform

#30760 taoskeeper support new adapter metrics: connection pool and status
  tools/keeper/api/adapter2.go
  tools/keeper/api/adapter2_test.go
  tools/keeper/api/gen_metric.go
  tools/keeper/system/program.go
Labels: team tools

#30047 docs(mqtt): add documetation for cached data configuration
  docs/zh/06-advanced/05-data-in/07-mqtt.mdx
  docs/zh/06-advanced/05-data-in/mqtt-14.png
Labels: team tools

#30764 feat: [TS-6333] Fix decimal attempting free on address which was not malloc()-ed.
  source/dnode/vnode/src/meta/metaQuery.c
  tests/army/query/decimal/test_TS6333.py
  tests/parallel_test/cases.task
Labels: team engine

#30763 feat: change taosadapter log dir and log level
  test/new_test_framework/utils/before_test.py
  tests/army/frame/taosadapter.py
  tests/pytest/util/taosadapter.py
Labels: team platform

#30795 enh: add default log dir when examples case failed
  test/ci/run_case.sh
  test/ci/run_container.sh
  tests/parallel_test/run_case.sh
  tests/parallel_test/run_container.sh
Labels: team platform

#30782 fix(tmq): update privilege for tmq if privilege change
  source/client/src/clientTmq.c
Labels: team engine

#30787 fix(dataformat): fix single column row copying
  source/common/src/tdataformat.c
Labels: team engine

#30788 fix(dataformat): fix single column row copying
  source/common/src/tdataformat.c
Labels: team engine

#30790 fix: memcpy with snprintf to fix build error
  tools/taos-tools/src/benchUtil.c
Labels: team tools

#30778 remove tmq attribute enable.heartbeat.background
  tests/army/tools/benchmark/basic/json/tmqBasicPara.json
  tests/army/tools/benchmark/basic/json/tmqBasicSequ.json
  tests/army/tools/benchmark/basic/json/tmq_basic.json
  tests/army/tools/benchmark/basic/json/tmq_basic2.json
  tests/army/tools/benchmark/basic/json/tmq_basic3.json
  tests/army/tools/benchmark/basic/json/tmq_cancel.json
  tools/taos-tools/inc/bench.h
  tools/taos-tools/src/benchJsonOpt.c
  tools/taos-tools/src/benchTmq.c
Labels: team tools

#30793 fix(stmt2):non-interlace multi-prepare problem
  source/client/src/clientStmt2.c
  source/client/test/stmt2Test.cpp
Labels: team engine

#30799 docs: [TS-6094] Modify docs of virtual table.
  docs/zh/14-reference/03-taos-sql/05-virtualtable.md
Labels: team engine

#30794 fix: make duplicate version acceptable
  source/dnode/vnode/src/tsdb/tsdbUtil.c
Labels: team engine

#30796 enh: reduce the amount of logs printed when the apply queue is full.
  include/libs/sync/sync.h
  source/dnode/vnode/src/inc/vnodeInt.h
  source/dnode/vnode/src/vnd/vnodeSync.c
  source/libs/sync/inc/syncInt.h
  source/libs/sync/src/syncPipeline.c
Labels: team engine

#30789 fix fill range check for natural units
  source/libs/parser/src/parTranslater.c
  tests/system-test/2-query/fill.py
  tests/system-test/2-query/fill2.py
  tests/system-test/2-query/tsma.py
Labels: team engine

#30785 fix: json configuration not effective
  tests/army/tools/benchmark/basic/config/taos.cfg
  tests/army/tools/benchmark/basic/json/taos_config.json
  tests/army/tools/benchmark/basic/taos_config_json.py
  tests/parallel_test/cases.task
  tools/taos-tools/inc/bench.h
  tools/taos-tools/src/benchMain.c
  tools/taos-tools/src/benchSys.c
Labels: team tools

#30775 docs: update release note for 3.3.6.3 in office web
  cmake/cmake.version
  docs/en/28-releases/01-tdengine.md
  docs/en/28-releases/03-notes/3.3.6.3.md
  docs/zh/28-releases/01-tdengine.md
  docs/zh/28-releases/03-notes/3.3.6.3.md
Labels: team platform

#30801 enh(stream): add groupId in stream notification
  docs/en/14-reference/03-taos-sql/14-stream.md
  docs/zh/14-reference/03-taos-sql/14-stream.md
  source/libs/executor/src/streamexecutorInt.c
Labels: team engine

#30808 merge: from main to 3.0 branch
  .github/workflows/tdengine-doc-build.yml
  .github/workflows/tdengine-test-coverage.yml
  README-CN.md
  README.md
  cmake/cmake.define
  docs/en/08-operation/03-deployment/03-kubernetes.md
  docs/en/14-reference/01-components/03-taosadapter.md
  docs/en/14-reference/01-components/07-explorer.md
  docs/en/14-reference/09-error-code.md
  docs/typos.toml
  docs/zh/08-operation/20-inspect-tools/03-taosinstall.md
  docs/zh/08-operation/20-inspect-tools/index.md
  docs/zh/14-reference/01-components/03-taosadapter.md
  docs/zh/14-reference/03-taos-sql/05-virtualtable.md
  docs/zh/14-reference/09-error-code.md
  include/libs/sync/sync.h
  include/util/taoserror.h
  packaging/tools/com.taosdata.taosd.plist
  packaging/tools/make_install.sh
  source/client/inc/clientStmt2.h
  source/client/src/clientStmt2.c
  source/client/src/clientTmq.c
  source/client/test/clientTests.cpp
  source/client/test/stmt2Test.cpp
  source/common/src/tdatablock.c
  source/dnode/mgmt/exe/dmMain.c
  source/dnode/mgmt/mgmt_dnode/src/dmHandle.c
  source/dnode/mnode/impl/src/mndDb.c
  source/dnode/mnode/impl/src/mndMnode.c
  source/dnode/mnode/impl/src/mndTrans.c
  source/dnode/vnode/src/inc/vnodeInt.h
  source/dnode/vnode/src/meta/metaQuery.c
  source/dnode/vnode/src/tsdb/tsdbRead2.c
  source/dnode/vnode/src/tsdb/tsdbUtil.c
  source/dnode/vnode/src/vnd/vnodeSync.c
  source/libs/parser/src/parTranslater.c
  source/libs/sync/inc/syncInt.h
  source/libs/sync/src/syncMain.c
  source/libs/sync/src/syncPipeline.c
  source/libs/sync/src/syncUtil.c
  source/util/src/terror.c
  test/ci/run_case.sh
  test/ci/run_container.sh
  test/new_test_framework/utils/before_test.py
  tests/README.md
  tests/army/frame/taosadapter.py
  tests/army/inspect-tools/taosinspect.py
  tests/army/query/decimal/test_TS6333.py
  tests/parallel_test/cases.task
  tests/parallel_test/run_case.sh
  tests/parallel_test/run_container.sh
  tests/pytest/util/taosadapter.py
  tests/script/tsim/parser/ts-6314.sim
  tests/system-test/2-query/fill.py
  tests/system-test/2-query/fill2.py
  tests/system-test/2-query/tsma.py
  tools/keeper/api/adapter2.go
  tools/keeper/api/adapter2_test.go
  tools/keeper/api/gen_metric.go
  tools/keeper/system/program.go
Labels: team engine

#30625 feat: added base64 SQL function
  docs/en/14-reference/03-taos-sql/10-function.md
  docs/zh/14-reference/03-taos-sql/10-function.md
  include/libs/function/functionMgt.h
  include/libs/scalar/scalar.h
  source/libs/function/src/builtins.c
  source/libs/scalar/src/sclfunc.c
  tests/army/query/function/ans/base64.csv
  tests/army/query/function/in/base64.err
  tests/army/query/function/in/base64.in
  tests/army/query/function/test_function.py
Labels: from community

#30804 fix/TD-34460-create-tb-in-thread
  tests/system-test/0-others/taosd_audit.py
Labels: team engine

#30812 enh(cfg): modify config behavior.
  source/common/src/tglobal.c
  source/dnode/mgmt/mgmt_dnode/src/dmHandle.c
  source/dnode/mnode/impl/src/mndConfig.c
  source/util/src/tconfig.c
  tests/army/alter/alterConfig.py
  tests/system-test/0-others/test_dismatch_config.py
Labels: team engine

#30813 fix(stmt2):fixed tag multi-prepare core
  source/client/src/clientStmt2.c
  source/client/test/stmt2Test.cpp
Labels: team engine

#30759 enh: disable the 'show scores' command
  source/libs/nodes/src/nodesUtilFuncs.c
  tests/army/query/show.py
Labels: team engine

#30816 add support of data types for composite primary key columns
  docs/zh/14-reference/03-taos-sql/03-table.md
Labels: internal

#30818 modify the taosBenchmark parameter issue in the Mac environment
  .github/workflows/tdengine-build.yml
  tools/taos-tools/src/benchSys.c
Labels: team tools

#30774 fix: set lcn = 0 while lastcompact = lastcommit.
  source/dnode/vnode/src/tsdb/tsdbFS2.c
Labels: team engine

#30825 doc: update user manual.
  docs/zh/06-advanced/06-TDgpt/05-forecast/index.md
  docs/zh/06-advanced/06-TDgpt/09-dev/04-tsfm/index.md
Labels: team engine

#30823 docs: update window pic
  docs/en/05-basic/03-query.md
  docs/en/06-advanced/03-stream.md
  docs/en/14-reference/03-taos-sql/12-distinguished.md
  docs/en/14-reference/03-taos-sql/14-stream.md
  docs/en/14-reference/03-taos-sql/assets/stream-processing-01-watermark.webp
  docs/en/14-reference/03-taos-sql/assets/stream-processing-01.png
  docs/en/14-reference/03-taos-sql/assets/time-series-extensions-01-time-window.png
  docs/en/14-reference/03-taos-sql/assets/time-series-extensions-02-state-window.png
  docs/en/14-reference/03-taos-sql/assets/time-series-extensions-02.png
  docs/en/14-reference/03-taos-sql/assets/time-series-extensions-03-session-window.png
  docs/en/14-reference/03-taos-sql/assets/time-series-extensions-03.png
  docs/en/14-reference/03-taos-sql/assets/time-series-extensions-04-event-window.png
  docs/en/14-reference/03-taos-sql/assets/time-series-extensions-04.png
  docs/en/14-reference/03-taos-sql/assets/time-series-extensions-05-count-window.png
  docs/en/14-reference/03-taos-sql/assets/time-series-extensions-05.png
  docs/en/assets/data-querying-01-window.png
  docs/en/assets/data-querying-01.png
  docs/en/assets/data-querying-02-time-window.webp
  docs/en/assets/data-querying-02.png
  docs/en/assets/data-querying-03-session-window.png
  docs/en/assets/data-querying-03.png
  docs/en/assets/data-querying-04-event-window.png
  docs/en/assets/data-querying-04.png
  docs/en/assets/stream-processing-01-watermark.webp
  docs/en/assets/stream-processing-01.png
  docs/zh/05-basic/01-model.md
  docs/zh/05-basic/03-query.md
  docs/zh/05-basic/event-window.png
  docs/zh/05-basic/pic/data-model.png
  docs/zh/05-basic/pic/event_window.png
  docs/zh/05-basic/pic/session_window.png
  docs/zh/05-basic/pic/time_window.webp
  docs/zh/05-basic/pic/window.png
  docs/zh/05-basic/session-window.png
  docs/zh/05-basic/sliding-window.png
  docs/zh/14-reference/03-taos-sql/12-distinguished.md
  docs/zh/14-reference/03-taos-sql/14-stream.md
  docs/zh/14-reference/03-taos-sql/event_window.webp
  docs/zh/14-reference/03-taos-sql/pic/count_window.png
  docs/zh/14-reference/03-taos-sql/pic/event_window.png
  docs/zh/14-reference/03-taos-sql/pic/session_window.png
  docs/zh/14-reference/03-taos-sql/pic/state_window.png
  docs/zh/14-reference/03-taos-sql/pic/time_window.webp
  docs/zh/14-reference/03-taos-sql/pic/watermark.webp
  docs/zh/14-reference/03-taos-sql/timewindow-2.webp
  docs/zh/14-reference/03-taos-sql/timewindow-3.webp
Labels: team engine

#30592 fix(stream): parName is null
  source/common/src/tdatablock.c
  source/dnode/mnode/impl/src/mndStreamTrans.c
  source/dnode/vnode/src/tq/tq.c
  source/dnode/vnode/src/tq/tqSink.c
  source/dnode/vnode/src/tq/tqSnapshot.c
  source/libs/executor/inc/operator.h
  source/libs/executor/src/executor.c
  source/libs/executor/src/groupoperator.c
  source/libs/executor/src/operator.c
  source/libs/executor/src/projectoperator.c
  source/libs/executor/src/scanoperator.c
  source/libs/executor/src/streamfillnonblockoperator.c
  source/libs/executor/src/streamfilloperator.c
  source/libs/executor/src/streamintervalsliceoperator.c
  source/libs/executor/src/streamtimesliceoperator.c
  source/libs/executor/src/streamtimewindowoperator.c
  source/libs/stream/src/streamDispatch.c
  source/libs/stream/src/streamMeta.c
  source/libs/stream/src/streamSched.c
  source/libs/stream/src/streamState.c
Labels: team engine

#30829 doc:pdate en pics
  docs/en/14-reference/03-taos-sql/assets/time-series-extensions-04-event-window.png
  docs/en/assets/data-querying-04-event-window.png
Labels: team engine

#30822 fix: wrapper load so from /usr/local/lib/ on mac
  source/client/wrapper/src/wrapperDriver.c
Labels: team tools

#30820 fix: [TS-6383] Fix drop vtable error.
  source/libs/parser/src/parTranslater.c
  tests/army/vtable/test_vtable_drop.py
Labels: team engine

#30830 fix: show create table and desc table statements return composite key…
  source/libs/command/src/command.c
  tests/script/tsim/query/cache_last.sim
  tests/system-test/1-insert/composite_primary_key_create.py
Labels: team engine

#30833 doc: add description of DURATION.
  docs/en/14-reference/03-taos-sql/02-database.md
  docs/zh/14-reference/03-taos-sql/02-database.md
Labels: team engine

#30831 feat(gpt): add tdtsfm server
  tools/tdgpt/taosanalytics/tsfmservice/tdtsfm-server.py
Labels: team engine

#30835 fix: (TS-6376)jump virtual table if snapshot is true in tmq
  source/dnode/vnode/src/meta/metaSnapshot.c
  tests/system-test/7-tmq/tmq_taosx.py
Labels: team engine

#30847 ci: modify branch in tdengine-test.yml
  .github/workflows/tdengine-test.yml
Labels: team platform

#30848 ci: modify branch in tdengine-test.yml
  .github/workflows/tdengine-test.yml
Labels: team platform

#30852 doc: Update 04-machine-learning.md
  docs/zh/06-advanced/06-TDgpt/06-anomaly-detection/02-statistics-approach.md
  docs/zh/06-advanced/06-TDgpt/06-anomaly-detection/04-machine-learning.md
Labels: team engine

#30836 doc: Update index.md
  docs/zh/06-advanced/06-TDgpt/05-forecast/index.md
Labels: team engine

#30807 test: migrate datatype cases
  .gitignore_global
  test/cases/datatype/test_column_bigint.py
  test/cases/datatype/test_column_bool.py
  test/cases/datatype/test_column_double.py
  test/cases/datatype/test_column_float.py
  test/cases/datatype/test_column_geometry.py
  test/cases/datatype/test_column_int.py
  test/cases/datatype/test_column_json.py
  test/cases/datatype/test_column_nchar.py
  test/cases/datatype/test_column_smallint.py
  test/cases/datatype/test_column_timestamp.py
  test/cases/datatype/test_column_tinyint.py
  test/cases/datatype/test_column_uint.py
  test/cases/datatype/test_column_unsign.py
  test/cases/datatype/test_column_varbinary.py
  test/cases/datatype/test_column_varchar.py
  test/cases/stable/tagmgmt/test_tag_add.py
  test/cases/stable/tagmgmt/test_tag_change.py
  test/cases/stable/tagmgmt/test_tag_commit.py
  test/cases/stable/tagmgmt/test_tag_create.py
  test/cases/stable/tagmgmt/test_tag_drop.py
  test/cases/stable/tagmgmt/test_tag_drop_table.py
  test/cases/stable/tagmgmt/test_tag_set.py
  test/cases/stable/tagmgmt/test_tag_set_multi.py
  test/cases/stable/tagquery/test_tag_3.py
  test/cases/stable/tagquery/test_tag_4.py
  test/cases/stable/tagquery/test_tag_5.py
  test/cases/stable/tagquery/test_tag_6.py
  test/cases/stable/tagquery/test_tag_bigint.py
  test/cases/stable/tagquery/test_tag_binary.py
  test/cases/stable/tagquery/test_tag_binary_binary.py
  test/cases/stable/tagquery/test_tag_bool.py
  test/cases/stable/tagquery/test_tag_bool_binary.py
  test/cases/stable/tagquery/test_tag_bool_int.py
  test/cases/stable/tagquery/test_tag_column.py
  test/cases/stable/tagquery/test_tag_double.py
  test/cases/stable/tagquery/test_tag_filter.py
  test/cases/stable/tagquery/test_tag_float.py
  test/cases/stable/tagquery/test_tag_int.py
  test/cases/stable/tagquery/test_tag_int_binary.py
  test/cases/stable/tagquery/test_tag_int_float.py
  test/cases/stable/tagquery/test_tag_smallint.py
  test/cases/stable/tagquery/test_tag_tbname_in.py
  test/cases/stable/tagquery/test_tag_tinyint.py
  test/ci/cases.task
  test/ci/pytest.sh
  test/conftest.py
Labels: team engine

#30828 docs(datain): add missing health status types
  docs/zh/06-advanced/05-data-in/index.md
Labels: team tools

#30859 fix(tmq): init tmq handle error if snapshotVer is out of range
  include/libs/wal/wal.h
  source/dnode/vnode/src/inc/sma.h
  source/dnode/vnode/src/tq/tq.c
  source/dnode/vnode/src/tq/tqMeta.c
  source/libs/wal/src/walRef.c
  tests/parallel_test/cases.task
  tests/system-test/7-tmq/tmq_taosx.py
  tests/system-test/7-tmq/tmq_ts6392.py
Labels: team engine
