Repository taosdata/TDengine, pull requests merged in 2025-06, with the labels that each got.

#31259 feat(taoskeeper): taoskeeper listen on a specified IP address
  docs/en/14-reference/01-components/06-taoskeeper.md
  docs/zh/14-reference/01-components/06-taoskeeper.md
  tools/keeper/api/adapter2.go
  tools/keeper/api/adapter2_test.go
  tools/keeper/api/audit.go
  tools/keeper/api/audit_test.go
  tools/keeper/api/common.go
  tools/keeper/api/exporter_test.go
  tools/keeper/api/gen_metric.go
  tools/keeper/api/gen_metric_test.go
  tools/keeper/api/https_test.go
  tools/keeper/api/report.go
  tools/keeper/api/tables_test.go
  tools/keeper/cmd/command.go
  tools/keeper/cmd/command_test.go
  tools/keeper/config/taoskeeper.toml
  tools/keeper/config/taoskeeper_enterprise.toml
  tools/keeper/db/connector.go
  tools/keeper/infrastructure/config/config.go
  tools/keeper/monitor/monitor.go
  tools/keeper/monitor/monitor_test.go
  tools/keeper/process/builder.go
  tools/keeper/process/handle.go
  tools/keeper/system/program.go
  tools/keeper/system/program_test.go
  tools/keeper/util/empty_test.go
  tools/keeper/util/util.go
  tools/keeper/util/util_test.go
Labels: team tools

#31262 feat: [TS-6100] Parse create stream sql: Sql gen refactor and fix bugs.
  source/libs/parser/src/parAstCreater.c
  source/libs/parser/src/parTokenizer.c
  source/libs/parser/src/parTranslater.c
  test/cases/13-StreamProcessing/02-Stream/test_create_stream_syntax.py
Labels: team engine

#31265 docs: update release note for 3.3.6.9 in office web
  cmake/version.cmake
  docs/en/28-releases/01-tdengine.md
  docs/en/28-releases/03-notes/3.3.6.9.md
  docs/zh/28-releases/01-tdengine.md
  docs/zh/28-releases/03-notes/3.3.6.9.md
Labels: team platform

#31277 add server port and mqttport in configuration file
  test/README.md
  test/cases/30-DataCompression/test_compress_basic.py
  test/env/taos_config.yaml
  test/new_test_framework/utils/autogen.py
  test/new_test_framework/utils/before_test.py
Labels: team platform

#31274 fix: [TD-35276] add-log-apply-internal-error
  source/dnode/vnode/src/vnd/vnodeSvr.c
Labels: team engine

#31282 feat: [TS-6100] Parse create stream sql: Support %%tbname.
  include/libs/nodes/plannodes.h
  include/libs/planner/planner.h
  source/libs/nodes/src/nodesCloneFuncs.c
  source/libs/nodes/src/nodesCodeFuncs.c
  source/libs/nodes/src/nodesMsgFuncs.c
  source/libs/parser/src/parTranslater.c
  source/libs/planner/src/planLogicCreater.c
  source/libs/planner/src/planPhysiCreater.c
  source/libs/planner/src/planScaleOut.c
  source/libs/planner/src/planSpliter.c
Labels: team engine

#31284 feat: [TS-6100] Parse create stream sql: Fix _twduration wrong type.
  source/libs/function/src/builtins.c
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31285 feat: [TS-6100] Parse create stream sql: Add primary key check.
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31281 Update install.sh
  packaging/tools/install.sh
Labels: team platform

#31288 feat: [TS-6100] Parse create stream sql: Fix %%tbname wrong plan
  source/libs/parser/src/parTranslater.c
  source/libs/planner/src/planOptimizer.c
  source/libs/planner/src/planUtil.c
Labels: team engine

#31293 feat: [TS-6100] Parse create stream sql: Extract condition from count window
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31289 enh: grant support vnode/storage_size and TDasset items
  include/common/tglobal.h
  include/common/tgrant.h
  include/util/taoserror.h
  source/common/src/tglobal.c
  source/libs/qworker/src/qwMsg.c
  source/util/src/terror.c
  tests/army/whole/checkErrorCode.py
  tests/system-test/0-others/grant.py
  tests/system-test/0-others/information_schema.py
Labels: team engine

#31302 feat: [TS-6100] Parse create stream sql: Fix %%tbname wrong plan
  source/libs/parser/src/parTranslater.c
  test/cases/13-StreamProcessing/02-Stream/test_create_stream_syntax.py
Labels: team engine

#31304 feat(taoskeeper): support forever retry when error in setup
  tools/keeper/api/adapter2.go
  tools/keeper/api/audit.go
  tools/keeper/api/gen_metric.go
  tools/keeper/api/report.go
  tools/keeper/db/connector.go
  tools/keeper/db/connector_test.go
  tools/keeper/db/empty_test.go
  tools/keeper/process/builder.go
  tools/keeper/process/handle.go
Labels: team tools

#31307 Update remove.sh
  packaging/tools/remove.sh
Labels: team platform

#31312 feat: [TS-6100] Parse create stream sql: sql generator refactor
  source/libs/parser/src/parTranslater.c
  test/cases/13-StreamProcessing/02-Stream/test_create_stream_syntax.py
Labels: team engine

#31314 feat: [TS-6100] Parse create stream sql: Add stream name check
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31308 fix(gpt): set the return type to be double.
  docs/zh/06-advanced/06-TDgpt/05-forecast/index.md
  docs/zh/06-advanced/06-TDgpt/09-dev/02-algo/02-forecast.md
  docs/zh/06-advanced/06-TDgpt/09-dev/04-tsfm/index.md
  source/libs/executor/src/forecastoperator.c
  source/libs/function/src/builtins.c
  tools/tdgpt/taosanalytics/tsfmservice/moirai-server.py
Labels: team engine

#31316 update the user manual based on the inspection series tool v1.3.4
  docs/zh/08-operation/20-inspect-tools/01-taosprecheck.md
  docs/zh/08-operation/20-inspect-tools/02-taospreset.md
  docs/zh/08-operation/20-inspect-tools/03-taosinstall.md
  docs/zh/08-operation/20-inspect-tools/04-taosinspect.md
  docs/zh/08-operation/20-inspect-tools/05-taosperf.md
  docs/zh/08-operation/20-inspect-tools/index.md
Labels: internal

#31319 enh: add method to run crash_gen with pkg
  tests/pytest/crash_gen/crash_gen_main.py
  tests/pytest/crash_gen/service_manager.py
Labels: team platform

#31321 feat: [TS-6100] Parse create stream sql: Fix varchar schema wrong lengh.
  source/libs/parser/src/parTranslater.c
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_concat.py
  test/cases/13-StreamProcessing/99-Others/test_dev_basic3.py
  test/cases/13-StreamProcessing/99-Others/test_dev_basic6.py
Labels: team engine

#31318 doc: update doc.
  docs/zh/06-advanced/06-TDgpt/05-forecast/index.md
  docs/zh/06-advanced/06-TDgpt/pic/fc-covariate.png
Labels: team engine

#31322 doc: fix error in doc.
  docs/zh/06-advanced/06-TDgpt/05-forecast/index.md
Labels: team engine

#31309 chore: upload keeper coverage to Codecov
  .github/workflows/taoskeeper-build.yml
  tools/keeper/README-CN.md
  tools/keeper/README.md
Labels: team tools

#31315 test(benchmark): add dsn field in TD-32913-2.json
  tests/army/tools/benchmark/basic/json/TD-32913-2.json
Labels: team tools

#31334 feat: [TS-6100] Parse create stream sql: Refactor.
  include/util/taoserror.h
  source/common/src/msg/streamMsg.c
  source/libs/nodes/src/nodesUtilFuncs.c
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parTranslater.c
  source/libs/parser/test/parInitialCTest.cpp
  source/libs/parser/test/parStreamTest.cpp
  test/cases/13-StreamProcessing/02-Stream/test_create_stream_syntax.py
Labels: team engine

#31223 Update cases.task
  tests/parallel_test/cases.task
  tests/parallel_test/run.sh
Labels: team platform

#31335 test:alter cron time
  .github/workflows/tdengine-test-coverage.yml
Labels: team platform

#31347 Revert "fix TD-35057 and TD-35346"
  test/ci/pytest.sh
  test/new_test_framework/taostest/components/taosd.py
  test/new_test_framework/utils/before_test.py
Labels: team platform

#31349 feat: [TS-6100] Parse create stream sql: Add more unit test.
  source/common/src/msg/streamMsg.c
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parTranslater.c
  source/libs/parser/test/mockCatalog.cpp
  source/libs/parser/test/parStreamTest.cpp
Labels: team engine

#31350 feat: [TS-6100] Parse create stream sql: Fix bugs and change error me…
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31343 fix(stmt2):get fields select query memleak
  source/client/src/clientStmt2.c
  source/client/test/stmt2Test.cpp
Labels: team engine

#31310 docs: jdbc support ipv6 and blob datatype
  docs/en/14-reference/05-connector/14-java.md
  docs/zh/14-reference/05-connector/14-java.mdx
Labels: team tools

#31351 fix: bounded cols is expected for supertable insertion。
  source/libs/parser/src/parInsertSql.c
Labels: team engine

#31359 fix: explorer.toml not installed to configDir
  packaging/tools/install.sh
Labels: team platform

#31333 fix(gpt): fix the error in future co-variate forecasting.
  source/client/test/clientTests.cpp
  tests/script/tsim/analytics/basic0.sim
  tools/tdgpt/cfg/taosanode.ini
  tools/tdgpt/script/install.sh
  tools/tdgpt/taosanalytics/tsfmservice/moirai-server.py
Labels: team engine

#31336 update enableIpv6 doc
  docs/en/14-reference/01-components/01-taosd.md
  docs/zh/14-reference/01-components/01-taosd.md
Labels: team engine

#31353 fix: add vnode/storage_size for show grants
  source/dnode/mnode/impl/src/mndGrant.c
Labels: team engine

#31324 upgrade the Node.js version and improve the documentation
  docs/en/07-develop/01-connect.md
  docs/en/14-reference/05-connector/35-node.md
  docs/examples/node/package.json
  docs/zh/07-develop/01-connect/index.md
  docs/zh/14-reference/05-connector/35-node.mdx
Labels: team tools

#31364 fix:update paths-ignore in new-framework-test.yml for pull requests
  .github/workflows/new-framework-test.yml
Labels: team platform

#31368 feat: [TS-6100] Parse create stream sql: Add more ut.
  source/common/src/msg/streamMsg.c
  source/libs/parser/src/parAstParser.c
  source/libs/parser/src/parTranslater.c
  source/libs/parser/test/mockCatalog.cpp
  source/libs/parser/test/parStreamTest.cpp
Labels: team engine

#31367 refactor: update container_build.sh to include branch option for taosadapter
  tests/parallel_test/container_build.sh
  tools/CMakeLists.txt
Labels: team platform

#31356 fix: taosdump windows pthread_mutex_unlock crash(main)
  tests/army/frame/eos.py
  tests/army/frame/epath.py
  tests/army/simpletest.bat
  tools/taos-tools/src/dumpUtil.c
  tools/taos-tools/src/taosdump.c
Labels: team tools

#31369 enh: update markdownlint configuration to check only changed markdown files
  .github/workflows/tdengine-docs-ci.yml
  docs/.markdownlint-cli2.jsonc
  docs/zh/03-intro.md
  docs/zh/04-get-started/03-package.md
  docs/zh/04-get-started/_01-install.md
Labels: team platform

#31357 fix: taosdump windows pthread_mutex_unlock crash(3.0)
  .github/workflows/tdengine-test.yml
  tests/army/frame/eos.py
  tests/army/frame/epath.py
  tests/army/simpletest.bat
  tools/taos-tools/src/dumpUtil.c
  tools/taos-tools/src/taosdump.c
Labels: team tools

#31370 doc(gpt): update faq about how to handle timeout problem.
  docs/zh/06-advanced/06-TDgpt/11-faq.md
Labels: team engine

#31379 feat: [TS-6100] Parse create stream sql: Add error ut and fix bugs.
  include/libs/planner/planner.h
  include/util/taoserror.h
  source/libs/nodes/src/nodesCodeFuncs.c
  source/libs/parser/src/parTranslater.c
  source/libs/parser/src/parUtil.c
  source/libs/parser/test/CMakeLists.txt
  source/libs/parser/test/parStreamTest.cpp
  source/libs/planner/src/planLogicCreater.c
  source/util/src/terror.c
  test/cases/13-StreamProcessing/99-Others/test_dev_basic3.py
  test/cases/13-StreamProcessing/99-Others/test_dev_basic6.py
Labels: team engine

#31381 docs: update nodejs connector version
  docs/en/14-reference/05-connector/35-node.md
  docs/examples/node/package.json
  docs/zh/14-reference/05-connector/35-node.mdx
Labels: team tools

#31331 update ip -white-list log
  docs/examples/c/connect_example.c
  source/client/src/clientMain.c
  source/common/src/tglobal.c
  source/dnode/mgmt/node_mgmt/src/dmTransport.c
  source/dnode/mnode/impl/src/mndProfile.c
  source/dnode/mnode/impl/src/mndUser.c
  source/libs/tcs/test/tcsTest.cpp
  source/libs/transport/inc/transComm.h
  source/libs/transport/src/transComm.c
  source/libs/transport/src/transSvr.c
  tests/script/api/whiteListTest.c
  tests/script/sim.sql
  tests/script/tsim/show/basic.sim
  tests/script/tsim/valgrind/checkError1.sim
Labels: team engine

#31384 docs: update perspective doc for node
  docs/en/10-third-party/03-visual/02-perspective.md
  docs/en/10-third-party/03-visual/perspective/prsp_architecture.webp
  docs/en/10-third-party/03-visual/perspective/prsp_view.webp
  docs/en/assets/perspective-01.png
Labels: internal

#31386 Feat/ts 6100 smj
  source/libs/nodes/src/nodesUtilFuncs.c
  source/libs/parser/src/parTranslater.c
  source/libs/parser/test/parStreamTest.cpp
Labels: team engine

#31378 enh: add more check of submit message
  source/dnode/vnode/src/vnd/vnodeSvr.c
Labels: team engine

#31397 docs(jdbc): add varchar as string doc
  docs/en/14-reference/05-connector/14-java.md
  docs/zh/14-reference/05-connector/14-java.mdx
Labels: team tools

#31382 docs: improve formatting and clarity in taosAdapter documentation
  docs/en/14-reference/01-components/03-taosadapter.md
  docs/zh/14-reference/01-components/03-taosadapter.md
Labels: team tools

#31398 fix(shell): incorrect cursor position after entering Chinese in taos_shell in ARM environment
  tools/shell/src/shellCommand.c
Labels: team tools

#31390 relean mutex when returning
  source/dnode/vnode/src/tsdb/tsdbCache.c
  tests/system-test/0-others/information_schema.py
Labels: team engine

#31389 releasing lock when oom
  source/dnode/vnode/src/tsdb/tsdbCache.c
Labels: team engine

#31399 fix: race condition of update tsDndUpTime
  source/dnode/mgmt/mgmt_dnode/src/dmWorker.c
Labels: team engine

#31395 update set_connnect_option error
  docs/examples/c/connect_example.c
  source/client/src/clientMain.c
  source/client/test/connectOptionsTest.cpp
Labels: team engine

#31407 enh: make info to debug
  source/dnode/vnode/src/vnd/vnodeSvr.c
Labels: team engine

#31410 feat: [TS-6100] Parse create stream sql: Fix out col / tag wrong length
  source/libs/parser/src/parTranslater.c
  test/cases/13-StreamProcessing/20-UseCase/test_three_gorges_phase1.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_check.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_check_bug.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_concat.py
  test/cases/13-StreamProcessing/99-Others/test_dev_basic1.py
  test/cases/13-StreamProcessing/99-Others/test_dev_basic3.py
  test/cases/13-StreamProcessing/99-Others/test_dev_basic6.py
Labels: team engine

#31404 enh: smooth the pressure caused by logRotate thread when performing l…
  source/util/src/tlog.c
  tests/system-test/0-others/taosdlog.py
Labels: team engine

#31266 feat(keeper): support ipv6
  .github/workflows/taoskeeper-build.yml
  tools/keeper/db/connector_test.go
  tools/keeper/go.mod
  tools/keeper/go.sum
Labels: team tools

#31425 add debug info
  test/conftest.py
  test/new_test_framework/taostest/components/taosd.py
Labels: team platform

#31422 feat: update database creation to keep data for 36500 days in various test cases
  tests/parallel_test/run.sh
  tests/system-test/2-query/abs.py
  tests/system-test/2-query/and_or_for_byte.py
  tests/system-test/2-query/irate.py
  tests/system-test/2-query/last_row.py
Labels: team platform

#31348 fix(parser): set current statement precision use join table precision
  source/libs/parser/src/parTranslater.c
  test/cases/22-Show/test_show_basic.py
  test/cases/29-JoinQueries/test_join_ns_db.py
  test/cases/50-Others/01-Valgrind/test_valgrind_checkerror1.py
  test/ci/cases.task
Labels: team engine

#31430 fix: compatibility ci problems.
  tests/system-test/0-others/compatibility_basic.py
Labels: team engine

#31415 fix: add test case for table column limit
  test/cases/03-Tables/01-NormalTables/01-Create/test_normal_table_column_num_limit.py
  test/ci/cases.task
Labels: team engine

#31438 feat: [TS-6100] Parse create stream sql: Add check when partition by …
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31439 feat: [TS-6100] Parse create stream sql: Make sure calc plan always n…
  source/libs/planner/src/planOptimizer.c
Labels: team engine

#31418 fix(gpt): fix error when the primary key exists.
  source/libs/executor/src/forecastoperator.c
  tests/script/tsim/analytics/basic0.sim
  tools/tdgpt/script/install.sh
Labels: team engine

#31413 docs: NODE-RED for TDengine Plugin (main)
  docs/en/10-third-party/01-collection/12-flink.md
  docs/en/10-third-party/01-collection/13-Node-RED.md
  docs/en/10-third-party/01-collection/img/td-all.webp
  docs/en/10-third-party/01-collection/img/td-catch.webp
  docs/en/10-third-party/01-collection/img/td-consumer.webp
  docs/en/10-third-party/01-collection/img/td-frame.webp
  docs/en/10-third-party/01-collection/img/td-reader.webp
  docs/en/10-third-party/01-collection/img/td-writer.webp
  docs/zh/10-third-party/01-collection/13-NODE-RED.html
  docs/zh/10-third-party/01-collection/13-NODE-RED.md
  docs/zh/10-third-party/01-collection/img/td-all.webp
  docs/zh/10-third-party/01-collection/img/td-catch.webp
  docs/zh/10-third-party/01-collection/img/td-consumer.webp
  docs/zh/10-third-party/01-collection/img/td-frame.webp
  docs/zh/10-third-party/01-collection/img/td-reader.webp
  docs/zh/10-third-party/01-collection/img/td-writer.webp
Labels: team tools

#31199 docs(dataIn): add more descriptions for `delay` option in multi datasources
  docs/zh/06-advanced/05-data-in/13-mysql.mdx
  docs/zh/06-advanced/05-data-in/14-postgres.mdx
  docs/zh/06-advanced/05-data-in/15-oracle.mdx
  docs/zh/06-advanced/05-data-in/16-mssql.mdx
  docs/zh/06-advanced/05-data-in/17-mongodb.mdx
Labels: team tools

#31452 feat: [TS-6100] Parse create stream sql: Fix create stream systable q…
  source/libs/planner/src/planPhysiCreater.c
Labels: team engine

#31432 fix retry interval count
  source/libs/transport/src/transCli.c
Labels: team engine

#31451 fix: insert using sql use the same stb and ctb name.
  source/libs/parser/src/parInsertSql.c
  tests/army/insert/auto_create_insert.py
Labels: team engine

#31454 feat(stream): set operator
  source/libs/executor/inc/executil.h
  source/libs/executor/inc/executorInt.h
  source/libs/executor/src/aggregateoperator.c
  source/libs/executor/src/countwindowoperator.c
  source/libs/executor/src/dynqueryctrloperator.c
  source/libs/executor/src/eventwindowoperator.c
  source/libs/executor/src/exchangeoperator.c
  source/libs/executor/src/executorInt.c
  source/libs/executor/src/externalwindowoperator.c
  source/libs/executor/src/filloperator.c
  source/libs/executor/src/groupoperator.c
  source/libs/executor/src/hashjoinoperator.c
  source/libs/executor/src/mergejoinoperator.c
  source/libs/executor/src/mergeoperator.c
  source/libs/executor/src/operator.c
  source/libs/executor/src/projectoperator.c
  source/libs/executor/src/sortoperator.c
  source/libs/executor/src/sysscanoperator.c
  source/libs/executor/src/timesliceoperator.c
  source/libs/executor/src/timewindowoperator.c
Labels: team engine

#31401 feat:insert into subquery
  docs/en/14-reference/03-taos-sql/06-insert.md
  docs/zh/14-reference/03-taos-sql/06-insert.md
  include/libs/executor/storageapi.h
  source/dnode/vnode/inc/vnode.h
  source/dnode/vnode/src/inc/tsdb.h
  source/dnode/vnode/src/tsdb/tsdbRead2.c
  source/dnode/vnode/src/vnd/vnodeQuery.c
  source/libs/executor/src/dataInserter.c
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parTranslater.c
  test/cases/06-DataIngestion/05-Others/test_insert_select.py
Labels: team engine

#31455 feat: [TS-6100] Parse create stream sql: support fill_history without…
  source/libs/parser/inc/sql.y
  source/libs/parser/src/parAstCreater.c
Labels: team engine

#31427 docs: add OpenMetrics support and configuration details to taosAdapter documentation
  docs/en/14-reference/01-components/03-taosadapter.md
  docs/zh/14-reference/01-components/03-taosadapter.md
Labels: team tools

#30933 Update 07-supported.md
  docs/zh/14-reference/07-supported.md
Labels: team platform

#31426 refactor: clean up install_spec.sh by removing unused functions and a…
  packaging/tools/install_spec.sh
Labels: team platform

#31457 feat: [TS-6100] Parse create stream sql: Improve error msg when check…
  source/libs/parser/src/parTranslater.c
  source/libs/parser/src/parUtil.c
Labels: team engine

#31458 Feat/ts 6100 ver
  include/libs/new-stream/stream.h
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31460 feat: [TS-6100] Parse create stream sql: Change default out subtable …
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31465 feat: [TS-6100] Parse create stream sql: Fix out table length bug
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31477 check catalog field in docstring
  .github/scripts/validate_tests.py
Labels: team platform

#31479 feat: [TS-6100] Parse create stream sql: Add more serialize/deserialize
  include/libs/nodes/plannodes.h
  source/libs/command/src/explain.c
  source/libs/executor/src/countwindowoperator.c
  source/libs/executor/test/queryPlanTests.cpp
  source/libs/nodes/src/nodesCodeFuncs.c
  source/libs/nodes/src/nodesMsgFuncs.c
  source/libs/nodes/src/nodesUtilFuncs.c
  source/libs/planner/src/planPhysiCreater.c
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
Labels: team engine

#31441 refactor: remove unused fileLock mutex from SVnodeMgmt structure
  source/dnode/mgmt/mgmt_vnode/inc/vmInt.h
  source/dnode/mgmt/mgmt_vnode/src/vmFile.c
  source/dnode/mgmt/mgmt_vnode/src/vmInt.c
Labels: team engine

#31434 fix(taosBenchmark): tag config parameter 'gen: order' is invalid
  tests/army/tools/benchmark/basic/insert_tag_order_sml.py
  tests/army/tools/benchmark/basic/insert_tag_order_sql.py
  tests/army/tools/benchmark/basic/insert_tag_order_stmt.py
  tests/army/tools/benchmark/basic/insert_tag_order_stmt2.py
  tests/army/tools/benchmark/basic/json/insert_tag_order.json
  tests/parallel_test/cases.task
  tools/taos-tools/inc/benchData.h
  tools/taos-tools/src/benchData.c
  tools/taos-tools/src/benchInsert.c
  tools/taos-tools/src/benchInsertMix.c
  tools/taos-tools/src/benchJsonOpt.c
Labels: team tools

#31485 fix: update path ignore pattern for analytics tests in workflow
  .github/workflows/new-framework-test.yml
Labels: team platform

#31473 docs: move Node-RED from 01-collection to 09-iot folder
  docs/en/10-third-party/09-iot/01-Node-RED.md
  docs/en/10-third-party/09-iot/img/td-all.webp
  docs/en/10-third-party/09-iot/img/td-catch.webp
  docs/en/10-third-party/09-iot/img/td-consumer.webp
  docs/en/10-third-party/09-iot/img/td-frame.webp
  docs/en/10-third-party/09-iot/img/td-reader.webp
  docs/en/10-third-party/09-iot/img/td-writer.webp
  docs/en/10-third-party/09-iot/index.md
  docs/zh/10-third-party/01-collection/13-NODE-RED.html
  docs/zh/10-third-party/09-iot/01-Node-RED.md
  docs/zh/10-third-party/09-iot/img/td-all.webp
  docs/zh/10-third-party/09-iot/img/td-catch.webp
  docs/zh/10-third-party/09-iot/img/td-consumer.webp
  docs/zh/10-third-party/09-iot/img/td-frame.webp
  docs/zh/10-third-party/09-iot/img/td-reader.webp
  docs/zh/10-third-party/09-iot/img/td-writer.webp
  docs/zh/10-third-party/09-iot/index.md
Labels: team tools

#31492 feat: [TS-6100] Fix vtable tag error when tag is null
  source/libs/executor/src/virtualtablescanoperator.c
Labels: team engine

#31420 fix: Out of memory in queue and Sync leader unreachable error
  include/util/tdef.h
  source/client/src/clientEnv.c
  source/dnode/mgmt/node_mgmt/src/dmTransport.c
  source/libs/transport/src/transCli.c
  source/libs/transport/src/transComm.c
  source/libs/transport/src/transSvr.c
Labels: team engine

#31494 fix(sml): change soure flag of alteing stable to avoid error in tmq
  include/common/tmsg.h
  source/client/src/clientSml.c
  source/dnode/mnode/impl/src/mndStb.c
Labels: team engine

#31475 fix: transcli crash (TS-6730)
  source/libs/transport/src/transCli.c
Labels: team engine

#31482 fix(gpt): dynamic allocate the option buffer and remove the limitation on the option serialization.
  source/common/src/tanalytics.c
  source/libs/executor/src/forecastoperator.c
  tests/script/tsim/analytics/basic0.sim
Labels: team engine

#31503 fix: add verification of vgroup binding parameters
  tools/taos-tools/src/benchInsert.c
  tools/taos-tools/src/benchMain.c
Labels: team tools

#31237 feat: add password encryption algorithm support and related configura…
  docs/en/08-operation/16-security.md
  docs/en/14-reference/01-components/01-taosd.md
  docs/zh/08-operation/16-security.md
  docs/zh/14-reference/01-components/01-taosd.md
  include/common/tglobal.h
  source/common/src/tglobal.c
  source/dnode/mnode/impl/inc/mndDef.h
  source/dnode/mnode/impl/inc/mndUser.h
  source/dnode/mnode/impl/src/mndProfile.c
  source/dnode/mnode/impl/src/mndUser.c
  tests/script/tsim/show/basic.sim
  tests/script/tsim/valgrind/checkError1.sim
  tests/system-test/0-others/taosd_audit.py
Labels: team engine

#31510 fix: alter minReservedMemorySize error code.
  docs/en/14-reference/09-error-code.md
  docs/zh/14-reference/09-error-code.md
  include/util/taoserror.h
  source/util/src/terror.c
  source/util/src/tmempool.c
  test/ci/container_build.sh
  test/ci/container_build_newmachine.sh
  test/ci/run_check_assert_container.sh
  test/ci/run_check_void_container.sh
  test/ci/run_container.sh
  test/ci/run_scan_container.sh
  test/new_test_framework/taostest/util/common.py
Labels: team engine

#31508 enh/TS-5619-add-case-crypted-pass
  test/cases/23-Users/test_user_crypted_pass.py
  test/ci/cases.task
  tests/coverage/covtests.task
  tests/system-test/0-others/taosd_audit.py
Labels: team engine

#31521 feat: [TS-6100] Fix single table judging condition
  include/libs/nodes/querynodes.h
  source/libs/parser/src/parTranslater.c
  source/libs/planner/src/planLogicCreater.c
Labels: team engine

#31530 Feat/ts 6100 3.0 mm
  source/dnode/vnode/src/vnd/vnodeStream.c
Labels: team engine

#31532 feat(stream): fix coredump when destroy reader
  source/libs/new-stream/src/streamReader.c
Labels: team engine

#31531 fix(stream): fix process of new wal meta in stream trigger task
  source/libs/new-stream/inc/streamTriggerMerger.h
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31523 feat: [TS-6100] Add outtable full name's md5 to outSubtable name
  source/libs/parser/src/parTranslater.c
Labels: team engine

#31536 test: subquery cases
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
  test/cases/13-StreamProcessing/31-OldTsimCases/test_oldcase_basic2.py
  test/ci/streamlist_for_ci.task
Labels: team engine

#31198 Feat: add write metrics.
  docs/zh/14-reference/01-components/01-taosd.md
  include/common/systable.h
  include/common/tglobal.h
  include/common/tmsg.h
  include/libs/metrics/metrics.h
  include/libs/sync/sync.h
  source/common/src/tglobal.c
  source/dnode/mgmt/mgmt_dnode/inc/dmInt.h
  source/dnode/mgmt/mgmt_dnode/src/dmInt.c
  source/dnode/mgmt/mgmt_dnode/src/dmWorker.c
  source/dnode/mgmt/mgmt_vnode/src/vmHandle.c
  source/dnode/mgmt/node_mgmt/inc/dmMgmt.h
  source/dnode/mgmt/node_mgmt/inc/dmNodes.h
  source/dnode/mgmt/node_mgmt/src/dmEnv.c
  source/dnode/mgmt/node_mgmt/src/dmMetrics.c
  source/dnode/mgmt/node_util/CMakeLists.txt
  source/dnode/mgmt/node_util/inc/dmUtil.h
  source/dnode/vnode/inc/vnode.h
  source/dnode/vnode/src/inc/vnodeInt.h
  source/dnode/vnode/src/tsdb/tsdbFS2.c
  source/dnode/vnode/src/tsdb/tsdbMerge.c
  source/dnode/vnode/src/vnd/vnodeCommit.c
  source/dnode/vnode/src/vnd/vnodeQuery.c
  source/dnode/vnode/src/vnd/vnodeSvr.c
  source/libs/CMakeLists.txt
  source/libs/metrics/CMakeLists.txt
  source/libs/metrics/inc/metricsInt.h
  source/libs/metrics/src/metrics.c
  source/libs/metrics/test/CMakeLists.txt
  source/libs/metrics/test/metricsTest.cpp
  source/libs/monitorfw/src/taos_metric_formatter.c
  source/libs/sync/CMakeLists.txt
  source/libs/sync/inc/syncInt.h
  source/libs/sync/src/syncMain.c
  source/libs/sync/src/syncPipeline.c
  source/libs/sync/src/syncRaftLog.c
  tests/system-test/0-others/taosdNewMonitor.py
  tools/keeper/api/gen_metric.go
Labels: team engine

#31480 add stmt2 docs
  docs/en/14-reference/05-connector/10-cpp.md
  docs/zh/14-reference/05-connector/10-cpp.mdx
Labels: team engine

#31538 fix: 避免while循环打印无效日志
  packaging/docker/bin/entrypoint.sh
Labels: from community

#31537 Feat/ts 6100 3.0 mm0630
  source/dnode/vnode/src/vnd/vnodeStream.c
  source/libs/scalar/src/scalar.c
  source/libs/wal/src/walRead.c
Labels: team engine

#31540 chore: add deepwiki badge
  README.md
Labels: team platform

#31541 test: report bugs
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding_bug3.py
Labels: team engine

#31533 fix(query) subscriptions memory leak
  source/dnode/vnode/src/tq/tqScan.c
Labels: team engine

#31545 test: add subquery cases
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
Labels: team engine

#31550 test: reproduce bug
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding_bug6.py
Labels: team engine

#31551 test:more
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding_bug1.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding_bug8.py
Labels: team engine

#31553 test: more cases
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding.py
  test/cases/13-StreamProcessing/07-SubQuery/test_subquery_sliding_bug9.py
Labels: team engine

#31548 docs: upgrade the Python version and add the flink version description
  docs/en/07-develop/01-connect.md
  docs/en/10-third-party/01-collection/12-flink.md
  docs/en/14-reference/02-tools/10-taosbenchmark.md
  docs/en/14-reference/05-connector/30-python.md
  docs/en/14-reference/05-connector/35-node.md
  docs/zh/07-develop/01-connect/index.md
  docs/zh/10-third-party/01-collection/12-flink.md
  docs/zh/14-reference/02-tools/10-taosbenchmark.md
  docs/zh/14-reference/05-connector/30-python.mdx
  docs/zh/14-reference/05-connector/35-node.mdx
  test/ci/container_build_newmachine.sh
  test/ci/run_case.sh
  test/pyproject.toml
  test/requirements.txt
  test/uv.lock
  tests/ci/Dockerfile
  tests/ci/container_build_newmachine.sh
  tests/parallel_test/run_case.sh
  tools/tdgpt/requirements.txt
Labels: team tools

#31558 fix(stream): fix checkpoint generation in stream trigger task
  source/libs/new-stream/src/streamTriggerTask.c
Labels: team engine

#31555 fix: enhance remote command handling and local host checks in run script
  test/ci/run.sh
  tests/parallel_test/run.sh
Labels: team platform

#31543 docs: add DECIMAL type representation and usage notes for C# connector
  docs/en/14-reference/05-connector/40-csharp.md
  docs/zh/14-reference/05-connector/40-csharp.mdx
Labels: team tools
